### ISSUE TITLE
References to CWE and OWASP Mobile Top 10

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1]
In the guide we created in Google Docs we had also references to CWE and the OWASP Mobile Top 10. I think we should continue this, to reference properly to a common vulnerability type or weakness if one is applicable to the test case. I just put it in the test case I am migrating right now from Google Docs to GitHub.  
What do you guys think?

![screenshot at oct 09 14-59-19](https://cloud.githubusercontent.com/assets/5951320/19218618/fc8e0bd6-8e30-11e6-9da6-55d87d52fb26.png)

**Comment by b-mueller** [comment]
Yes, definitely! I also added both to the MASVS recently.

**Comment by sushi2k** [comment]
I put the reference to OWASP Mobile Top 10 and CWE into the template. Will close this now. 

https://github.com/OWASP/owasp-mstg/commit/a08488f6e2d1134ab3af5e345ae2ce55a9788b9f
