### ISSUE TITLE
Create new checklist file

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1001]
The checklist (XLS) needs updating right before going to 1.2.0 of the MASVS.

**Comment by meetinthemiddle-be** [comment]
I can help on this one. If nobody is taking that up, feel free to assign to me.

**Comment by commjoen** [comment]
The file is located in Heading off to Bay Area to present at @appsecusa
<https://twitter.com/appsecusa>. Excited to have this opportunity.

Share my story and hear from others as well.

#appsec #owasp #conference

Op di 9 okt. 2018 11:50 schreef meetinthemiddle-be <notifications@github.com

**Comment by commjoen** [comment]
Done

**Comment by meetinthemiddle-be** [comment]
Just an idea : Would it be an idea to work with intermediary "permalinks"? This keeps the flexibility in altering the URL's without breaking the links in the Excel checklist.

**Comment by commjoen** [comment]
Let's create links to github with the tags :D

**Comment by A-AFTAHI** [comment]
I checked the checklist and found that some sentences are expressed diffrently from the MASVS and i'm not sure if these has to be changed. please check these examples to make sure everything is alright: 4.2, 4.7 and 5.2
thanks

**Comment by commjoen** [comment]
Beautifully done, all seems to make sense now.
