### ISSUE TITLE
Migrate hackmes to omtg playground and automate

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1015]
Currenlty, the maintenance of the OMTG and the hackmes gives a lot of overhead. We should merge them together and apply the same automation as we do for the crackmes already.

**Comment by commjoen** [comment]
- [ ] Add kottlin ap
- [ ] do paperwork for incorporating the playground into the omtg project

**Comment by sushi2k** [comment]
I will push the source code to the MSTG Github repo and also open source another Android Kotlin App.

**Comment by cpholguera** [comment]
Any news here? @sushi2k

**Comment by cpholguera** [comment]
covered in https://github.com/OWASP/owasp-mstg/issues/1946
