### ISSUE TITLE
MASVS 7.8 is missing for both Android and iOS

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1017]
MASVS 7.8 is missing for both iOS and Android:
 | **7.8** | In unmanaged code, memory is allocated, freed and used securely.  | ✓ | ✓ |

- [x] Explain what it is in general testing guide in terms of memory management and corruption
- [x] Explain what it is in terms of cleaning up keys in the general testing guide
- [x] explain the calls to look for in the general testing guide
- [x] Add Android JNI, NDK parts
- [x] Add iOS wrapping and unsafe code in obj-c/swift

**Comment by sushi2k** [comment]
Unmanaged code is defined as C/C++ code

**Comment by commjoen** [comment]
Detect it on android with https://github.com/pnfsoftware/jnihelper

**Comment by commjoen** [comment]
Android is fixed, will fix iOS in the next branch
