### ISSUE TITLE
0x6b - Vendor neutrality

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#102]
In "Basic Security Testing" (iOS), as OWASP is vendor neutral, unfortunately company names (other than Apple in that case) may not be cited. However, "vantagepoint" is mentioned several times. Should it be changed to something neutral? :-)

The logic is the same for "sg" (Singapore).

**Comment by b-mueller** [comment]
"Vantagepoint" pops up in some crackme tutorials as I use it as a package name / company identifier when writing code. I'm also signing iOS apps with the company cert, so I need to use the matching team identifier. Personally I don't think it's inappropriate to leave it in this context - you'll also see com.mrw.xxx in security books when Drozer is used and such. It's not an endorsement of the company's services or products. If this would be a problem, we'd have to censor everything that refers to commercial companies (even more so when showing tools like BURP Proxy, IDA Pro, JEB, and others).

What does everyone else think?
