### ISSUE TITLE
QA - iOS Testing Local Authentication

### ISSUE THREAD

**Issue by CelloBin22** [OWASP/owasp-mstg#1031]
Noticed that in https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06f-Testing-Local-Authentication.md a reference to the OWASP MASVS is incorrect:

V4.8: "Biometric authentication, if any, is not event-bound (i.e. using an API that simply returns "true" or "false"). Instead, it is based on unlocking the keychain/keystore."

It should actually be 4.7 according to the v1.1 standard.

**Comment by commjoen** [comment]
Hi @CelloBin22 ,
Welcome to the MSTG project! 
Thank you for your Q/A! You're totally right: in the MASVS pdf release (english) 1.1 we apparently made a mistake: 4.7 and 4.8 got mixed up. So in the MSTG, MASVS RU, MASVS ES it is correct... We will fix this soon 👍 .

**Comment by commjoen** [comment]
We will close the issue here, and continue at https://github.com/OWASP/owasp-masvs/issues/140 as it needs to be fixed there.
