### ISSUE TITLE
List down companies that are using MSTG/MASVS

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1046]
**Describe the issue**
We should list down companies that are using the MASVS/MSTG (this was feedback during the OWASP Project Review)

**Comment by meetinthemiddle-be** [comment]
I'll ask my current client's CISO if they can be mentioned by name in this context. They're one of the bigger bio-pharma companies in Europe, so would be a nice reference.

**Comment by commjoen** [comment]
I will ask a few companies as well :)

**Comment by commjoen** [comment]
Feel free to list them here as well

**Comment by commjoen** [comment]
- [Infosec](Infosec.com.br)

**Comment by securityvoid** [comment]
We use this as the initial basis of what we test at @CyberNinjas .

**Comment by meetinthemiddle-be** [comment]
I got a no-go from my current client's CISO on this front. It was worth a shot as that would've been a nice reference, but alas to no avail. I hope that we can get more names on this list though, so anyone who reads this: please try your best to convince your superiors to approve using their company name :)

**Comment by dineshdinz** [comment]
@Briskinfosec we are using the MASVS in our projects.

[Briskinfosec Technology and Consulting Pvt Ltd](https://www.briskinfosec.com/)

**Comment by TheDauntless** [comment]
My company also uses the MASVS during assessments:

* [NVISO CVBA](https://www.nviso.be)

**Comment by commjoen** [comment]
@sushi2k / @TheDauntless : question is now: where do we put this :) ?

**Comment by TheDauntless** [comment]
I suggest on the FrontisPiece, as that's the place where other commercial companies are listed.

But maybe that's too prominent?

**Comment by commjoen** [comment]
My suggestion would be to put it as part of the README.md :).

**Comment by sushi2k** [comment]
I also think readme would be sufficient. Let's keep the companies in the frontispiece that are supporting us actively.

**Comment by commjoen** [comment]
Readme.md it is 👍

**Comment by commjoen** [comment]
https://www.europeanpaymentscouncil.eu/document-library/implementation-guidelines/mobile-initiated-sepa-credit-transfer-interoperability, NIST, http://egovstandards.gov.in/notified-standards-0 and more

**Comment by cldrn** [comment]
I talked to @commjoen about it this morning but I just saw this ticket. I think a dedicated page for this would be nice. It will help promote MSTG/MASVS.

**Comment by commjoen** [comment]
Fixed in #1313
