### ISSUE TITLE
Automation of MASVS

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1047]
**Describe the issue**
We should reach out to Davide if he is interested writing about automation of the MASVS into the MSTG. 

https://www.owasp.org/images/f/fb/V2_-_OWASP_Buscharest_Davide_Cioccia.pdf
https://github.com/ing-bank/bdd-mobile-security-automation-framework

**Comment by commjoen** [comment]
I have send him an email, let's see what happens.

**Comment by sushi2k** [comment]
I just pinged him.

**Comment by commjoen** [comment]
Thank you for joining the project @david3107 ! As you know, we were amazed by your work on the automation of the MASVS requirements! We would love to have some write up about it inside the MSTG, so that people can follow your lead in doing automated verifications :)

**Comment by david3107** [comment]
Hey @commjoen thanks, you guys are doing an amazing jobs with the MSTG and MASVS. I will definitely put more content in the automation section.

**Comment by commjoen** [comment]
@david3107 any updates on this :) ?

**Comment by commjoen** [comment]
Hi @david3107 : do you have any updates on this :) ?

**Comment by cpholguera** [comment]
Closed after long inactivity. Please re-open if you've something new. Thanks!
