### ISSUE TITLE
Why are we pointing to commercial website instead of product page

### ISSUE THREAD

**Issue by anantshri** [OWASP/owasp-mstg#1066]
This issue is regarding Pull Requst : https://github.com/OWASP/owasp-mstg/pull/1062

Why are we pointing to specific website and not a particular product.
Its commercial and that should also be clearly noted if we care mixing free / opensource stuff with commercial entities. 

Don't want OWASP-MSTG to grow into another promotion platform.

**Comment by commjoen** [comment]
LGTM :).

**Comment by sushi2k** [comment]
Done and closed https://github.com/OWASP/owasp-mstg/pull/1069
