### ISSUE TITLE
Security libraries removed from Testing Tools section

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1068]
**Describe the issue**
In the Testing Tools section we had a sub section called "Security libraries". This doesn't really fit into testing tools, as this section should describe tools that you can use for verifying vulnerabilites and analyse app.s 

**Optional: Additional context**

I removed the following section. Either we create an additional chapter "Security libraries" that summarises different libraries that can be suggested to developers to fix these issues or we should move them directly into the chapters where they belong as best practice. I would suggest we move it into the chapters and double check also the libraries if they are outdated and if they actually make sense. 

#### Security Libraries

- [Java AES Crypto](https://github.com/tozny/java-aes-crypto "Java AES Crypto") - A simple Android class for encrypting & decrypting strings, aiming to avoid the classic mistakes that most such classes suffer from.
- [Proguard](https://www.guardsquare.com/en/products/proguard "Proguard") - ProGuard is a free Java class file shrinker, optimizer, obfuscator, and preverifier. It detects and removes unused classes, fields, methods, and attributes.
- [SQL Cipher](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/ "SQL Cipher") - SQLCipher is an open source extension to SQLite that provides transparent 256-bit AES encryption of database files.
- [Secure Preferences](https://github.com/scottyab/secure-preferences "Secure Preferences") - Android Shared preference wrapper than encrypts the keys and values of Shared Preferences.
- [Trusted Intents](https://github.com/guardianproject/TrustedIntents "Trusted Intents") - Library for flexible trusted interactions between Android apps.
- [Capillary](https://github.com/google/capillary "Capillary") - Capillary is a library to simplify the sending of end-to-end encrypted push messages from Java-based application servers to Android clients.

**Comment by commjoen** [comment]
There are tons of security libraries mentioned throughout the mstg. Maybe we can create a simple url overview of mentioned security libraries in version 1.2? (Summit release)

**Comment by sushi2k** [comment]
Let's make this as part of release 1.2 so that all libraries mentioned in this ticket are mentioned at the right place in the MSTG.

**Comment by sushi2k** [comment]
I didn't include https://github.com/guardianproject/TrustedIntents, as the repo is now 3 years old and not maintained.

**Comment by commjoen** [comment]
Is fixed in #1120
