### ISSUE TITLE
0x5b - replace 'App' with 'application'

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#107]
In "Basic Security Testing" (Android), 'App' should be replaced with 'application' (with a lower case 'a') throughout the whole chapter.

**Comment by b-mueller** [comment]
That's the question! Right now we're sometimes using "app" and sometimes "application". I've been using "app" most of the time as I'm thinking that in the mobile world "app" is actually the more commonly used term, so using it makes the MSTG more modern & "edgy". What do you think?

**Comment by romualdszkudlarek** [comment]
I tend to agree, I had the same concern while writing 0x5a. At the end, my conclusion was that "app" is more familiar and more cool, while "application" is more traditional and more commonly found in litterature. 
At the end, the wording should be consistent through the whole guide, so we'll have to unify the practice through the different chapter. Maybe we can make a poll in the group? :-)

**Comment by sushi2k** [comment]
I would also say we should use app instead of application. Application by default let's people think about web not mobile. Maybe poll in the slack channel?

**Comment by romualdszkudlarek** [comment]
No problem for me, we just need to keep in mind we'll have a task to use the same naming throughout the whole guide (which is not the case at the moment).
I'll use 'app' in the rest of my writing as it seems to be the favorite solution :-)
