### ISSUE TITLE
0x05c Tampering and Reverse Engineering on Android: Update regarding latest angr release

### ISSUE THREAD

**Issue by Jnchi** [OWASP/owasp-mstg#1076]
Under [Building a Reverse Engineering Environment for Free](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#building-a-reverse-engineering-environment-for-free),

> You can accomplish more elaborate tasks (such as program analysis and automated de-obfuscation) with open source reverse engineering frameworks such as Radare2 and [Angr](https://nilocunger.github.io). 

The new homepage is [angr.io](https://angr.io).

Then under [Installing Angr](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#installing-angr),

> Angr is written in Python 2...

Angr has migrated to Python 3, "As of angr 8, angr will be dropping all Python 2 support and moving to Python 3" ([angr blog](https://angr.io/blog/moving_to_angr_8)).

Finally, in the same section,

> Comprehensive Angr documentation, including an installation guide, tutorials, and usage examples [5], is available on Gitbooks. A complete API reference is also available [6].

I could not find those footnotes anywhere on this page.

<pre>
[5]: https://docs.angr.io
[6]: https://angr.io/api-doc/
</pre>

**Comment by commjoen** [comment]
Thank you for posting @Jnchi ! This sounds like something we should improve. And it seems an easy task as well. Therefore, I will mark it as a "Good first issue" so that it can be fixed for our next milestone.

**Comment by commjoen** [comment]
@Jnchi is the change proposed in #1080 enough?

**Comment by commjoen** [comment]
Closed by merging #1080
