### ISSUE TITLE
Mitigation of tapjacking / overlay attacks are not tested for

### ISSUE THREAD

**Issue by meetinthemiddle-be** [OWASP/owasp-mstg#1103]
**Platform:**
Android

**Description:**
Add a SAST that looks for ``filterTouchesWhenObscured``being set to ``true``, or that ``onFilterTouchEventForSecurity()`` is implemented (source : https://blog.devknox.io/tapjacking-android-prevent/ )

**Comment by commjoen** [comment]
don't forget to set event.flags and MotionEvent.FLAG_WINDOW_IS_OBSCURED

**Comment by exujing** [comment]
From our experience, just implementing "filterTouchesWhenObscured=true" causes usabilitity problem. If a user has a legitimate screen overlay software such as twilight, the app does not allow user interaction and it freezes. Implementing "event.flags and MotionEvent.FLAG_WINDOW_IS_OBSCURED" for sensitive input seems to be a better implementation.

**Comment by sushi2k** [comment]
To-Do:

- [ ] New test case to cover Tapjacking / Screen Overlay should be created.
- [ ] Clarify on naming convention, are both terms (Tapjacking and Screen Overlay used interchangeably or is there a difference)
- [ ] Research best practices and add them to static analysis
- [ ] Add MSTG-Platform-9 to references at the end
