### ISSUE TITLE
Ox5b - Rooting an Android Virtual Device (AVD)

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#111]
In my understanding, adb shells are running as root by default (and it seems we share the same understanding from the content of the paragraph). Maybe this notion has to be clarified to avoid confusion.

**Comment by b-mueller** [comment]
Also not 100%, I'll check at the next opportunity.

**Comment by b-mueller** [comment]
Changed to "Connecting to an Android Virtual Device (AVD) as Root" as a quick fix.
