### ISSUE TITLE
0x06h Testing for Sensitive Functionality Exposure Through IPC missing [iOS]

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1110]
While reviewing 0x06h I realized that "Testing for Sensitive Functionality Exposure Through IPC" is missing for iOS. Now I've seen that there was a [ticket](https://github.com/OWASP/owasp-mstg/issues/376) some time ago and it's closed. However the section in 0x06h is not present.

In addition, in 0x06h "Testing Custom URL Schemes" it is stated that "Apple offers two types of indirect communication: file transfer through AirDrop and custom URL schemes." This is not completely true, there are more, all limited/constrained but definitely more (e.g. UIActivity-based, App Extensions). They should be listed in a "Testing for Sensitive Functionality Exposure Through IPC" Section and that statement removed from "Testing Custom URL Schemes", this section should only talk about URL schemes.

**Comment by commjoen** [comment]
This issue has been adressed partially in #925 as well. Can we close this issue and continue the discussion over there?

**Comment by cpholguera** [comment]
Sure!

**Comment by commjoen** [comment]
Closed and will assign you #925
