### ISSUE TITLE
Upgrade network eavesdropping test description

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1111]
We should include the Android 7.1 changes and onward (e.g.: if you want to pentest, yuou have to recompile the app with allowing user type certs (https://serializethoughts.com/2016/09/10/905/) )

I guess we have to update 0x04f and 0x05g for this 🙂
(0x04f explain that for newer versions (android 7.1 and above) we have to check 0x05g and extend 0x05g for how to get the eavesdropping to work)

**Comment by A-AFTAHI** [comment]
Don't you think that we should refer to 0x05b, which already presents how to hook the app with a proxy, so we will expend it to explain how to do it with Android  7+ ?
i'm a little bit confused because 0x05g also talks about the changes in Android 7+ network config changes.

**Comment by commjoen** [comment]
Finished in #1125, thank you @A-AFTAHI !
