### ISSUE TITLE
Declared spelling mistake in the MSTG document

### ISSUE THREAD

**Issue by 007divyachawla** [OWASP/owasp-mstg#1127]
**Describe the issue**
In Testing Data storage in Android section for Shared Preferences, this particular paragraph has one spelling mistake, please rectify it.

The SharedPreferences API is commonly used to permanently save small collections of key-value pairs. Data stored in a SharedPreferences object is written to a plain-text XML file. The SharedPreferences object can be **declated** world-readable (accessible to all apps) or private. Misuse of the SharedPreferences API can often lead to exposure of sensitive data. Consider the following example:

It should be declared not declated.

**Comment by commjoen** [comment]
Hi @007divyachawla , we have checked the full code on master and we cannot find the spelling issue anywhere. Can you show where you found the spelling mistake?

**Comment by 007divyachawla** [comment]
![image](https://user-images.githubusercontent.com/7563150/51516842-cac19280-1e3e-11e9-84ee-67d021a41dd5.png)

**Comment by 007divyachawla** [comment]
@commjoen I have attached the screen shot please refer to it.

**Comment by commjoen** [comment]
Thank you! Can you copy the url here? because then we know which repo to sync

**Comment by 007divyachawla** [comment]
https://sushi2k.gitbooks.io/the-owasp-mobile-security-testing-guide/content/0x05d-Testing-Data-Storage.html

**Comment by 007divyachawla** [comment]
i am reading from the sushi2k.gitbooks,io here is the link.

**Comment by commjoen** [comment]
Ah I see! Thank you for pointing out that gitbook. This one is very outdated (@sushi2k : can you have a look at it?).
If you want to read it from gitbook, for now please read it from https://mobile-security.gitbook.io/mobile-security-testing-guide/ as that one is way more up to date. Sorry for the inconvinience of having older versions online!

**Comment by 007divyachawla** [comment]
Thanks for the same and to provide the link to the new testing guide. This is latest one 2018, also could you please remove the old version for the same.

**Comment by commjoen** [comment]
@sushi2k manages this gitbook if I am not mistaken. I think he can pick it up :).

**Comment by 007divyachawla** [comment]
Sure thanks for the same.

**Comment by commjoen** [comment]
Let's keep it open for now until the gitbooks are sorted out ;-).

**Comment by 007divyachawla** [comment]
Sure i think it will be good.

**Comment by 007divyachawla** [comment]
@sushi2k please update the MSTG guide with the latest one.

**Comment by sushi2k** [comment]
So this is the link for gitbook that will contain all the updates: 

https://mobile-security.gitbook.io/mobile-security-testing-guide/ 

The old one I just deleted.
