### ISSUE TITLE
book issues

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1156]
This issue covers all the issues we might need to fix for the actual print:

- [x] make sure that the changelog has the same typefont
- [x] make sure that the index actually contains pagenumbers instead of sections. 
**[Sven] I couldn't find anything in the gitbook documenation, but it can be done with CSS, see http://support.typora.io/Auto-Numbering/. Thanks @ThunderSon for the tip!**
- [x] make the grayscale of the photo to be printed a bit lighter **[Sven] This is for the printed version of the book. This would need to be configured in lulu.com settings**
- [x] limit picture size of the mobile app pictures
- [x] center all the pictures, as some are left/right aligned **[Sven] Pictures now all use a image tag, <img> an they are by default left aligned. Centering all pictures is not as straightforward in Gitbook.**
- [x] remove empty pages (e.g. before Mobile App Security Testing, page 14) **[Sven] This would need to be checked with the PDF version, before we make the release, as the whole content is getting bigger/smaller for every release and might create empty pages in the document.**
- [x] fix formatting for titles in 5th level (e.g. ##### Running a Password Dictionary Attack), as they are showing up as normal text without formatting when using gitbook command to create a PDF: let's make sure we have only 4 headings and that we start a chapter with level 1 instead of 2;  **[Sven] A quick search in the markdown files resulted in 212 hits for titles with "######". This is a bigger issue throughout the guide. Nevertheless the PDF we are generating is showing 5th level as normal text, but 6th level is formatted in light grey and can be recognised as title/heading. Maybe it would be easier to find a way to format the 5h level properly, so that it's not showing up as normal text.**
- [x] Fix captions **[Sven] we actually never use captions for pictures. I would suggest for now we keep it like this.**
- [x] Fix here links

**Comment by sushi2k** [comment]
Couldn't find anything to remove the empty pages in the book. It seems that when the end of the chapter almost reached the end of the page, the subsequent page is empty. 
Also couldn't find anything that would show the page numbers in the TOC :-(

**Comment by sushi2k** [comment]
Will work on the titles in the 5th and 6th level, so that this is fixed and can be recognised as titles

**Comment by cpholguera** [comment]
all done. Last fix in #1973
