### ISSUE TITLE
iOS: update the network testing stack where necessary

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1160]
**Platform:**
iOS
**Description:**
In https://developer.apple.com/ios/whats-new/ we see the upgrade of the network framework . This means it is a good idea to update the network related portion if it comes to interception and pinning: https://developer.apple.com/documentation/network. Next, we have to doublecheck if urlsession had any changes due to that and make sure that is covered as well  https://developer.apple.com/documentation/foundation/urlsession

**Comment by commjoen** [comment]
(to be updated)

**Comment by commjoen** [comment]
https://developer.apple.com/documentation/foundation/urlsession

**Comment by commjoen** [comment]
https://developer.apple.com/documentation/network

**Comment by commjoen** [comment]
Check for both good- and bad practices that came to life with the changes here ;-)

**Comment by cpholguera** [comment]
Hi @cak, do you have any progress on this one? Can we help you with something?

**Comment by cak** [comment]
@cpholguera Sorry about the delay, I have a draft already written - I will work on it this week and open PR.

**Comment by cpholguera** [comment]
That sounds great, we're looking forward to it.  Thanks a lot!

**Comment by cak** [comment]
I apologize for the delay 😬, but I am circling back on my draft and will submit soon.

**Comment by cpholguera** [comment]
Already merged
