### ISSUE TITLE
Style guide for test cases

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-mstg#1166]
While reviewing the 0x06h PR, I was wondering what kind of style we want to use for the test cases. Active? Passive? Targeted at the reader? Together with the reader?

A few options (don't mind the content ;) ):

> If you open the AndroidManifest.xml file, you will see a main Application tag, with the following attributes: `atr1`, `atr2` and `atr3`. If you run the following command, you will see that `atr1` is actually dangerous.

> The AndroidManifest.xml file contains an Application tag, with the following attributes: `atr1`, `atr2` and `atr3`. The command below shows that `atr1` is dangerous:

> If we open the AndroidManifest.xml file, we will see a main Application tag, with the following attributes: `atr1`, `atr2` and `atr3`. If we run the following command, we will see that `atr1` is actually dangerous.

I'm personally a fan of the 2nd, as I don't like using "you" in these explanations. I took a look at the owasp testing guide, but they seem to use different styles. Sometimes they speak about "the tester should check", and sometimes "you should check".

**Comment by commjoen** [comment]
Vey good issue! I like the 2nd person (you) and active voice. This can make sentences short and readable. What do you think @sushi2k ?

**Comment by sushi2k** [comment]
Definitely also prefer the 2nd one. This is much more to the point. I tend to do it in various ways I think, but usually like the 1st one, targeting the reader. 
We should then also update the style guide, so that

**Comment by TheDauntless** [comment]
@commjoen Was talking about the 2nd person (=1st example) while @sushi2k you choose the 2nd example. So... discuss ? ;)

I'm also in favour of the 2nd example by the way.

**Comment by sushi2k** [comment]
I was just going through a few sections and it seems usually we were using 2nd person and it reads quite well (but maybe I am now just used to it and spoiled ;-) )and fit's it's purpose the best. As these are technical instructions that should be executed by the reader I think addressing him/her directly with "you" in an active voice is the best for that.

**Comment by commjoen** [comment]
Closing this given #1177
