### ISSUE TITLE
iOS Anti-Reversing Defenses - Anti-Debugging Checks

### ISSUE THREAD

**Issue by YoonChangKIM** [OWASP/owasp-mstg#1169]
**Platform:**
iOS
**Description:**
I have test with 'Anti-Debugging Cehcks' part.
But, I can't detect attaching frida on my app by using ptrace and sysctl...
It can't be do?
Please, teach me.

**Comment by commjoen** [comment]
Hi @YoonChangKIM ! Welcome to the MSTG! Sooo what is exactly your issue? If you seek guidance, have you tried connecting with us on Slack? because that makes understanding the issue you face a little more easier :).

**Comment by YoonChangKIM** [comment]
Hi, @commjoen .
How to prevent attaching frida on my app?
Using ptrace and sysctl doesn't work.

**Comment by commjoen** [comment]
Can you be a bit broader on which ios/android version you are trying to prevent this? Please note that the attacker can rename hte process name all hte time so eventually there is no closing detection scheme based on proces name, all you could do then is check if there are certain symbols available..

**Comment by commjoen** [comment]
Basically, as discussed on slack: you cannot prevent it, you can only detect it partially when you check the running processes... again : it depends on the method and os version...

**Comment by commjoen** [comment]
Does this answer your question? Or would it be a nice idea to dive into the details of Frida together in order to understand what is happening so you can make a more detailed write up on detection in return :)?

**Comment by YoonChangKIM** [comment]
I realized there are not absolutely skill for anti-debugging.
Thank you for your kind answer.
