### ISSUE TITLE
Android: Usage of Device Identifiers for Encryption Key?

### ISSUE THREAD

**Issue by shivsahni** [OWASP/owasp-mstg#1170]
**MSTG Suggests Usage of Device Identifiers For Encryption Key**
The "Testing Device Binding" section in chapter 0x05j suggests the following:

> Obfuscating the data stored on the device by using device identifiers as keys for encryption methods. This can help with binding to a device when the app does a lot of offline work or when access to APIs depends on access-tokens stored by the application.

I believe it is an insecure practice for encryption key generation. The device identifiers should never be directly used in the security context such as generation of encryption key since the values like IMEI, Android ID, Device ID can be easily obtained by an attacker having physical access or arbitrary code execution on the device.

If we are on the same page, I can make the PR?

**Comment by commjoen** [comment]
Hi @shivsahni ! Welcome to the MSTG! Basically the item you touch is not about the actual encryption, it is about binding certain assets to a device. That is why we do not say that we are encrypting data on the device, but we are obfuscating the data. We are not trying to secure the data, we are simply trying to bind the data to the device. 

If you still want to pull-request, we could indeed enrich this section by saying that you can use the keychain (with attributes such as `ksecattraccessiblewhenpasscodesetthisdeviceonly` at https://developer.apple.com/documentation/security/ksecattraccessiblewhenpasscodesetthisdeviceonly?language=objc or stronger --> which should be explained in the iOS section) or the AndroidKeystore (if KeyInfo shows inSideSecureHardware is true). However: if there is no keystore with hardware backing or a proper key, then this is still a viable option i guess :).

**Comment by shivsahni** [comment]
Hi @commjoen,

Thank you for the prompt response. I do understand that the section under discussion is not pertaining to the secure data storage and instead device binding. However, since we suggest MSTG as the bible of mobile application security to developers/security analysts, we should remove the space for ambiguities.

I think we should not suggest encrypting the data using device identifiers which can be easily obtained by other applications installed on the device. I agree, that it would help in the implementation of device binding which would add an additional layer of security, but at the same time, it would make the sensitive data stored in the local data storage vulnerable.

Even in the scenario wherein, the hardware-backed secure storage is not available, I believe this should not be a viable option, instead, the key should be dynamically generated using PBKDF2. Since there's no option for secure key storage it should not be stored anywhere and should derive every time whenever required.

**Comment by commjoen** [comment]
Given our discussion I do agree that we need to reword it, but this section is not about secure storage: it is about device binding ;-).

**Comment by sushi2k** [comment]
@shivsahni I do understand your point, but the goal of using encryption in this scenario is purely to bind the app to the device and not protect the confidentiality of the data. 
Instead of following up a discussion here, do you want to create a PR that makes this clear to avoid any ambiguities?

**Comment by commjoen** [comment]
Perhaps another nice idea to extend the binding next to the keystore would be to use aes gcm based on envelope encryption (with the private key in the keychain) and the authentication data using device identifiers...

**Comment by shivsahni** [comment]
@sushi2k, I'll do that.

@commjoen, I didn't get the idea you are trying to explain. Can you please elaborate on it?

**Comment by commjoen** [comment]
Basically, what we can do is use "proper encryption" and make it more device binding:
1. create a public private keypair stored in the AndroidKeystore or in the Keychain (https://developer.android.com/reference/android/security/KeyChain)
2. generate a random AES key
3. encrypt the AES key with that keypair created in 1
4. now use AES GCM to encrypt the data at hand, but do use the Android application identifiers allowed for your android version as authenticated data. So that moving this data from one device to antoher will not allow for easy decryption.

Obviously an attacker can still misuse this, but it gets a lot harder and he/she might move to the next app :)

**Comment by shivsahni** [comment]
Thanks for the description @commjoen, I have made the required changes, please go through it and suggest if we need to make any further improvements.
