### ISSUE TITLE
Level3 detects root on non-rooted devices

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-mstg#1171]
**Describe the bug**
Running the Level 3 app on a non rooted device shows the "Root detected" popup and then quits.

The check that fails is the CRC check on classes.dex, which probably wasn't updated with the last revision of the app. The CRC should be "275e7af8", but the application flags this as the wrong CRC:

`04-09 12:21:48.936   5731     5731           UnCrackable3  V  CRC[lib/arm64-v8a/libfoo.so] = 2268200259
04-09 12:21:48.936   5731     5731           UnCrackable3  V  CRC[lib/x86_64/libfoo.so] = 1483140570
04-09 12:21:48.937   5731     5731           UnCrackable3  V  CRC[lib/armeabi-v7a/libfoo.so] = 2867094050
04-09 12:21:48.937   5731     5731           UnCrackable3  V  CRC[lib/x86/libfoo.so] = 3242540510
04-09 12:21:48.937   5731     5731           UnCrackable3  V  CRC[classes.dex] = 660503288
04-09 12:21:48.937   5731     5731           UnCrackable3  V  classes.dex: crc = 660503288, supposed to be 1999877287`

Manual verification of the classes.dex shows that it should indeed be 660503288 (=275e7af8)

**crackme or other challenge**
Level 3

**Additional context**
Tested on a non-rooted Galaxy S8 with Android 9, and the warning is shown. I also recently RE'd level 3 for a project, and I was at that time stumped as to why it was still "detecting" Magisk. Didn't have time to look into it though and just bypassed the CRC check :(.

**Comment by commjoen** [comment]
Hi @TheDauntless ! Thank you for your bug submission, we will have a look soon, when we can find some time (given that both @sushi2k & me are at a terrible busy schedule at this point in time). If you want to, you can have a check as well @ https://github.com/commjoen/uncrackable_app and see if i did something wrong there...

**Comment by commjoen** [comment]
Fixed in #1146 :) together with @TheDauntless . Please, for now, only use the apk provided in the mstg folder.
