### ISSUE TITLE
0x6h: update MASVS references

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1184]
Given the various topics discussed in 0x6h we need to update the references to the masvs.

**Comment by cpholguera** [comment]
Should we add the following to the "#### OWASP MASVS" section of 0x06h?

- V6.2: "All inputs from external sources and the user are validated and if necessary sanitized. This includes data received via the UI, IPC mechanisms such as intents, custom URLs, and network sources."
- V6.4: "The app does not export sensitive functionality through IPC facilities, unless these mechanisms are properly protected."

**Comment by commjoen** [comment]
At least, let's doublecheck which others as well :)

**Comment by commjoen** [comment]
Let's add at least these :)

**Comment by cpholguera** [comment]
6.2+6.4, sure. Will do ;)

**Comment by commjoen** [comment]
Fill fix it for now :)

**Comment by commjoen** [comment]
Fixed it in #1199
