### ISSUE TITLE
0x06h - Aquiring the app binary to 0x06b

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1185]
**Describe the issue**
"###### Acquiring the App Binary" should be part of 0x06b as it describes a generic approach of how to get the app binary 
https://github.com/OWASP/owasp-mstg/pull/1158/files#diff-c9f2ccf4f6a5979b995232e65803555eR223

**Comment by commjoen** [comment]
Fixed in #1158
