### ISSUE TITLE
Update 0x08-Testing Tools

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1186]
**Describe the issue**
The links in 0x08-Testing Tools need to be changed so they can be read in the printed version of the MSTG. 

Instead of: 
- [Frida](https://www.frida.re) - The toolkit works using a client-server model and lets you inject into running processes on Android and iOS.

We should change it to:
- Frida: The toolkit works using a client-server model and lets you inject into running processes on Android and iOS - https://www.frida.re

**Comment by cpholguera** [comment]
@sushi2k I can take over this, is it OK for you?

**Comment by commjoen** [comment]
Fixed with #1197
