### ISSUE TITLE
How to prevent tampering signatures of APK-files using C 

### ISSUE THREAD

**Issue by DimaKoz** [OWASP/owasp-mstg#1189]
You can add to this book a description about tampering apk keys by nkstool and my solution how to prevent that.
You can see a more detailed description here:
 https://github.com/DimaKoz/stunning-signature/blob/master/README.md

**Comment by commjoen** [comment]
Hi @DimaKoz , nice writeup and nice suggestion. Would you like to give it a shot yourself?

**Comment by DimaKoz** [comment]
Yes, I'd like to. I'm going to prepare a contribution related to my research and create a new pull request.

**Comment by commjoen** [comment]
Awesome! Looking forward to it 👍

**Comment by commjoen** [comment]
Hi @DimaKoz : do you have any updates on this ?

**Comment by commjoen** [comment]
@sushi2k / @cpholguera the author of the issue no longer has time for this item to be processed. I think it would be good to invest in the anti-reverse engineering chapters in a next OSS (together with updates on ios 12/13 android 9/10). Moving it to milestone 1.3

**Comment by cpholguera** [comment]
Closed after long inactivity
