### ISSUE TITLE
Measuring text is improper in linux environment

### ISSUE THREAD

**Issue by MadhanKumarasamy** [OWASP/owasp-mstg#1194]
**Describe the bug**
Measuring text is improper in Linux environment.

**To Reproduce**
var paint = new SKPaint();
var bounds = new SKRect();
float width = paint.MeasureText("Location", ref bounds);

**Expected behavior**
we want same width for the text in both windows and Linux environment

**Comment by commjoen** [comment]
Hi @MadhanKumarasamy ! Welcome to the MSTG. I don't think this issue is part of the Mobile Security Testing Guide as SKPaint (Skia paint library?) is not really part of the MSTG. Shall we close this issue?
