### ISSUE TITLE
Create code of conduct / contribution guidelines

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1204]
- [x] have a code of conduct
- [x] have a how to contribute
- [x] have clean markdown
- [x] have markdown automation support
- [x] have statistics on number of dead links and numer of issues with markdown reported back to the PR by travis: https://damien.pobel.fr/post/github-api-from-travisci/ 

Given the success of our project, we need to start creating a code of conduct / contribution guidelines next to the style-guide in which we should at least define that:

- We take facts over status (or something like that: e.g. explain that no matter if you have little to no expereince, your contribution is valued as long as you base it on proper research)
- We review before merge 
- Quality of written content is just as important as the content
- We do NOT support writeups with commercial tools, other than referring to a security tool in the tools section. But write-ups to detect an issue SHOULD first be based on Free or Open Source tooling.
- We do not take any different approach to anyone given background/gender/etc.
- We show respect to contributions and/or issues :).

**Comment by cpholguera** [comment]
We could also highlight there that the code snippets must be well tested and maybe give some hints on the target apps people is allowed to use, e.g. open source apps, give preference to the hacking playground app or other OWASP apps like iGoat

**Comment by sushi2k** [comment]
Very good points and full ACK! Let's finish this before the summit

**Comment by commjoen** [comment]
Will start a pR soon :)

**Comment by commjoen** [comment]
Maybe nice, similar to https://github.com/OWASP/CheatSheetSeries/blob/master/CONTRIBUTING.md to have a definition of how we want to see the markdown configured? (thanks @jmanico  for the good example! We are happy to follow a proper path :D )

**Comment by commjoen** [comment]
Clean markdown only needs a decision on usage of ** as header and how to use links
