### ISSUE TITLE
Remove reference to yahoo weather service in 0x04h - Code quality

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-mstg#1207]
The 0x04h page currently discusses the Yahoo weather app as an example of SQL injection.

As the original blogpost is no longer available online, and since we don't want to showcase vulnerabilities on commercial applications, this should be rewritten.

**Comment by commjoen** [comment]
What if we instead use https://blog.ostorlab.co/android-sql-contentProvider-sql-injections.html ? then we can still use the example.

**Comment by sushi2k** [comment]
Let's remove it and link to it. Thanks for the URL!
