### ISSUE TITLE
OWASP slack link has expired

### ISSUE THREAD

**Issue by mkuivenhoven** [OWASP/owasp-mstg#1217]
The link "https://join.slack.com/t/owasp/shared_invite/enQtNDI5MzgxMDQ2MTAwLTEyNzIzYWQ2NDZiMGIwNmJhYzYxZDJiNTM0ZmZiZmJlY2EwZmMwYjAyNmJjNzQxNzMyMWY4OTk3ZTQ0MzFhMDY" has expired.

**Comment by sushi2k** [comment]
Is this one working for you: https://owasp.slack.com/join/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ

**Comment by commjoen** [comment]
I guess the wiki needs to be updated;-)

**Comment by sushi2k** [comment]
The Link that I shared is the link from our README.md :-) Sorry, should have been more specific. 
Not sure where the other link is from. 

@mkuivenhoven Can you please let me know if the registration was successful? Then I will close this issue. You can find link also here: https://github.com/OWASP/owasp-mstg/#contributions-feature-requests-and-feedback
Thanks

**Comment by commjoen** [comment]
Updated the wiki link at FAQ for now

**Comment by sushi2k** [comment]
Closing issue as Slack link is now updated everywhere. @mkuivenhoven  please reopen if you still have problems.
