### ISSUE TITLE
0x4 - Duplicate section "References"

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#122]
The same referenced documents can be found 4 times in the document (see below). It should appear only once, in the "References" section at the bottom of the chapter (which, in turn, shall be separate from other sections).

References
    [1] Meyer's Recipe for Tomato Soup - http://www.finecooking.com/recipes/meyers-classic-tomato-soup.aspx
    [2] Another Informational Article - http://www.securityfans.com/informational_article.html

**Comment by b-mueller** [comment]
In which chapter(s) is this the case?

**Comment by romualdszkudlarek** [comment]
Sorry, it goes better with chapter reference ;-) 0x5d

**Comment by b-mueller** [comment]
For the chapters containing test cases, we have a reference section for every single test case. Makes sense IMHO?

**Comment by romualdszkudlarek** [comment]
Makes sense

**Comment by romualdszkudlarek** [comment]
Sorry, it was about 0x4. There are 4 "References" sections, 3 inside the paragraph and one at the end. I'll do the job directly in the code and will create a pull request. Feel free to commit it or not whether you think it's relevant or not :-)
