### ISSUE TITLE
OSS19 0x5b - Enhance Testing on a Real Device

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1226]
- Elaborate a bit more on "why a physical device is the preferred option", e.g. when the app communicates with companion devices, e.g. fitness tracking apps communicating with an armband or automotive apps communicating with the car per bluetooth.

- Include a recommendation for physical devices. e.g. Nexus / Pixel devices and why we recommend them.

Search for the "ToDo" in 0x05b

**Comment by cpholguera** [comment]
Hi @TheDauntless , @A-AFTAHI  would like to work on this ticket but it's assigned to you. Have you started working on it already?

**Comment by commjoen** [comment]
Fixed in #1344
