### ISSUE TITLE
OSS19 0x5b - Recommended Tools

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1227]
Write an intro for the section "Recommended Tools" for Android

Additionally consider this: in this section we will only summarize the few basic tools that we are using throughout the guide. **Be sure to reference to installation manuals and DON'T copy paste from the tools documentation**. Only put in installation instructions if they are not straightforward or the documentation lacks information. Otherwise we will run out of sync and would need to maintain this also.

**Comment by commjoen** [comment]
Fixed in #1337
