### ISSUE TITLE
OSS19 0x5b - Frida on Android

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1229]
We've moved installation and basics from 0x05c to the "Recommended Tools/Frida" section in 0x05b. Still we have to review these instructions and refer to the official instructions to avoid maintaining them, which does not make sense for us.

Also, we should make clear in this section 
- what's the point on using Frida (instead of another tool, e.g. Xposed, and in which situations)
- what are the benefits of using Frida on Android
- what are the basic commands / features. 

(keep in mind that we will include similar information for iOS in 0x06b, please ensure that both sections are in sync)

To ensure consistency, please search all chapters to avoid having duplicate information about installation or introduction to Frida, etc.

Also: "Dynamic Instrumentation with Frida" in 0x5c needs a rework.

**Comment by commjoen** [comment]
Fixed in #1350
