### ISSUE TITLE
0x4 - About Burp Suite

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#123]
The text states that "Burp Suite (Professional)" should be used for traffic interception. In my experience, the free version can easily do the job, no need to use the professional (paid) version. Moreover, as much as possible OWASP should not do any commercial promotion.

Proposal: limit to the free version and remove "(Professional") from the sentence "This can be achieved by using an interception proxy like Burp Suite (Professional) or ..."

**Comment by b-mueller** [comment]
Fixed.
