### ISSUE TITLE
OSS19 0x5b - Objection on Android

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1230]
Create the "Recommended Tools/Objection" section in 0x05b. 

- Give an introduction.
- Refer to the official installation instructions to avoid maintaining them.

Also, we should make clear in this section

- what's the point on using objection (instead of another tool and in which situations)
- what are the benefits of using it on Android
- what are the basic commands / features.

Keep in mind that we will include similar information for iOS in 0x06b, please ensure that both sections are in sync.

To ensure consistency, please search all chapters to avoid having duplicate information about installation or introduction, etc.

**Comment by sushi2k** [comment]
Include also this issue: https://github.com/OWASP/owasp-mstg/issues/806

**Comment by commjoen** [comment]
Can be closed thanks to #1289
