### ISSUE TITLE
OSS19 0x5b - angr on Android

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1235]
Review and enhance the "Recommended Tools/Angr" section in 0x05b.

- Review the introduction. Give some more basics and benefits.
- Refer to the official installation instructions to avoid maintaining them.

Also, we should make clear in this section

- what's the point on using angr (instead of another tool, e.g. radare2 + ESIL, and in which situations)
- what are the benefits of using it on Android
- what are the basic commands / features.

Should we consider angr for iOS in 0x06b, if yes, please ensure that both sections are in sync.

To ensure consistency, please search all chapters to avoid having duplicate information about installation or introduction, etc.

Todo:
- [x] Review the introduction. Give some more basics and benefits.
- [x] Refer to the official installation instructions to avoid maintaining them.
- [x] what's the point on using ang
- [x] what are the benefits of using it on Android
- [x] what are the basic commands / features
- [x] investigate on iOS

**Comment by commjoen** [comment]
Hi @rylyade1 :), do you have any status update on this :) ?

**Comment by commjoen** [comment]
Update: had a chat on slack and decided to pick up the issue together :)

**Comment by commjoen** [comment]
I have not seen any easy steps to use angr on an ios binary, as most examples run on a binary dedicated for the cpu architecture it is compiled for... (e.g x86 binaries on an intel based machine)

**Comment by commjoen** [comment]
Fixed in #1351
