### ISSUE TITLE
OSS19 0x5b - Accessing the Device Shell

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1236]
Enhance the "Accessing the Device Shell" section in 0x05b.

Add introduction and create / enhance / review the following sub-sections:

- On-device Shell App: describe it for the sake of completeness, but should also mention that usually using a on-device shell is very tedious compared to a remote shell. But might be good for debugging in case of for example network issues. e.g. app: termux. 
- Remote Shell: consider adding SSH, e.g. via termux or an "SSH for Android" app, consider the best solution (e.g. investigate and test what we can achieve only using termux and if it covers several things we can go and keep recommending it for all those tasks.

**Comment by commjoen** [comment]
Fixed in #1280 and #1279
