### ISSUE TITLE
OSS19 0x5b - Information Gathering

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1239]
Create the "Information Gathering" section in 0x05b.

- Give an introduction.
- Read all messages in the discussion starting with https://github.com/OWASP/owasp-mstg/pull/1222#discussion_r287551713
- After considering the mentioned discussion, decide if we want to split this issue in sub issues.

Complete the following sections:

- Installed Apps: e.g. `adb shell pm list packages`
```shell
$ adb shell pm list packages
package:com.android.sdm.plugins.connmo
package:com.google.android.googlequicksearchbox
package:com.android.providers.calendar
package:com.android.providers.media
package:com.google.android.onetimeinitializer
package:com.google.android.ext.shared
package:com.android.wallpapercropper
package:sg.vp.owasp_mobile.omtg_android
```

- App Basic Information: include things that we can obtain using tools like aapt, dumpsys.
  - Sandbox: how to get to `adb shell ls /data/data/sg.vp.owasp_mobile.omtg_android`? what's in there?
  - Permissions: from androidmanifest or aapt dump, e.g. `aapt dump permissions omtg.apk`. Consider differences, do some tests using several apps and evaluate results. 
  - Native Libs: Consider getting them from the APK or from the device; Consider also getting them using Frida / objection / gdb when running. Talk about the differences and give an evaluation. e.g. on runtime you may have to wait / trigger some functionality before seen the library being loaded.

Some help for Native Libs:

```
bullhead:/ # ls /data/data/sg.vp.owasp_mobile.omtg_android/lib
libdatabase_sqlcipher.so libnative.so libsqlcipher_android.so libstlport_shared.so
```

Using objection it is also straightforward as you already land in the sandbox and can directly use `cd` and `ls` commands to look around:

```
$ objection -g sg.vp.owasp_mobile.omtg_android explore

...g.vp.owasp_mobile.omtg_android on (google: 8.1.0) [usb] # ls lib                                                                                                           
Type    Last Modified            Read    Write    Hidden    Size       Name
------  -----------------------  ------  -------  --------  ---------  ------------------------
File    2018-06-06 08:16:34 GMT  True    False    False     13.4 KiB   libnative.so
File    2018-06-06 08:16:34 GMT  True    False    False     181.9 KiB  libdatabase_sqlcipher.so
File    2018-06-06 08:16:34 GMT  True    False    False     357.3 KiB  libstlport_shared.so
File    2018-06-06 08:16:34 GMT  True    False    False     2.2 MiB    libsqlcipher_android.so
```

**Consider adding more sections for App Basic Information. Always keeping in mind that they should be reflected in the iOS chapter, unless not applicable**

- Accessing App Data: what to expect, where, sandbox structure `/data/data`
- Monitoring System Logs: `logcat` or android studio https://developer.android.com/studio/command-line/logcat.html

**Comment by commjoen** [comment]
Closed by #1299
