### ISSUE TITLE
OSS19 0x5b - Dynamic Analysis on Android

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1240]
Create the "Dynamic Analysis" section in 0x05b.

- Give an introduction.
- Complete the next sections:
  - Using Non-Rooted Devices
  - Method Tracing
- Basic Network Monitoring/Sniffing: maybe consider moving "Basic Network Monitoring/Sniffing" from the next section to here.

Are we missing some other basics? Evaluate and add. Consider creating new issues.

**Comment by ThunderSon** [comment]
Hello, I'd like to handle this issue 😄

**Comment by commjoen** [comment]
Hi @ThunderSon !
Great to have you on board! You don't seem to be in the collaborator list yet, so I have send you an invite. Can you please accept it? Then i can assign the issue to you.

**Comment by ThunderSon** [comment]
The basic networking section contains plenty of subsections, and I'd debate it being in in the Dynamic Analysis section. What do you think @commjoen ? If we were to add that section, why not the Intercepting proxy too? That could as well be part of the dynamic analysis.

**Comment by commjoen** [comment]
Current status: being discussed on Slack ;-).

**Comment by commjoen** [comment]
Closed based on #1326. Thanks @ThunderSon !
