### ISSUE TITLE
OSS19 0x6b - Update Tools list 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1243]
**Describe the issue**
As part of changes to the basic security testing chapter for iOS, the tools list nee to be updated in 0x06b. 

1. First identify the tools we are using in the iOS guide, including URLs where the tool can be downloaded
2. Then extend the list in "Recommended Tools" with the identified tools and give guidance on how to install them. Refer to the official installation instructions to avoid maintaining them. Only describe the installation process in the chapter if it is not straightforward and additional information is needed that is not part of the tool documentation.
3. Also explain the following for each tool:
- What's the point on using this tool (instead of another tool and in which situations)
- what are the basic commands / features.

Keep in mind that we will include similar information for iOS in 0x05b, please ensure that both sections are in sync.

To ensure consistency, please search all chapters to avoid having duplicate information about installation or introduction, etc.

**Comment by commjoen** [comment]
Closed in  #1267
