### ISSUE TITLE
OSS19 0x6b - Information Gathering on iOS  with objection 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1247]
**Describe the issue**
As part of changes to the basic security testing chapter for iOS, describe how to get basic information that might be useful for an attacker out of the app with objection, e.g. directories used and UUID for installation of the app and other useful information. 

iOS jailbroken test devices are available during the summit.

**Comment by sushi2k** [comment]
https://github.com/OWASP/owasp-mstg/pull/1267

**Comment by commjoen** [comment]
Can be closed thanks to #1267
