### ISSUE TITLE
OSS19 0x6b - Describe various ways of sideloading iOS apps 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1248]
**Describe the issue**
As part of changes to the basic security testing chapter for iOS, describe the various ways of sideloading the app:
- ideviceinstaller as part of libimobiledevice
- ios-deploy 
- Xcode etc.

**Comment by sushi2k** [comment]
https://github.com/OWASP/owasp-mstg/pull/1277

**Comment by commjoen** [comment]
Fixed in #1277
