### ISSUE TITLE
OSS19 0x6b - Information Gathering on iOS with Passionfruit

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1249]
**Describe the issue**
As part of changes to the basic security testing chapter for iOS, describe how to get basic information that might be useful for an attacker/pentester out of the app with passionfruit, e.g. directories used and UUID of the app and other useful information.

iOS jailbroken test devices are available during the summit.

**Comment by commjoen** [comment]
Can be closed thanks to #1314
