### ISSUE TITLE
OSS19 0x6b - Dumping KeyChain Data with Needle/Objection/Passionfruit/Keychaindumper

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1250]
**Describe the issue**
As part of changes to the basic security testing chapter for iOS, describe how to use Passionfruit and objection to dump Keychain data from a non jailbroken device and explain it's limitations (e.g. the tester is still in the app sandbox and can only access items in the keychain that are tied to the entitlement of the app). 

iOS jailbroken test devices are available during the summit.

**Comment by commjoen** [comment]
for now:
- do it with Needle on iOS12 and with the ios Keychaindumper
- do it with objection/passionfruit on a lower version of ios

**Comment by commjoen** [comment]
#1307
