### ISSUE TITLE
0x05b add drozer highlights

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1270]
Now we have a nice structure on the Basic Testing -> Recommended Tools. However we can add more value to the drozer section by talking about:
- basic architecture
- modules
- little spoiler on how we use it in the guide
- review Sieve
- talk about the highlights: why do we want to use drozer, there's some things you can actually do via adb, or some grepping, without having to install drozer only for that. But for other things it is really helpful.

**Comment by cldrn** [comment]
The Sieve app has problems running on newer Android versions. It partially works. Should we use something else?

**Comment by commjoen** [comment]
Fixed in #1296
