### ISSUE TITLE
OSS19 0x6b - Setting up a Network Testing Environment

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-mstg#1271]
This section is much less populated than the 0x5b counterpart.

On Android:
* Basic Network Monitoring/Sniffing
    * Burp plugins to Process Non-HTTP Traffic
    * Firebase/Google Cloud Messaging (FCM/GCM)
        * Preparation of Test Setup
        * HTTP
        * XMPP
        * Intercepting the Requests
        * End-to-End Encryption for Push Notifications
* Setting Up an Interception Proxy
    * Interception Proxy for a Virtual Device
        * Setting Up a Web Proxy on an Android Virtual Device (AVD)
        * Installing a CA Certificate on the Virtual Device
    * Interception Proxy for a Physical Device
        * Bypassing the Network Security Configuration
            * Adding the User Certificates to the Network Security Configuration
            * Adding the Proxy's certificate among system trusted CAs using Magisk
            * Manually adding the Proxy's certificate among system trusted CAs
* Potential Obstacles
    * Client Isolation in Wireless Networks
    * Non-Proxy Aware Apps
        * iptables
        * bettercap
    * Proxy Detection
    * Certificate Pinning
        * Bypass Custom Certificate Pinning Statically
        * Bypass Custom Certificate Pinning Dynamically
             * References

Currently on iOS:

* Setting up a Network Testing Environment
    * Network Monitoring/Sniffing
    * Setting up an Interception Proxy

**Comment by commjoen** [comment]
PArtially fixed in #1271, still needs to remain open.

**Comment by commjoen** [comment]
Fixed in #1286
