### ISSUE TITLE
OSS19 0x5b - Enhance Testing on the Emulator

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1279]
When working on issue #1236 we moved some content to "Testing on a Real Device" and "Testing on the Emulator". However, this section might not be complete and therefore a review is required.

**Please only work on this ticket after we close #1236** 

Things to consider:

- which emulators exist? (AVD, Genymotion, ...), which one is better for what, etc.
- what to install in the emulator (Frida, Xposed, etc.): maybe use recommended setup script from Jeroen: install busybox, Xposed, maybe also add Frida.
- which tools include an emulator and test the apps autom. inside. (e.g. MobSF, Nathan?)

Note: Nathan is a 5.1.1 SDK 22 AOSP Android emulator and it's not updated since 2016. We might want to drop it.

**Comment by cpholguera** [comment]
@TheDauntless please consider this and the changes from #1236 (only one paragraph actually) when working on #1226

**Comment by commjoen** [comment]
Can we close this one @cpholguera ?

**Comment by cpholguera** [comment]
This is still open. We can remove the assignment in case someone wants to take care of it. I'm working on other issues right now.

**Comment by commjoen** [comment]
Fixed in #1315
