### ISSUE TITLE
Clear wording for the "computer" of the tester 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1283]
**Describe the issue**
We are using sometimes different phrases to describe the "computer" of the tester:
- laptop
- workstation
- machine 
- etc.

We should decide which one we should use and keep it consistent in the guide and add it to the style guide. I would prefer workstation :-)

**Comment by ninedter** [comment]
I give workstation a vote + 1

**Comment by imskr** [comment]
I am beginner. I want to take this issue. How can i get started for this ?

**Comment by sushi2k** [comment]
Hi @imskr. Thanks for reaching out. Can you please ping me in Slack (@sushi2k)? Then we can take it from there.  
This is how you can join our Slack:
https://github.com/OWASP/owasp-mstg/#contributions-feature-requests-and-feedback

**Comment by imskr** [comment]
Yeah sure @sushi2k

**Comment by sushi2k** [comment]
As workstation usually refers to a heavy desktops, the term "computer" might be better as it's more generic (can be a laptop, workstation etc.). Any objections @TheDauntless @cpholguera?

Computer is for example used here already and fits better than workstation: https://github.com/OWASP/owasp-mstg/blob/dcda81fa5974146cb6efc3f61be4b12d62d8bcc6/Document/0x06b-Basic-Security-Testing.md#jailbreak-types

**Comment by cpholguera** [comment]
I think that's a good idea. We're using "host computer" pretty often on
that chapter and it's working perfectly so it'd be great to keep using it
consistently.

**Comment by commjoen** [comment]
Hi there, what is the current status of this issue?
