### ISSUE TITLE
OSS19 -0x6b - Accessing the Device Shell 

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1284]
Create the "Accessing the Device Shell" section in 0x06b.

Add introduction and create the following sub-sections:

- On-device Shell App: describe it for the sake of completeness, but should also mention that usually using a on-device shell is very tedious compared to a remote shell. But might be good for debugging in case of for example network issues.
- Remote Shell: SSH

**Comment by commjoen** [comment]
Can be closed with  #1286
