### ISSUE TITLE
Don't use passwords that have been disclosed in previous breaches 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1321]
**Platform:**
A new sub-section should be added for General Testing Authentication Chapter, https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04e-Testing-Authentication-and-Session-Management.md#best-practices-for-passwords

**Description:**
We should add a check to the password best practices to use the API from haveibeenpwned to verify if the password has already been breached. 
https://haveibeenpwned.com/API/v2#PwnedPasswords

**Comment by commjoen** [comment]
Covered in #1418
