### ISSUE TITLE
Verify requirements in Excel sheet with MASVS 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1324]
**Describe the issue**
Check the wording of each requirement in MASVS with column C in the excel checklist and verify if all requirements are aligned.

**Comment by commjoen** [comment]
#1327 covered the french and english version
@cpholguera can you pick up this issue to update the Spanish one please :) ?

**Comment by cpholguera** [comment]
Sure ;)

**Comment by commjoen** [comment]
After that we can close this issue :).
