### ISSUE TITLE
0x05a Broadcast Receiver: Incorrect description

### ISSUE THREAD

**Issue by zehuanli** [OWASP/owasp-mstg#1340]
**Describe the issue**

As [0x05a-Platform-Overview.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05a-Platform-Overview.md) states, Broadcast Receiver must be declared in `AndroidManifest.xml` to work:

>Broadcast Receivers must be declared in the app's manifest file... If Broadcast Receivers aren't declared, the app won't listen to broadcasted messages.

However, according to [Android documentation](https://developer.android.com/guide/topics/manifest/receiver-element), Broadcast Receivers can also be registered dynamically:

>There are two ways to make a broadcast receiver known to the system: One is declare it in the manifest file with this element. The other is to create the receiver dynamically in code and register it with the Context.registerReceiver() method.

I'm not sure if this is a new feature in recent Android versions, but apparently the former description is incorrect now.

Additionally, according to [Android guide](https://developer.android.com/guide/components/broadcasts), most implicit broadcasts will not work for the receivers declared in `AndroidManifest.xml` in Android version 8.0 or higher:

>If your app targets Android 8.0 or higher, you cannot use the manifest to declare a receiver for most implicit broadcasts (broadcasts that don't target your app specifically). You can still use a context-registered receiver when the user is actively using your app.

It would be nice if this could also be added to description.

Thanks!

**Comment by commjoen** [comment]
Hi @zehuanli ! you have a point there! Let's put this in the 1.2 milestone.
I was wondering though: can you help us out with a PR on this matter :)? That would be awesome! Otherwise I will pick it up later.

**Comment by commjoen** [comment]
It seems we have similar issues with the browsable intents :). Let's have a look at that as well :)

**Comment by zehuanli** [comment]
Hi @commjoen , thanks for the update! I'm working on 0x05a now, but haven't noticed the issue with the browsable intents. I can also work on it if you could point me to that one, otherwise I'll file a PR for the 0x05a itself.

**Comment by commjoen** [comment]
Maybe I overlooked something there, or it is only in my head. For now continue with what you are working on! Can you file an early PR (WIP) when you have something to push please? Because large rewrites often (E.g. more than 250 words) often take way more time to review and pingpong...

**Comment by commjoen** [comment]
Funny: it does seem we had an issue on this registered, best is to linke it here i guess: https://github.com/OWASP/owasp-mstg/issues/941 . Thank you for picking it up! Looking forward to your results :).

**Comment by zehuanli** [comment]
I'll file it as soon as I push the changes.

Yeah I didn't see that issue but it was related to this one!

**Comment by commjoen** [comment]
Fixed in #1355
