### ISSUE TITLE
Slack Channel Link Update

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/owasp-mstg#1353]
It seems that a recent update to Slack links changed the routes. The current link takes the user to the default channel, and not to the project's [channel](https://app.slack.com/client/T04T40NHX/C1M6ZVC6S)

**Comment by commjoen** [comment]
Hi @ThunderSon ! Thank you for your check! Just to make sure: which links did you check?

**Comment by commjoen** [comment]
Thank you for fixing it in #1354 !
