### ISSUE TITLE
5c - Review Symbolic Execution Section

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1357]
commjoen: "this might need some references to arm instructions before you continue as this example does not speak for itself as it is described here."

See: https://github.com/OWASP/owasp-mstg/pull/1332#discussion_r303216106

The goal is to re-read the section and make sure that both the section is understandable and its example "speaks for itself", include all necessary enhancements and references.

**Comment by cpholguera** [comment]
Hi @su-vikas , maybe you could help us out here. This is related to your current issue #1374 and might be a good place to add a nice miasm example in addition to reviewing and enhancing the current one. What do you think?

**Comment by su-vikas** [comment]
Sure. I will take it up once I am done with iOS one.

**Comment by cpholguera** [comment]
Nice, thank you very much! :)

**Comment by su-vikas** [comment]
@cpholguera I have started looking into this one, will send PR with changes to existing content first. 
You can make it hacktoberfest, should be done in october :).

**Comment by cpholguera** [comment]
That's very nice. It's now tagged, thanks!

**Comment by commjoen** [comment]
Fixed in #1524, thanks @su-vikas !
