### ISSUE TITLE
5c - Create Basic Information Gathering (Static Analysis)

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1358]
Create in section Static Analysis -> Basic Information Gathering

after "Manual (Reversed) Code Review"

```
#### Basic Information Gathering
##### Retrieving Strings
##### Call Diagrams and Cross References
##### API Usage
##### Checking Secure Connections
```

Consider this:

- In "##### Retrieving Strings" and "##### Call Diagrams and Cross References" consider using radare2.
- In "##### API Usage" talk briefly about Bluetooth, NFC, Crypto ... You can reference 0x05d-j
- In "##### Check Secure Connections" You can talk about HTTPS, TLS, cert. pinning, Network Configuration. Be sure to check that no information is duplicated, be brief and reference 0x05g or other chapters.

**Comment by su-vikas** [comment]
Will take this one :)

**Comment by su-vikas** [comment]
I will do this with Ghidra, is that fine, or has to be done with R2?

**Comment by cpholguera** [comment]
Hi @su-vikas , thanks for taking over this one as well. It's ok if you use Ghidra, as long as you keep it "tool" neutral in the explanation. The focus should be in the techniques, way to do it and why to do what, rather than on explaining how to use the tool.
