### ISSUE TITLE
5c - Create Basic Information Gathering (Dynamic Analysis)

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1359]
Create Dynamic Analysis -> Basic Information Gathering

after "Dynamic Analysis on Non-Rooted Devices"

```
#### Basic Information Gathering
##### Opened Files
##### Opened Connections
##### Loaded Native Libraries
##### Sandbox Inspection
```

Thanks to Dynamic Analysis we are able to do some additional Information Gathering steps that we cannot do when performing Static Analysis. This section is meant to describe those steps.

Consider talking about Files and Permissions in "Sandbox Inspection".

**Comment by su-vikas** [comment]
Can we please close this one :)

**Comment by commjoen** [comment]
@cpholguera is this one sufficiently covered now :-)?
