### ISSUE TITLE
5c - Create Native Code Tracing

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1361]
Create Dynamic Analysis -> Tracing -> Native Code Tracing

after "Method Tracing"

```
##### Native Code Tracing
```

This section will talk about how to trace native code, for example using frida-trace to trace the methods of a native library and how is this different from Java Code method tracing.

The following snippet taken (and removed) from chapter 5b should help starting here:

```
To trace specific (low-level) library calls, you can use the `frida-trace` command line tool:

$ frida-trace -i "open" -U com.android.chrome

This generates a little JavaScript in `__handlers__/libc.so/open.js`, which Frida injects into the process. The script traces all calls to the `open` function in `libc.so`. You can modify the generated script according to your needs with Frida [JavaScript API](https://www.frida.re/docs/javascript-api/).
```

**Comment by su-vikas** [comment]
Taking this one.

**Comment by cpholguera** [comment]
Thanks @su-vikas ;)

**Comment by cpholguera** [comment]
Here some major points that I hope might get you started with this more easily:
 
- using -i, -x and their uppercase versions. When one wants to get some specific function or when one wants to match a group of functions using a glob *
- using it quickly (without considering __handlers__)
- going deeper by obtaining the signature of the target function, opening the specific auto-generated stub in __handlers__ and inputting the right parameter types/names.
- going even further and performing some operations inside the code of the stubs
- tracing all JNI functions ` -i "Java_*"`
- explain what the colors mean in the traces and that one may modify the stubs on-the-fly

Am I missing something? 🤔

Please keep it really short and just refer to the official docs here which have all the options explained in more detail: 

https://www.frida.re/docs/frida-trace/

Please let me know if you have some questions or some suggestions on slack ;)
