### ISSUE TITLE
5c - Create Library Injection

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1362]
Create Tampering and RI -> Patching ... -> Library Injection

before end of "Patching ...", before "Dynamic instrumentation"

```
##### Library Injection
```

This section will talk about how to perform Library Injection on Android. This is used for example to inject Frida gadget but can be used on other cases and using several techniques: e.g. modifying the source code, patching a binary or its libraries, using a dynamic linker feature like LD_PRELOAD.

**Comment by su-vikas** [comment]
I will take this one.

**Comment by commjoen** [comment]
Have fun!

**Comment by commjoen** [comment]
Possible extension, using https://twitter.com/iGio90/status/1216326128601837570 ?

**Comment by cpholguera** [comment]
Nice suggestion! As this section is rather general and the tool is Frida specific, what if we mention it as "yet another way to inject Frida agent" in the Android Frida section? (Including of course all requirements/constraints such as that the phone must be rooted)

If we add it, it would also be nice to write a concrete usage scenario where this might come handy. If I get the tool properly it's for including it in one app so that one can inject Frida into another apps (on a rooted phone) and use the injector app as client instead of the tester computer, right?

What do you think?
