### ISSUE TITLE
5c - Create Tooling (Dynamic Instrumentation)

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1363]
Create Tampering and RI -> DI -> Tooling

after "Dynamic Instrumentation"

```
##### Tooling
```

This section will present recommended tools to use for Android dynamic analysis, e.g. Xposed and Frida.

Consider the tools in 5b! Avoid repeating content. Consider if we should move some content here (e.g. Xposed), or for Frida talk about some basics in 5b (actually only what it's being used there) and the more advanced in 5c (e.g. the hooking capabilities).

**Comment by su-vikas** [comment]
will take this one.
