### ISSUE TITLE
5c - Create Process Exploration

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1365]
Create Tampering and RI -> Dynamic Instrumentation -> Process Exploration

after "Method Hooking"

```
##### Process Exploration
###### Memory Maps and Inspection
###### In-Memory Search
###### Memory Dump
###### Runtime Reverse Engineering
```

This section is intended to show a view of the app from within its memory. One of the recommended tools to address here is r2frida.

Check chapter 6c to keep it consistent. Once this ticket is ready: #1377

**Comment by commjoen** [comment]
Fixed in https://github.com/OWASP/owasp-mstg/pull/1424
