### ISSUE TITLE
6c - Create Subsections in Disassembling and Decompiling

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1367]
add subsections to #### Disassembling and Decompiling

```
##### Disassembling Objective-C and Swift Code
##### Disassembling Native Code
###### radare2
###### Ghidra
```

> We won't use IDA for the examples as it is commercial.

Check chapter 5c to keep it consistent.

Think of maybe splitting this if it's too much for one ticket.

**Comment by commjoen** [comment]
@su-vikas , can you accept the invite at https://github.com/OWASP/owasp-mstg/invitations so we can assign this ticket to you ?

**Comment by commjoen** [comment]
@cpholguera can this now be closed?

**Comment by cpholguera** [comment]
If I understood the last PR properly that was just the introduction in 5b. This is the actual content in 5c. Here it should get concrete and specific on what to consider when reversing iOS binaries. The other intro section was just about which tools you can use for it. 

What we could do is to choose one of the tools here and write the section with it.

So we could remove the mentioned subsections per tool here in 5c.

**Comment by su-vikas** [comment]
@cpholguera  can you please elaborate a bit more. I feel what you are suggesting will be part of #1368.

**Comment by su-vikas** [comment]
@commjoen @cpholguera can you please review this bug and let me know what is missing.
