### ISSUE TITLE
6c - Create Manual (Reversed) Code Review section and subsections

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1368]
add "#### Manual (Reversed) Code Review" and subsections after "### Static Analysis"

```
#### Manual (Reversed) Code Review
##### Reviewing Disassembled Objective-C and Swift Code
##### Reviewing Disassembled Native Code
###### radare2
###### Ghidra
###### IDA Pro
```

Check chapter 5c to keep it consistent.

Consider discarding IDA (?)

**Comment by cpholguera** [comment]
Hi @su-vikas , that's very nice. We can assign it to you then :)

I'd say, you can start with Ghidra and we'll see. We'll probably be discarding IDA Pro but we still have to discuss about it. Nevertheless, at least you're not blocked if you want to start with Ghidra. Please let us know if you have any questions here or on the slack channel. Thank you!

**Comment by cpholguera** [comment]
The ticket is already assigned to you in the project and set to "in progress". Please let us know if you have any questions :)

**Comment by su-vikas** [comment]
While writing this chapter I felt that there may not be a need to include each tool - ghidra, ida, R2. The technique and approach discussed is agnostic to the tool used. And we already provide an introduction on all these tools. Do you guys agree?

**Comment by cpholguera** [comment]
That's totally right for me, thanks 👍  I'll review your PR ;)

**Comment by commjoen** [comment]
Is this one now completed? (@cpholguera /@su-vikas)

**Comment by cpholguera** [comment]
Yes. Thanks @su-vikas again!

**Comment by commjoen** [comment]
Awesome! Thanks @su-vikas !
