### ISSUE TITLE
6c - Review and Restructure Basic Information Gathering (Static Analysis)

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1369]
restructure "#### Basic Information Gathering" and add subsections

```
#### Basic Information Gathering
##### Retrieving Strings
##### Call Diagrams and Cross References
##### API Usage
##### Checking Secure Connections
```

Consider this:

- In "##### Retrieving Strings" and "##### Call Diagrams and Cross References" consider using radare2.
- In "##### API Usage" talk briefly about Bluetooth, NFC, Crypto ... You can reference 0x06d-j
- In "##### Check Secure Connections" You can talk about HTTPS, TLS, cert. pinning, Network Configuration. Be sure to check that no information is duplicated, be brief and reference 0x06g or other chapters.

**Comment by su-vikas** [comment]
Taking this one.
