### ISSUE TITLE
6c - Create Basic Information Gathering (Dynamic Analysis)

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1370]
add "#### Basic Information Gathering" in "### Dynamic Analysis" after "#### Dynamic Analysis on Non-Jailbroken Devices"

```
#### Basic Information Gathering
##### Opened Files
##### Opened Connections
##### Loaded Native Libraries
##### Sandbox Inspection
```

Thanks to Dynamic Analysis we are able to do some additional Information Gathering steps that we cannot do when performing Static Analysis. This section is meant to describe those steps.

Consider talking about Files and Permissions in "Sandbox Inspection".

**Comment by su-vikas** [comment]
Will take this one.

**Comment by su-vikas** [comment]
Mentioned in PR #1595  as well, and adding here for traceability. 

Currently content for `loaded libraries` is incomplete as pre-compiled vmmap exe is available only for armv7 and my self-compiled vmmap for arm64 is not working. Apple has hided most of the symbols and compiling and making it work has been painful so far. 

Will update the content once I get working. If there is an alternative command, do let me know :)
