### ISSUE TITLE
6c - Create Emulation-based Analysis

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1373]
add "#### Emulation-based Analysis" to "### Dynamic Analysis" after "#### Tracing"

```
#### Emulation-based Analysis
##### iOS Simulator
##### Corellium
```

Check chapter 5c to keep it consistent.

Consider:
- talking about simctl in "iOS Simulator" as well as caveats using the simulator. Consider the contents already in 6b "##### Testing on the iOS Simulator"
- adding Corellium https://corellium.com/ (just mention it shortly, it might vanish in some time)

**Comment by su-vikas** [comment]
As per my understanding you cannot run a release application on iOS simulator (release app dont have x86 code). If so, do we still want to have this chapter and what kind of content to include in that case?

**Comment by su-vikas** [comment]
I will take this one. I will put unicorn related stuff in this section ?

**Comment by cpholguera** [comment]
Hi @su-vikas this issue is actually much simpler as it looks. It is really only about testing with the emulator/simulator and what are the limitations in comparison to the Android counterpart (spoiler: Android wins, here there's not really much to do). One clear point is that you cannot run a release app as you already said. 

That about unicorn will be part of another section. I'd say in  "Binary Analysis" section of both 5c and 6c, what do you think?

**Comment by su-vikas** [comment]
Got it. I will put in Unicorn in Binary analysis section. 

And yes I agree this section will be pretty light, and can be done fast. I will send a PR soon.

**Comment by cpholguera** [comment]
Sounds great, thanks a lot!

**Comment by su-vikas** [comment]
@commjoen I think we can close this one?

**Comment by sushi2k** [comment]
Thanks @su-vikas! 

Was closed as covered in PR https://github.com/OWASP/owasp-mstg/pull/1553
