### ISSUE TITLE
6c - Create Information Gathering (Dynamic Instrumentation)

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1376]
add "##### Information Gathering" to "#### Dynamic Instrumentation" after "##### Tooling"

```
##### Information Gathering
###### Getting Loaded Libraries
###### Getting Loaded Classes and their Methods
###### Getting Runtime Dependencies

```

This section is intended to show a couple of cases where you can apply dynamic analysis for Information Gathering and present some of the things you can retrieve.

**Comment by su-vikas** [comment]
Will take this one :)

**Comment by commjoen** [comment]
It is yours now, happy hacking!

**Comment by su-vikas** [comment]
I think now we can close this one too :).

**Comment by sushi2k** [comment]
Indeed :-) Thanks for the nudge
