### ISSUE TITLE
6c - Create Process Exploration

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1377]
add "##### Process Exploration" to "#### Dynamic Instrumentation" after "##### Method Hooking".

```
##### Process Exploration
###### Memory Maps and Inspection
###### In-Memory Search
###### Memory Dump
###### Runtime Reverse Engineering
```

This section is intended to show a view of the app from within its memory. One of the recommended tools to address here is r2frida.

Check chapter 5c to keep it consistent. Once this ticket is ready: #1365

**Comment by commjoen** [comment]
Fixed in https://github.com/OWASP/owasp-mstg/pull/1424
