### ISSUE TITLE
Explain in the guide that 4.9 + 2nd factor should mean: enforce at remote endpoint

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1383]
As derived from https://github.com/OWASP/owasp-masvs/issues/189: we have to make sure that we explain in the mstg that with MFA, the 2nd/3rd factor should be enforced at the remote endpoint. And explain why capthca's (webviews/etc.) might not be a good idea.

**Comment by sushi2k** [comment]
@commjoen 
It's anyway already mentioned in 0x04e at the beginning of the chapter, but I just added it also to the 2FA test case, that 2FA/MFA should always be enforced on the serverside. 

Regarding CAPTCHAs, this is already mentioned in "Testing Best Practices for Passwords" in 0x04e. 

Or what did you mean back then with CAPTCHAs in Webviews?
