### ISSUE TITLE
Misused word

### ISSUE THREAD

**Issue by AOrobator** [OWASP/owasp-mstg#1433]
**Describe the issue**
In 0x05d-Testing-Data-Storage.md L127, when talking about passwords for realm databases, the word deferred is used, but probably should have been derived.

**Comment by commjoen** [comment]
An issue, a PR, all correct! What more can we wish for? 
Getting it to the next release ofcourse ^^. Thank you again @AOrobator !
Fixed in #1434 .

**Comment by AOrobator** [comment]
I'm learning a bunch from going through these documents, so I figured I'd pay it forward :)

**Comment by commjoen** [comment]
And we are grateful for you doing so! Thanks again 👍
