### ISSUE TITLE
Flutter MSTG

### ISSUE THREAD

**Issue by lehejcek** [OWASP/owasp-mstg#1436]
[Fuchsia](https://fuchsia.dev/) could became a wide spread OS and the [Flutter](https://flutter.dev/) SDK could be the preview of how apps will be build for it. Also its [high adoption](https://trends.google.com/trends/explore?date=today%205-y&geo=DE&q=flutter,react%20native) among developers for building apps for Android, iOS, macOS, Linux, Windows and the Web are maybe reasons to take a closer look.

Because the Flutter SDK is producing native code for both platforms, some guidelines may already could be followed.

**Android**
> The engine’s C and C++ code are compiled with Android’s NDK. The Dart code (both the SDK’s and yours) are ahead-of-time (AOT) compiled into a native, ARM and x86 libraries.

**iOS**
> The engine’s C and C++ code are compiled with LLVM. The Dart code (both the SDK’s and yours) are ahead-of-time (AOT) compiled into a native, ARM library. 

Please provide a OWASP MSTG for Flutter developers.

**Comment by commjoen** [comment]
Hi @lehejcek as you probably will understand, we cannot support that given the large amount of work. Instead the MSTG currently supports only Android and iOS . Instead, we can do something similar as we have started of with https://github.com/OWASP/owasp-masvs/issues/293 by asking you as the requestor to start mapping the compliancy sheet for Flutter. Are you up for that challenge?

**Comment by lehejcek** [comment]
Hi @commjoen sure, i am in 😃

**Comment by commjoen** [comment]
LEt's go then: fill in https://drive.google.com/file/d/1wHK3VI1cU1xmYrCu9yb5OHKUEeLIPSkC/view?usp=sharing 👍

**Comment by commjoen** [comment]
We will ask support from others through Twitter and Slack as we simply cannot write down all these security recommendations for those projects ATM.

**Comment by commjoen** [comment]
Migrating issue to https://github.com/OWASP/owasp-mstg/issues/1482
