### ISSUE TITLE
Alternative App Store apkpure not displaying SHA values

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1444]
APKpure claims to offer only verified APKs and their SHA. However, I'm not able to display the SHA values:

https://apkpure.com/es/faq-safe.html

APK Mirror on the other hand displays this information when clicking on **Verified safe to install (read more)**. Both SHA-1 and SHA-256 are displayed. 

I'd investigate this further. Because the guide states that both pages display the SHA values.

https://github.com/OWASP/owasp-mstg/blob/da4514f5676426d6b80fb3fd0b5bc2521639eca9/Document/0x05b-Basic-Security_Testing.md#alternative-app-stores

**Comment by commjoen** [comment]
<img width="1677" alt="Schermafbeelding 2019-09-11 om 19 57 01" src="https://user-images.githubusercontent.com/1457214/64722256-66873800-d4ce-11e9-845a-5b9703dc99f2.png">
Steps to reproduce: 
1. open a title
2. scroll to Versiones anteriores
3. select the version
4. click on ...
5. you can see hte version info.

I rather not detail steps to get it in the MSTG as this will change at the sites over time.

**Comment by commjoen** [comment]
Can we close this 👍  :-) ?

**Comment by cpholguera** [comment]
Nice! Thanks for checking. No, no need for step but good to verify it. We can close it :)

**Comment by commjoen** [comment]
Closing as agreed.
