### ISSUE TITLE
Document Xamarin specific oddities in Google Document

### ISSUE THREAD

**Issue by meetinthemiddle-be** [OWASP/owasp-mstg#1457]
Traceability-bug from Slack discussion on September 13th 2019.
E.g.: as discussed over Slack: we would like to have a google doc based compliance sheet which describes the different actions for Xamarin to secure a Xamarin app correctly compared to a native app.

**Comment by commjoen** [comment]
You ask: we serve! https://drive.google.com/file/d/1UL1yLRREJwXfe0HlrcX-IuvPYQM7lTtG/view?usp=sharing

**Comment by commjoen** [comment]
At this point, similarly to the React-native and Flutter checklist, we cannot fill it in ourselves as we are working on the native security issues instead of the hybrid ones. But let's see who can join to check the entries and update them.

**Comment by commjoen** [comment]
So for now: any experienced Xamarin developer and/or security expert: feel free to join! Check https://drive.google.com/file/d/1UL1yLRREJwXfe0HlrcX-IuvPYQM7lTtG/view?usp=sharing and help the community on how the controls should be implemented and validated (e.g. follow MSTG and/or  describe how to deal with it using Xamarin)

**Comment by commjoen** [comment]
Migrated issue to https://github.com/OWASP/owasp-mstg/issues/1482
