### ISSUE TITLE
Extend MSTG on connectivity remarks

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1493]
Based on https://github.com/OWASP/owasp-masvs/issues/132, we should have a MSTG-ARCH-3 testcase with explanation on the risks of bluetooth/nfc/etc. and reference to the testcase for payload encryption MSTG-MSTG‑RESILIENCE‑13.

**Comment by commjoen** [comment]
See https://github.com/OWASP/owasp-mstg/issues/1494

**Comment by cpholguera** [comment]
We considered this as part of MASVS-NETWORK and the ioXt standard will take care of this bulding on top of the MASVS.
