### ISSUE TITLE
Testing Backups for Tamper Detection

### ISSUE THREAD

**Issue by jasondoyle** [OWASP/owasp-mstg#1496]
I believe there is a need to add a section for testing tamper detection of modified backups in iOS apps. Many times security configurations are stored plainly in some plist within the app container and no keychain based integrity checks are performed to ensure security controls are not disabled after a device restore. 

I've used this attack to disable UI lockscreens when the pin is stored in a plist and have also used this attack to disable DLP controls in MDM managed apps.

It might make sense for this section to appear immediately after Testing Backups for Sensitive Data (MSTG-STORAGE-8).

**Comment by commjoen** [comment]
Hi @jasondoyle ! Thank you for submitting an issue. Just to make sure I understand: is this really the backup which you are then attacking or the plist stored on the filesystem?

**Comment by jasondoyle** [comment]
Hi @commjoen since modifying app container contents is not possible during runtime, an attacker can perform a device backup to access the target app's container content. At this point, the attacker can start reviewing files and configs for any settings with potential security implications (e.g., pincode, max failed login attempts, dlp settings, etc). These settings are sometimes in a plist the developer has added or some configuration in a sqlite db. After modifying the security settings and saving a new version of the backup, the attacker can then restore the backup to the device in an attempt to modify app behavior / turn off security controls. I hope this answered your question but if not let me know where to clarify.

**Comment by commjoen** [comment]
Makes total sense: a security configuration is part of the sensitive information to me. Can I ask you a favor? Can you help us out please and extend the existing testcase of MSTG-STORAGE-8 with this methodology?

**Comment by jasondoyle** [comment]
yes, happy to put something together

**Comment by commjoen** [comment]
Great! Looking forward to it!

**Comment by jasondoyle** [comment]
To modify backups I use the iMazing software which has been mentioned already in the owasp testing guide. Just want to ensure it's ok to use iMazing in my methodology again since I understand referencing commercial tools is discouraged. I'm not aware of a good free alternative that allows easy navigation and modification of backups.

**Comment by commjoen** [comment]
Opensource tooling would be preferred indeed, @sushi2k : would you know an alternative for that?

**Comment by sushi2k** [comment]
I am also not aware of an open source solution for this test case. I would say go with iMazing, but mention that it's shareware and not open source. As long as we can describe the test case with the free version, it's fine. Thanks @jasondoyle!

**Comment by commjoen** [comment]
Thanks! Fixed at #1516
