### ISSUE TITLE
Using one analysis tool for discussing reversing techniques

### ISSUE THREAD

**Issue by su-vikas** [OWASP/owasp-mstg#1501]
Currently there are multiple tools used to demonstrate the various analysis techniques that are involved while testing applications. For e.g in Android, for Reviewing disassembled code, all R2, ghidra, and IDA, all are used. I think this approach need to be reconsidered because: 

- Reader need to go through all sections of various tools to understand the techniques,  he/she might not be interested in knowing about all these tools
- The focus from exploring and discussing analysis technique is lost, instead it becomes a user guide on how to use tools
- Might lead to repetitive information and verbosity 
- Dont need to worry in case another tool is released in future

I propose we keep current format of introducing to various tools in the introduction part of the chapter, but while talking about the analysis techniques we use single tool. I propose to use Ghidra for native analysis, bcoz its open source, easy to use (unlike R2, at least for me), and most importantly has a a pretty decent decompiler. 

Please let me know if its reasonable, I can help in it where possible.

**Comment by commjoen** [comment]
Hi @su-vikas , thank you for submitting your issue!
I rather use different tools as we have it right now: this way you can see the various tools in action and learn from them. I don't want to cover "all tools out there", but instead at least have a solid basis in explaining the various current tools, which i believe the MSTG is finaly archieving thanks to many contributors like yourself. So let's not rewrite everything using Ghidra or any of the other reverse-engineering tools . Closing the issue.
