### ISSUE TITLE
Android: update biometrics parts with changes in Android 10

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1504]
There have been various changes in Android 10 for biometric authentication: https://developer.android.com/about/versions/10/features#improved-biometric-auth, these need to be processed in the android testing parts of the MSTG

**Comment by sushi2k** [comment]
The new BiometricManager class, available in Android 10 is covered in the PR https://github.com/OWASP/owasp-mstg/pull/1569/
