### ISSUE TITLE
Android 10: update in TLS 1.3 support and cryptographic changes

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1505]
https://developer.android.com/about/versions/10/features#tls-1.3 and https://developer.android.com/about/versions/10/features#conscrypt introduces quiet a few changes with TLS 1.3 and related cryptographic APIs on which the MSTG needs to be updated.

**Comment by A-AFTAHI** [comment]
I will take this one.

**Comment by commjoen** [comment]
It is yours! Looking forward to the results sir!

**Comment by cpholguera** [comment]
Hey @A-AFTAHI , how are you? Do you have any news on this one? Thanks!

**Comment by A-AFTAHI** [comment]
Hi @cpholguera , i'm good tahnks. i was busy with some work lately. i will push the updates later this sunday.

**Comment by cpholguera** [comment]
Sounds great, thanks @A-AFTAHI !

**Comment by commjoen** [comment]
Fixed in #1627
