### ISSUE TITLE
Android 10: connectivity management from the app

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1507]
Android 10 now gives access to network interfaces to connect, which gives oppertunity to further manage and secure the trustworthiness of the network being used. https://developer.android.com/about/versions/10/features#q-connnectivity

**Comment by sushi2k** [comment]
Is considered out of scope for the MSTG, as the user is prompted for example to switch to a peer-to-peer network. This is happening on the OS level
