### ISSUE TITLE
Extend iOS testing guide on testing apps that have common codebasis with macOS?

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1510]
https://developer.apple.com/documentation/uikit/creating_a_mac_version_of_your_ipad_app/ & https://developer.apple.com/ipad-apps-for-mac/ show that you can create a mac version of teh ipad app. however, this should not limit the secuirty controls taken by devs for the ipad version.

**Comment by cpholguera** [comment]
I'd say this is unfortunately out of scope.

**Comment by commjoen** [comment]
It is I guess :-)
