### ISSUE TITLE
v3SigningEnabled not available

### ISSUE THREAD

**Issue by zjn0505** [OWASP/owasp-mstg#1518]
I wonder what is the source for 
```
v3SigningEnabled true
```
at 
https://github.com/OWASP/owasp-mstg/blame/master/Document/0x05i-Testing-Code-Quality-and-Build-Settings.md#L65

I check Android Gradle plugin DSL, currently in ver. 3.5.1, there are `v1SigningEnabled` and `v2SigningEnabled`.
http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.SigningConfig.html

**Comment by commjoen** [comment]
https://android.googlesource.com/platform/tools/apksig/+/master/src/apksigner/java/com/android/apksigner/help_sign.txt shows support for v3 signing and the https://source.android.com/security/apksigning/v3 gives further indication of what is possible. Does this answer your question a little bit?

**Comment by zjn0505** [comment]
I understand v3 signature scheme is supported by `apksigner` as argument `--v3-signing-enabled`. 

Here in OWASP doc, it is referring that the field `v3SigningEnabled` can be used in Gradle to turn v3 signing on and off. So I wonder is this a valid config? As it is neither in the doc from the link in the original thread, nor pass the  build when used with Android Gradle Plugin 3.5.1 in Android Studio.

Can you verify of this config?

**Comment by zjn0505** [comment]
https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/dsl/SigningConfig.java#53

Here it supports to v2, but I may look at the wrong place and this may not be the latest branch.

**Comment by commjoen** [comment]
Hi @zjn0505 , I checked https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.SigningConfig.html and a few other resources, and you are right: v3signing is only available through APK signer. I will create a PR to fix this. Not sure how it slipped through earlier.

**Comment by commjoen** [comment]
Thanks for spotting it! And sorry to disapoint you on v3 signing.

**Comment by zjn0505** [comment]
Thanks for looking into this. I think it will be added eventually.
