### ISSUE TITLE
Source in the iOS testing tools is listed as malicious by Sileo

### ISSUE THREAD

**Issue by savagejen** [OWASP/owasp-mstg#1523]
> http://repo.hackyouriphone.org: Add the HackYouriPhone repository to get the AppSync package.

Sileo seems to be reporting that this source (recommended in the book) is malicious. I tracked down the author of AppSync and evidently it's being hosted in another repo. 

A reddit thread by an author of AppSync lists it as being available from an entirely different source: https://www.reddit.com/r/jailbreak/comments/cslj55/update_appsync_unified_411noa12_now_with_ios_124/

**Comment by commjoen** [comment]
Hi @savagejen ! Thank you very much for reporting this issue. It makes total sense to mention the right repo. Can I ask you a favor? Would you mind filing a PR with the fix?

**Comment by sushi2k** [comment]
Thanks for raising @savagejen! Fixed  and merged
