### ISSUE TITLE
Add to organizations which use MASVS and MSTG

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1528]
I would like to add following line to Users.md
STM Solutions actively uses both guides (MASVS and MSTG) during pentests.

```
- [STM Solutions](https://stmsolutions.pl/ "STM Solutions")
```

**Comment by commjoen** [comment]
Excellent! Can you do a PR for it? (Please keep in mind the alphabetic sorting 👍 )

**Comment by lwierzbicki** [comment]
PR sent. Please let me know if it is OK.

**Comment by commjoen** [comment]
It is, fixed :)
