### ISSUE TITLE
Have gender neutral text

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1534]
As first approached in #1532, thanks to @grenlith: we need to improve the reading of the text in the guide in which it is more gender neutral without adding any confusion to the text. Todo:

- decide on the techniques to replace "he" without making it confusing
- update the styleguide
- refactor the guide.

**Comment by commjoen** [comment]
Notes from meeting; in the next meeting we will setup a set of techniques in this issue that we can agree on to make it at least readable and consistent without sticking to "he" in the guide

**Comment by commjoen** [comment]
Meeting notes:
- we will refrain from he/she as we do not want to exclude non-binary
- singular "they" is very confusing to us and shall not be used (and will be part of the styleguide!)
- techniques that we want to use:

... only a noun: “a user should…”
… the plural: “When users should…”
… the second person: “When you are pentesting, you should…”
… an imperative: “Never use event bound methods like LaContext!”

**Comment by commjoen** [comment]
Please look for the following to replace:
- him
- his
- her
- she
- hers
- he

**Comment by sushi2k** [comment]
https://github.com/OWASP/owasp-mstg/issues/1582
