### ISSUE TITLE
Fix description of zxcvbn image

### ISSUE THREAD

**Issue by legik** [OWASP/owasp-mstg#1554]
**Describe the issue**
In the "0x04e-Testing-Authentication-and-Session-Management.md" the alt description for zxcvbn image is wrong (it is copy-paste from the image below):
```
<img src="Images/Chapters/0x04e/zxcvbn.png" alt="A successful attack in Burp Suite">
```

**Comment by commjoen** [comment]
Thank you for your issue @legik ! Good catch! Would you mind filing a PR for it?

**Comment by commjoen** [comment]
Superduper cool! Thank you for spotting and fixing it!
