### ISSUE TITLE
JWT tokens description

### ISSUE THREAD

**Issue by legik** [OWASP/owasp-mstg#1556]
**Describe the issue**
In the "MSTG-AUTH-3" section you have the following jwt description:

```plain
JWT tokens consist of three Base64-encoded parts separated by dots. 
The following example shows a Base64-encoded JSON Web Token
```
But according to [RFC](https://tools.ietf.org/html/rfc7519) JWT uses  "base64url" encoding. 

```plain
A JWT is represented as a sequence of URL-safe parts separated by
period ('.') characters.  Each part contains a base64url-encoded
value.  
```

So, this part should change from base64 to base64url, cause they have some differences in alphabet. 

In addtion, I can suggest to add a token structure example:

```
[Base64url(header)].[Base64url(payload)].[Base64url(signature)]
```

**Comment by cpholguera** [comment]
Hi @legik that's a very nice catch ;) could you please help us out by sending a PR including those changes? We'll highly appreciate it. Thank you in advance.

**Comment by sushi2k** [comment]
Thanks for the improvement! As the PR is merged, I will close this ticket.
