### ISSUE TITLE
Word(s) missing

### ISSUE THREAD

**Issue by legik** [OWASP/owasp-mstg#1560]
**Describe the issue**
In the [MSTG-AUTH-11](https://mobile-security.gitbook.io/mobile-security-testing-guide/general-mobile-app-testing-guide/0x04e-testing-authentication-and-session-management#testing-login-activity-and-device-blocking-mstg-auth-11) you have the following sentence:

```plain
The application provides an overview of the last session after login,
if the previous session was with a different configuration 
(e.g. location, device, app-version) then the user his current configuration.
```

Isn't some word(s) are missing after "then"?

**Comment by commjoen** [comment]
uhohw, you're right! Let me have a look at that

**Comment by commjoen** [comment]
Would the rewording in [this pr](https://github.com/OWASP/owasp-mstg/pull/1563) make more sense @legik ?

**Comment by sushi2k** [comment]
I was too fast and already merged the PR. @legik, please let us know if the change is also ok from your side. 
Thanks @legik and @commjoen.

**Comment by legik** [comment]
Yes, it's ok now. Thanks for fast fix.
