### ISSUE TITLE
Update ios interaction with Mac OS X now that Catalina no longer has iTunes

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1564]
Update ios interaction with Mac OS X now that CAtalina no longer has iTunes.

**Comment by commjoen** [comment]
This, together with how to apply checkra1n at catalina can be fixed in 1 issue i guess.

**Comment by sushi2k** [comment]
There are various sections in the MSTG that reference to iTunes, like 

https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06b-basic-security-testing#testing-device

These sections would need to be removed and an alternative way need to be shown.
