### ISSUE TITLE
Link parsing in gitbook version

### ISSUE THREAD

**Issue by legik** [OWASP/owasp-mstg#1565]
**Describe the issue**
In the gitbook version the [following link](https://mobile-security.gitbook.io/mobile-security-testing-guide/general-mobile-app-testing-guide/0x04f-testing-network-communication#ca-certificates) is parsed wrong:
![image](https://user-images.githubusercontent.com/657615/68575230-ab9efa80-047c-11ea-9f70-cd98ff99d27e.png)

**Comment by commjoen** [comment]
Fixed in #1566 , thanks @legik !
