### ISSUE TITLE
Improvement for Simulating a MiTM in 0x04f-Testing-Network-Communication

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1590]
**Describe the issue**
Section 'Simulating a Man-in-the-Middle Attack' contains description how to do place in MiTM position using bettercap and only mention using router/Access Point. During testing, I think it is much easier if you place yourself in MiTM position by creating Access Point and connect mobile devices to this access point (you need network access anyway). I used for that USB wifi card with AP possibility and then configure hostapd, dnsmasq & iptables. It is somehow mentioned in subsection 'Span Port / Port Forwarding', however without details and looks difficult to set up. Additionally, when I skim document I was not aware that subsection 'Span Port / Port Forwarding' leads to using WiFi AP.

**Next steps**
* Extend description for related subsection (i.e. how to set up WiFi AP for testing using USB card - similar step by step guide like for bettercap)
* Adjust/clarify subsection names

I can help with that.

**Comment by sushi2k** [comment]
Hi @lwierzbicki. This is of course one way of doing a MITM, but I must say that this is quite some overhead, in terms of hardware and software configuration. 
The easiest approach is by just using `adb reverse` on Android an forwarding all traffic via USB (https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05b-Basic-Security_Testing.md#client-isolation-in-wireless-networks). Then you just need to connect your laptop to the network  you need for testing (Wifi or RJ45). During a client engagement usually some UAT/test systems might only be available in certain Wifis provided by the client and then opening another wifi via USB might also become technically more difficult to setup. 

The same is also possible for iOS https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06b-Basic-Security-Testing.md#using-burp-via-usb-on-a-jailbroken-device. 

As setting up your own AP shouldn't be the preferred way, we shouldn't go into detail and put in a step-by-step instruction. Nevertheless, you could add some additional information if you want, like that you can easily setup an access point on a Macbook or  what kind of services you need (hostapd etc.) and if you have a detailed guide or ressource we could also link to it.

**Comment by lwierzbicki** [comment]
Hi @sushi2k. 
I refer to https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04f-Testing-Network-Communication.md#simulating-a-man-in-the-middle-attack, where detailed guide is provided about bettercap. I think it is easier to be a router/AP than ARP poisoning the network (at least more stable) ;)


Regarding valid use case...
I find this useful in following situation:
- working with Xamarin application
- when you need MiTM position (i.e. modify DNS reply)
- create a mobile testing lab

Real world scenario (from one of engagement)...
Client ask to perform test on their devices (without possibility to root/jailbroken). Additionally there were some additional restriction (MDM solution on devices).  Client provided dedicated WiFi network. First solution I found was to create WiFi AP (as I have a usb WiFi card for wifi pentesting) and then route traffic to laptop built-in wifi interface which was connected to client network. All you need is USB wifi card which support being AP, 3 config (hostapd, dnsmasq and wpa_supplicant) and run less than 10 commands (at least on Linux).

That lead me to conclusion that maybe some detailed guide (soon I will provide a link to example).

**Comment by sushi2k** [comment]
After reading it, I must say you are right and this setup should be part of the MSTG!

What we have for a MITM at the moment is this structure:

#### Simulating a Man-in-the-Middle Attack - bettercap 
##### bettercap Installation
##### Network Analyzer Tool
##### Network Setup
##### ARP Poisoning with bettercap

So after this (or before) what we could do is this structure: 

#### Span Port / Port Forwarding -> Simulating a Man-in-the-Middle Attack with your own Access Point
##### Installation
##### Configuration
##### Network Analyzer Tool
##### Network Setup and MITM attack

Feel free to create a PR for this, including to specify the use cases also (like you did in the post before). You can also reach out to me in OWASP Slack (https://github.com/OWASP/owasp-mstg/#contributions-feature-requests-and-feedback) then it's easier to communicate :-)

**Comment by lwierzbicki** [comment]
I will work on this.

**Comment by lwierzbicki** [comment]
During writing this I noticed a few things:
1. Section Network Analyzer Tool will be similar (the same) section for bettercap and your own Access Point - should we duplicate section or extract this to new point which cover both paths?
2. In Network Setup section is description about applicable case - maybe it would be good to reorder subsection ?
I propose following structure:
#### Simulating a Man-in-the-Middle Attack with bettercap
##### Network Setup
##### Installation
##### Configuration
##### MITM Attack
#### Simulating a Man-in-the-Middle Attack with your own Access Point
##### Network Setup
##### Installation
##### Configuration
##### MITM Attack

**Comment by sushi2k** [comment]
Thanks, that structure makes sense. The section "Network Analyzer Tool " can be a separate paragraph after describing both scenarios. Thanks for taking care of that!

**Comment by sushi2k** [comment]
Great work! Thanks @lwierzbicki and PR merged :-)
