### ISSUE TITLE
Improvement for 'Example - Dealing with Xamarin' in 0x04f-Testing-Network-Communication

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1591]
**Describe the issue**
'Example - Dealing with Xamarin' shows command to redirect traffic only for macOS (using rdr). Maybe it would be nice to add iptables one-liner for linux users? ;)
Additionally, redirecting traffic to intercepting proxy (i.e. Burp) could require additional step like further redirecting traffic (in Burp configuration of Proxy Listener)

**Next step**
* Extend description to cover mentioned cases.

**Comment by sushi2k** [comment]
Hi @lwierzbicki. Thanks for your suggestion. Do you want to take care of the iptables addition and create a pull request :-) ?
For the 2nd item `Additionally, redirecting traffic to intercepting proxy (i.e. Burp) could require additional step like further redirecting traffic (in Burp configuration of Proxy Listener)`. I am not sure what you mean with this. The proxy listener is started with burp automatically and is 8080 and it's also explained in the last sentence of the section https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04f-Testing-Network-Communication.md#example---dealing-with-xamarin, that the proxy listener need to run on the port you specified.

**Comment by lwierzbicki** [comment]
Hi, 
1st item - I will create pull request.
2nd item - Here is a case: subject is Xamarin application. You want to be in MiTM position (so all traffic goes through your proxy). However Xamarin doesn't respect your mobile device settings and you need to redirect all traffic to your intercepting proxy (using rdr or iptables). 
During testing, I encountered some Xamarin application which has proxy set to some service address and simple redirection doesn't work. My MiTM position allowed me to change DNS reply to that address and redirect traffic to my intercepting proxy. That also required that in proxy listener configuration I need to use additional functionality of burp:
1. Go to Proxy -> Options
2. Select used proxy listener and edit its configuration.
3. Go to tab 'Request handling' and specified 'Redirect to host', 'Redirect to port', set 'Force use of SSL' and set 'Support invisible proxy'.

Hope this explanation is clearer.

**Comment by sushi2k** [comment]
Wouldn't it solve the problem if you change /etc/hosts on the android phone, so it resolved to your proxy listener, e.g.:

foo.org 127.0.0.1

or 

foo.org 192.168.1.101

**Comment by lwierzbicki** [comment]
It solves the problem if you have root on mobile device (or possibility to change /etc/hosts).
Additionally 'Redirect to host' and 'Redirect to port' need to be set - as we hijack traffic to our intercepting proxy and we need to specify where it should go next (in mentioned case was original proxy configured in Xamarin application).

**Comment by sushi2k** [comment]
Do you want to add a short description and extend the chapter about Xamarin to explain this? I mean by explaining the Burp setting you mentioned earlier and modifying /etc/hosts on the Android phone.
For Android we can always assume that a rooted device is available.

**Comment by lwierzbicki** [comment]
Yes, I would like to contribute. 
I will create a PR.
