### ISSUE TITLE
Probably typo on 0x05b-Basic-Security_Testing

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1592]
**Describe the issue**
I noticed following line in text:
```
![Intercepted Messages]() 
```
It doesn't look like it should be there as other pictures are not handled that way. It is line 1751 of 
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05b-Basic-Security_Testing.md

**Comment by sushi2k** [comment]
Thanks, that was a leftover, removed it here https://github.com/OWASP/owasp-mstg/pull/1594

Good spot!
