### ISSUE TITLE
Have section numbers in the markdown of the MSTG

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1596]
Similar like the WSTG, it would be great to have section numbers as well. (As suggested by @ThunderSon )

https://github.com/OWASP/wstg/blob/master/document/4_Web_Application_Security_Testing/4.1_Introduction_and_Objectives/4.1.1_Testing_Checklist.md

**Comment by ThunderSon** [comment]
We (WSTG team) currently looking into what could be the best structure to follow to generate the PDF and to publish to an online generated website (_E.g._ git pages).
Having section numbers in the markdown text is still under review, as we're looking at 2 main points:
- Automating the section headers on publishing and its feasibility, maintainability, etc.
- Manual process, where a check is added on every PR opened to make sure that it is following the section numbering, which renders it easy to follow. Having checks in PRs for manual intervention by the author could assist in the maintainability of the numbering.

Will keep you updated on what our final decision is.

**Comment by cpholguera** [comment]
Updated link:

https://github.com/OWASP/wstg/blob/master/document/4-Web_Application_Security_Testing/04-Authentication_Testing/02-Testing_for_Default_Credentials.md

@sushi2k @TheDauntless This is also related to today's topic.

**Comment by cpholguera** [comment]
We won't do it for now. It didn't look good and with the new approach this won't be needed anyway. We'll move to one file per MASVS ID
