### ISSUE TITLE
"mobile" misspelled as "mobtile" on the cover page 

### ISSUE THREAD

**Issue by avengerstark-web** [OWASP/owasp-mstg#1598]
"mobile" is misspelled as "mobtile" on the cover page 

![image](https://user-images.githubusercontent.com/43069307/70642753-cbf1de80-1c0d-11ea-8bf9-829aa18fad13.png)

**Comment by sushi2k** [comment]
Autsch. Thanks for pointing it out :-) 
It's already fixed in the new cover https://github.com/OWASP/owasp-mstg/blob/master/Document/cover.jpg
