### ISSUE TITLE
Upgrade Randorisec from donator to "Good Samaritan"

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1600]
Randorisec can be upgraded to Good samaritan: logos are attached
![randori_logo_original](https://user-images.githubusercontent.com/1457214/70656673-d1294a80-1c5a-11ea-9643-5db9f3f22df8.png)

**Comment by sushi2k** [comment]
https://github.com/OWASP/owasp-mstg/pull/1601

**Comment by commjoen** [comment]
Fixed by Sven at #1601
