### ISSUE TITLE
Heading level 7 issue

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1604]
**Describe the issue**
Heading level 7 is not displayed in github. I think Markdown only handles level 1-6 (but I'm not sure). This way heading is not handled (style is not applied) as heading and it is just displayed:
####### [Section Name]

**Optional: Testcase or section**
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05b-Basic-Security_Testing.md#bypassing-the-network-security-configuration
or perform search by "#######" (7x#)

**Comment by sushi2k** [comment]
Thanks, good spot! Just made a PR
