### ISSUE TITLE
WiFi or Wi-Fi convention 

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1605]
**Describe the issue**
Maybe it would be good to have one convention regarding WiFi word?
Currently I found that WiFi or Wi-Fi are used. 

**Optional: Testcase or section**
Wi-Fi used in example in 0x06b-Basic-Security-Testing.md. 
WiFi used in example 0x04f-Testing-Network-Communication.md
or just grep:
```
grep -rnw ./ -e "WiFi"
grep -rnw ./ -e "Wi-Fi"
```

**Comment by sushi2k** [comment]
Thanks for pointing out this inconsistency. It's indeed not in our style-guide yet. I will add it and make everything "Wi-Fi", as that's the writing used by the Wi-Fi alliance  (https://www.wi-fi.org/).
