### ISSUE TITLE
Cert Pinning - TrustManager 

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1612]
**Describe the issue**
I encountered case where to bypass Cert Pinning I did the following:
1. Unpack app & find that there is res/raw/truststore (bks file). 
2. Code was obfuscated and I'm a lazy person. Found part of a code which was responsible for loading truststore (additionally trivial solution 'switch off ssl pinning using objection' didn't work).
3. Get hint from a sentence "Once the KeyStore has been loaded, we can use the TrustManager that trusts the CAs in our KeyStore" :)
4. Added my burp cert to application keystore.
5. Repack application.
6. Intercept traffic in burp :)

I would like to share know-how in this section (using keytool and bouncycastle jar). What do you think? 

**Optional: Testcase or section**
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05g-Testing-Network-Communication.md#trustmanager

**Comment by sushi2k** [comment]
This would fit in here: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05g-Testing-Network-Communication.md#bypassing-certificate-pinning

The other link is part of static testing.
