### ISSUE TITLE
Unfinished link in reference?

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1615]
**Describe the issue**
Noticed that one of reference start with [#mueller]. Looks like markdown for a link, but no link shows up. Maybe creator of that line had something else on mind ;) Or maybe it is just typo.
Please let me know if someone knows how the line should look like and I will be happy to complete it :)

**Optional: Testcase or section**
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#references

**Comment by lwierzbicki** [comment]
The same happened here: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04b-Mobile-App-Security-Testing.md#references

**Comment by sushi2k** [comment]
@lwierzbicki  Thanks for spotting it! Do you want to make a PR and make it compliant to the style guide :-)

**Comment by lwierzbicki** [comment]
Will do a PR. However first I crosscheck all references.
