### ISSUE TITLE
Dublicate words in Testing OAuth 2.0 Flows

### ISSUE THREAD

**Issue by sadshade** [OWASP/owasp-mstg#1616]
Other OAuth2 Best **Best** Practices

**Comment by lwierzbicki** [comment]
I think you mean this heading: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04e-Testing-Authentication-and-Session-Management.md#other-oauth2-best-best-practices

**Comment by sushi2k** [comment]
@sadshade Thanks for spotting it! Do you want to make a PR :-) ?

**Comment by cpholguera** [comment]
Fixed already on #1620
