### ISSUE TITLE
Leading space before sentence end

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1618]
**Describe the issue**
Leading space before sentence end i.e "sidestep sandboxing . "

**Optional: Testcase or section**
Locations:
Document/0x05a-Platform-Overview.md line: 157
Document/0x05c-Reverse-Engineering-and-Tampering.md line: 776
Document/0x05c-Reverse-Engineering-and-Tampering.md line: 2249
Document/0x06b-Basic-Security-Testing.md line:761

**Comment by sushi2k** [comment]
Can you create a PR for this? Thanks

**Comment by lwierzbicki** [comment]
Will do.
