### ISSUE TITLE
Content Provider, Content provider or content provider

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1619]
**Describe the issue**
Content Provider name is inconsistently used - noticed versions: Content Provider, content provider, Content provider. Additionally, one sentence starts with lowercase version, next with first capital letter of each word. If I get information which is correct, I will create PR.

**Optional: Testcase or section**
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05a-Platform-Overview.md#content-providers

**Comment by sushi2k** [comment]
Let's use the lowercase version "content provider" and only write a capital C if it's the beginning of a sentence (see also https://developer.android.com/guide/topics/providers/content-providers).
