### ISSUE TITLE
Add Test case for MSTG‑RESILIENCE‑13

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1622]
**Platform:**
iOS / Android 

**Description:**
A new requirement was introduced in the MASVS about payload encryption that need to be described as test case in the MSTG: 

### Impede Eavesdropping

| # | MSTG-ID | Description | R |
| --- | --- | --- | -- |
| **8.13** | MSTG‑RESILIENCE‑13 | As a defense in depth, next to having solid hardening of the communicating parties, application level payload encryption can be applied to further impede eavesdropping. | ✓ |

**Comment by cpholguera** [comment]
Duplicate of #1494?

**Comment by sushi2k** [comment]
True :-) Closing it
