### ISSUE TITLE
Testing for Insecure Configuration of Instant Apps (MSTG-ARCH-1, MSTGARCH- 7)

### ISSUE THREAD

**Issue by its4win** [OWASP/owasp-mstg#1625]
**Platform:**
Android

**Description:**
I'm very newbie to testing mobile application.
I've read 
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05h-Testing-Platform-Interaction.md #Testing for Insecure Configuration of Instant Apps (MSTG-ARCH-1, MSTGARCH- 7)

For Static Analysis, i must check for Android Manifest to see whether dist:module dist:instant="true",
can i know what app used in that test?

I used https://github.com/OWASP/MSTG-Hacking-Playground/blob/master/Android/MSTG-Android-Java-App/app/app-x86-debug-Android5.apk 
but i didn't found dist:module in that AndroidManifest.xml

So, how can i do testing for insecure configuration of instants apps?

Thanks in advance

**Comment by commjoen** [comment]
This is a great question! Currently we do not have any testing app with that configuration. 
The apps used in this tests are commercial modular apps that have been modularly designed or refactored. I don't have an open source app from which we can show the "Wrong configuration" unfortunately. A lot of apps still don't use the instant-app capability. It would be a nice idea for the playground (@sushi2k ?) to have some modularity testing at one of the apps over there. Alternatively other open source vulnerable android app developers could try something as well? (@satishpatnayak)

**Comment by sushi2k** [comment]
Thanks for bringing that up. I created a ticket for that in the Hacking Playground. No ETA can be given though :-) But it's an interesting question and I hope I can find some and add a test case.

**Comment by cpholguera** [comment]
Should we close this one as it's already in the Hacking playground issues?
