### ISSUE TITLE
Multiple markdownlint errors - i.e. trailing spaces

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1632]
I noticed multiple markdown lint errors in following documents:
Document/0x05d-Testing-Data-Storage.md
Document/0x04f-Testing-Network-Communication.md
Document/0x04g-Testing-Cryptography.md
Document/0x05c-Reverse-Engineering-and-Tampering.md
Document/0x05g-Testing-Network-Communication.md

Most common errors:
- MD009/no trailing spaces
- MD012/no multiple blanks
- MD040/fenced code language

I can correct these errors and commit.

**Comment by cpholguera** [comment]
Fixed in #1630
