### ISSUE TITLE
Hostname left in code snippet

### ISSUE THREAD

**Issue by lwierzbicki** [OWASP/owasp-mstg#1648]
**Describe the issue**
Someone's hostname was left in code snippet (location below). 
I mean this line:
```
angler:/ # netstat -p | grep 24685
```
To be consistent across code snippets I would remove hostname from it. 

**Optional: Testcase or section**
owasp-mstg/Document/0x05c-Reverse-Engineering-and-Tampering.md
line 566

**Comment by sushi2k** [comment]
Thanks! Please make a PR for it.
