### ISSUE TITLE
Evaluate new Github Feature

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1649]
**Describe the issue**
Explore and evaluate the new Github feature https://github.blog/2020-01-22-how-we-built-good-first-issues/

> GitHub is leveraging machine learning (ML) to help more people contribute to open source. We’ve launched the good first issues feature, powered by deep learning, to help new contributors find easy issues they can tackle in projects that fit their interests.

Might be worth to do this, to get matches to our tickets!

**Comment by cpholguera** [comment]
Let's keep using the "good first issue" label, that should do it :)
