### ISSUE TITLE
Testing iOS Libraries with objection (MSTG-NETWORK-6, MSTG-CODE-5)

### ISSUE THREAD

**Issue by leonjza** [OWASP/owasp-mstg#1652]
Noticed the section where one could enumerate third party libraries was missing a dynamic analysis section using objection. The commands `ios bundles list_frameworks` and `ios bundles list_bundles` both produce output with the parsed versions numbers of the target libraries as output.

Eg:

```
com.leon.dev on (iPad: 12.4) [usb] # ios bundles list_frameworks
Executable           Bundle                                Version    Path
-------------------  ------------------------------------  ---------  -------------------------------------------

[...]

protobuf             org.cocoapods.protobuf                3.10.0     ...siness.app/Frameworks/protobuf.framework
Kingfisher           org.cocoapods.Kingfisher              5.8.3      ...ness.app/Frameworks/Kingfisher.framework

[... ]
```

**Comment by cpholguera** [comment]
Hi @leonjza,

Thanks for letting us know. That's great, we should definitely add it. Is there also a version of this command for Android?

**Comment by leonjza** [comment]
Not yet no. Pull requests welcome though haha!

**Comment by cpholguera** [comment]
Same here ^^ If you see something like this and have the time to quickly send a PR we'll be very thankful. If not, at least reporting it also helps of course, as you did here, thanks again!👌

**Comment by A-AFTAHI** [comment]
Hi @cpholguera you can assigne this to me. i like to work on it.

**Comment by cpholguera** [comment]
Thanks!

**Comment by sushi2k** [comment]
Hi @A-AFTAHI. Thanks for volunteering. Can you still pick it up?

**Comment by sushi2k** [comment]
Can be added here: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06i-Testing-Code-Quality-and-Build-Settings.md#dynamic-analysis-3

**Comment by A-AFTAHI** [comment]
@sushi2k  i'm sorry i'm really drowning in some work over here u can assing it to someone else and i'll pick up an other issue when i'm able to.

**Comment by karolpiateknet** [comment]
Hey @sushi2k  I could pick that up :)

**Comment by cpholguera** [comment]
Hi @karolpiateknet thank you very much, it's assigned to you ;)
