### ISSUE TITLE
Unable to check out repo on Github Desktop on windows

### ISSUE THREAD

**Issue by TheDauntless** [OWASP/owasp-mstg#1657]
When cloning the repo on Github Desktop on Windows, I get an error that the file tree contains a backslash in a filename and therefore can not be cloned:

![image](https://user-images.githubusercontent.com/1650034/74611776-764f1c00-50ff-11ea-87fa-90e77fc10b24.png)

> Error: Filename in tree entry contains backslash

Current workaround:
- git clone from cmd prompt

Fix:
- Remove the Tools/\ folder from the git history.

**Comment by sushi2k** [comment]
Hey @TheDauntless. Thanks for raising. How do you know it's the tools folder? At least in the screenshot you shared I cannot find it.

**Comment by cpholguera** [comment]
@TheDauntless , is this still an issue?
