### ISSUE TITLE
Where can I access the background app preview screenshot in Android?

### ISSUE THREAD

**Issue by bad5ect0r** [OWASP/owasp-mstg#1666]
For iOS, you can visit the following directory and download the screenshots:

`/var/mobile/Containers/Data/Application/$APP_ID/Library/Caches/Snapshots/`

This information is not provided for Android. Is it even possible for an attacker with only file system access to download these screenshots?

**Comment by legik** [comment]
hi @bad5ect0r ,

The palce of preview screenshots depends on vendor. But in most cases you can find snapshots in the following folders:
- /data/system/recent_images

If device support file-based encryption:
- /data/system_ce/{USER_ID}/snapshots
- /data/system_ce/{USER_ID}/recent_images

**Comment by sushi2k** [comment]
Thanks for pointing that out guys. In iOS this directory is covered in the dynamic testing section, but not for Android.

This should be added for the dynamic scanning in Android:
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#finding-sensitive-information-in-auto-generated-screenshots-mstg-storage-9

**Comment by legik** [comment]
@sushi2k 
I will create a PR for this

**Comment by sushi2k** [comment]
Hi @legik. Do you have some time to follow up on this? Thanks again for bringing it up.

**Comment by legik** [comment]
Hi @sushi2k,
Not sure about grammar, check please.
