### ISSUE TITLE
Port forwarding in "Tampering and Reverse Engineering on iOS"

### ISSUE THREAD

**Issue by legik** [OWASP/owasp-mstg#1667]
**Describe the issue**
In the [Debugging with LLDB](https://github.com/OWASP/owasp-mstg/blob/d3460bab8bc512b348807830afbb9455acf9a604/Document/0x06c-Reverse-Engineering-and-Tampering.md#debugging-with-lldb) section a python "tcprelay.py" script for port forwarding was mentioned without any reference. 

The same process can be done with iproxy utility which is already described in "basic-security-testing". Maybe the following port forwarding example would be better:
```sh
$ iproxy 2222 22
$ scp -P 2222 debugserver root@localhost:/tmp/
```

**Comment by sushi2k** [comment]
Good spot! Do you mind making a PR @legik?

**Comment by legik** [comment]
@sushi2k 
I will make a PR
