### ISSUE TITLE
Content Not Aligned With Apple Dev Docs

### ISSUE THREAD

**Issue by shivsahni** [OWASP/owasp-mstg#1672]
**Describe the issue**
The following section is taken from here: https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06f-testing-local-authentication#using-keychain-services-for-local-authentication

> If LocalAuthentication.framework is used in an app, the output will contain both of the following lines (remember that LocalAuthentication.framework uses Security.framework under the hood)

It says that **LocalAuthentication.framework uses Security.framework under the hood**. However, as per the Apple Dev Docs, it seems that the converse is true.

> To access keychain items in general, you use keychain services within the Security framework. When authentication is needed, keychain services then relies on the LocalAuthentication framework to present the appropriate interface to the user.

Reference:  https://developer.apple.com/documentation/localauthentication/accessing_keychain_items_with_face_id_or_touch_id

**Comment by cpholguera** [comment]
Same here, It'd help us a lot if you'd open a little PR with your suggestions :) thanks a lot for proofreading!

**Comment by shivsahni** [comment]
Hey @cpholguera,

I can definitely open a PR for this, not an issue at all. However, could you please confirm if whatever I mentioned makes sense and we actually need to correct the content.

**Comment by sushi2k** [comment]
Ok, so LAContext and Keychain services definitely play together. I would say that LAContext uses the security framework under the hood, at least this is what the documentation is describing for security framework (even though LAContext is not mentioned specifically) https://developer.apple.com/documentation/security. 

> > To access keychain items in general, you use keychain services within the Security framework. When authentication is needed, keychain services then relies on the LocalAuthentication framework to present the appropriate interface to the user.

I think this just means that LAContext is then deciding if the Touch or Face ID UI will be shown to the user to ask for the supported biometric input. 

I think there is no correction needed. Any other comments?

**Comment by sushi2k** [comment]
@shivsahni let us know if you have other feedback to this item

**Comment by cpholguera** [comment]
Closing after long inactivity, please re-open if it needs more clarification or contact us on Slack :)
