### ISSUE TITLE
Use of SHA1PRNG (MSTG-CRYPTO-2, MSTG-CRYPTO-3 and MSTG-CRYPTO-4)

### ISSUE THREAD

**Issue by drZaius** [OWASP/owasp-mstg#1685]
I've been reading the MSTG and noticed in the section "Testing the Configuration of Cryptographic Standard Algorithms (MSTG-CRYPTO-2, MSTG-CRYPTO-3 and MSTG-CRYPTO-4)" that when using SecureRandom, SHA1PRNG is deprecated and should no longer be used. Instead, a SecureRandom object should be instantiated as follows

``SecureRandom random = new SecureRandom();``

I wanted to check what algorithm is used in this case, and therefore wrote a simple app that creates a SecureRandom object. Using frida, I intercepted the constructor method and had frida output the algorithm and provider name. Turns out, the algorithm is still SHA1PRNG (by default, apparently), and the provider is AndroidOpenSSL v1.0.

Does this mean that only the SHA1PRNG implementation of the (deprecated) "Crypto" provider is deprecated and vulnerable? Or SHA1PRNG in general? In the latter case, this would mean that SecureRandom is not secure after all.

**Comment by sushi2k** [comment]
Thanks @drZaius, that's a very good question. Can you please let us know which Android version you were using to run the app? 

@lwierzbicki as you are rewriting some of the crypto stuff for Android, any thoughts on this one?

**Comment by commjoen** [comment]
Thank you @drZaius ! I do wonder: did you test it with a patched security provider?

**Comment by drZaius** [comment]
Thanks for your quick reply!

@sushi2k I actually ran the app on two different phones (Nexus 5X and Pixel 3), both running Android 10 with build version 29.

@commjoen  no, I only used the default provider. As mentioned in my post, I simply created a new SecureRandom object using ``SecureRandom random = new SecureRandom();``.
I just tested my frida script also on the PayPal and the Signal app. When they call the SecureRandom constructor the algorithm again is SHA1PRNG. But unlike PayPal, Signal uses the Conscrypt provider instead of the default AndroidOpenSSL.

So again the question here is whether SHA1PRNG is deprecated/vulnerable in general or if this only affects the SHA1PRNG implementation of the Crypto provider (which is [deprecated](https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html))?

**Comment by lwierzbicki** [comment]
@drZaius - what do you mean by `uses the Conscrypt provider instead of the default AndroidOpenSSL`. Based on my understanding Conscrypt is AndroidOpenSSL. 

I would investigate the case with SHA1PRNG and will try to answer your question.  

Currently, I would say that SHA1PRNG is not cryptographically strong and Crypto provider is depracated. But let me double check.

**Comment by lwierzbicki** [comment]
I used following code snippet on Android emulator API 28 :
```
SecureRandom random = new SecureRandom();
Log.v("algorithm: ", random.getAlgorithm());
Log.v("provider: ", random.getProvider().getName());
```
And output is:
```
V/algorithm:: SHA1PRNG
V/provider:: AndroidOpenSSL
```

@drZaius - this confirms your case.

In official Android docs, I found the following statement:
`The SHA1PRNG algorithm from the Crypto provider has been deprecated as it was insecure, and also incorrectly used by some apps as a key derivation function. See Security "Crypto" provider deprecated in Android N for details.`

When I take a look of available algorithms from [javadocs](https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SecureRandom), we don't have much choice regarding algorithms.

I will take a closer look to SHA1PRNG.

**Comment by drZaius** [comment]
@lwierzbicki yes, it seems that Conscrypt is just using AndroidOpenSSL as its provider name, but they appear to be the same. Although I do not understand why ``getProvider().getName()`` sometimes returns Conscrypt and sometimes AndroidOpenSSL.

Thanks for confirming my case. I've also taken a look at the [source code](https://android.googlesource.com/platform/libcore/+/dab9b37/ojluni/src/main/java/java/security/SecureRandom.java) of SecureRandom. It first tries to get a PRNG algorithm as follows:

``Gets a default PRNG algorithm by looking through all registered providers. Returns the first PRNG algorithm of the first provider that has registered a SecureRandom implementation, or null if none of the registered providers supplies a SecureRandom implementation.``

In case this returns null, it uses the SUN implementation of SHA1PRNG.

**Comment by lwierzbicki** [comment]
I found the following paragraph in [Android dev docs]("https://developer.android.com/reference/java/security/SecureRandom#getInstanceStrong()"):
`
In Android this is equivalent to get a SHA1PRNG from AndroidOpenSSL. Some situations require strong random values, such as when creating high-value/long-lived secrets like RSA public/private keys. To help guide applications in selecting a suitable strong SecureRandom implementation, Java distributions include a list of known strong SecureRandom implementations in the securerandom.strongAlgorithms Security property
`

I used the following code snippet:
```
SecureRandom random = new SecureRandom();
Log.v("algorithm: ", random.getAlgorithm());
Log.v("provider: ", random.getProvider().getName());
Log.v( "strong algorithms", Security.getProperty("securerandom.strongAlgorithms"));
SecureRandom random2 = null;
try {
    random2 = SecureRandom.getInstanceStrong();
} catch (NoSuchAlgorithmException e) {
    e.printStackTrace();
}
Log.v("algorithm: ", random2.getAlgorithm());
Log.v("provider: ", random2.getProvider().getName());
```
And every case shows SHA1PRNG from AndroidOpenSSL. 

Let's summarize:
* default constructor with no argument should be used (that leads to using SHA1PRNG from AndroidOpenSSL)
* I will adjust recommendation in MSTG (remove misleading prohibition for SHA1PRNG which should be explained as SHA1PRNG from Crypto provider)

Please let me know if you see additional correction/comments/improvement which can be added.

**Comment by commjoen** [comment]
It seems that it is indeed about the implementation of the Crypto provider. Patching the provider should lead to always returning AndroidOpenSSL as a provider. So i guess that got wrongly interpreted. Nice catch! Thanks! Your actions seem to be perfectly fit indeed. Looking forward to your PR!

**Comment by lwierzbicki** [comment]
I made correction in the latest PR regarding crypto. This issue is now closed (as I removed prohibition for SHA1PRNG which should be explained as SHA1PRNG from Crypto provider and clarified that SHA1PRNG from AndroidOpenSSL should be used).
