### ISSUE TITLE
Revisit iOS (MSTG-RESILIENCE-9)

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1693]
- **Obfuscation Techniques**: Introduce the types of obfuscation techniques available that make sense for iOS (both Obj-C and Swift and why): name obfuscation, string encryption, control flow obfuscation, dummy code insertion, opaque predicate insertion, etc. (a comparison to Android would also help).
- **Abstraction Levels**: source, binary, IR
- **Static vs Dynamic**: e.g. is "Self-modifying code" a thing for iOS? why?
- **SwiftShield**: State more clearly (based on the above) what SwiftShield is doing, it's a simple name obfuscation working at source level?
- **Other tools/techniques**?
  - Obfuscator-LLVM (works at Intermediate Representation (IR) level): https://github.com/obfuscator-llvm/obfuscator/wiki
  - Commercial tools? What do they generally do / are based on? e.g. https://dexprotector.com/

**Comment by cpholguera** [comment]
@serek8 requested per PM taking care of this issue. However I cannot assign him.

I'll check and let you know @serek8

**Comment by sushi2k** [comment]
Hey @serek8. Please click on the invite via mail or here: https://github.com/OWASP/owasp-mstg/invitations. 
Then we can assign the ticket to you! Ping Carlos or me for any issues. Thanks

**Comment by serek8** [comment]
Hey @cpholguera and @sushi2k, thanks for the invitation, I just accepted it. Please assign the task to me. @cpholguera, do you mean something specific by "Self-modifying code" for iOS? I believe Apple doesn't allow modifying executable pages in any order. Or you just want me to clarify why Self-modifying code is NOT the case on iOS? Thanks

**Comment by cpholguera** [comment]
Assigned @serek8! yes exactly, that'd be the idea, to explain the ones that are applicable and for the interesting ones that are not applicable also to tell why. If you have sources to link please also do so. Thank you so much!
