### ISSUE TITLE
Carthage Analyzr

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1697]
**Platform:**
iOS

**Description:**

At the moment it's not possible to analyse Cartage packages. This is still a gap and can be added to Document/0x06i-Testing-Code-Quality-and-Build-Settings.md. 

Tasks:

1. Research if any other tool can find vulnerabilites in Carthage
2. Develop your own analyzer and share with the community :-) See 
https://github.com/OWASP/owasp-mstg/pull/1690#discussion_r407389358

**Comment by cpholguera** [comment]
There's an issue for this in OWASP Dep. Check: https://github.com/jeremylong/DependencyCheck/issues/962; info added to PR #1811  so we can close this one.
