### ISSUE TITLE
gdb installation

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1725]
**Describe the issue**
gdb cannot be installed via http://cydia.radare.org/debs/. This repo is not working anymore. 

Need to find an alternative. 

gdb is listed here: https://github.com/OWASP/owasp-mstg/blob/2918b24f297acc27a48d6f50b63b4467fdaa6a66/Document/0x08-Testing-Tools.md#dynamic-and-runtime-analysis-2

**Comment by calabacito** [comment]
@radare ?  I guess this is not supported anymore?

**Comment by commjoen** [comment]
can https://iosgods.com/topic/71325-gnu-debugger-gdb-for-arm64/ be of any value?
