### ISSUE TITLE
Update Android Encryption

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1753]
https://twitter.com/DDinorahtovar/status/1264615629698580485?s=20

Check and update what's missing.

**Comment by lwierzbicki** [comment]
I can take a look and see if we need to update what's missing.

**Comment by commjoen** [comment]
Yes please, can you please update your tracking issue and then close this issue with a reference to yours?

**Comment by lwierzbicki** [comment]
Yes, of course. That was my plan :)

**Comment by lwierzbicki** [comment]
I reviewed part 1,2 and 3. I would sum up this as introduction to [Android Jetpack Security](https://developer.android.com/jetpack/androidx/releases/security). 
Part 1 -> description of Cipher class
Part 2 -> intro to KeyStore and TEE/SE
Part 3 -> EncryptedSharedPreferences and EncryptedFiles.

We've already started discussion about Android Jetpack (by picking topic EncryptedSharedPrefences) in issue #1662 . 

Only parts 1-3 were released in this article series, I would wait for parts 4-6 and verify them as well.

**Comment by lwierzbicki** [comment]
Till now, only part 4 were added - which focused on `Biometric as Local Auth` (mainly from implementation point of view). Currently it doesn't anything new. I would close this issue and create a new one if anything interesting shows up.
