### ISSUE TITLE
[iOS] how to call system function from swift code?

### ISSUE THREAD

**Issue by mkaraoz** [OWASP/owasp-mstg#1754]
**Platform:**
iOS

**Description:**
In **iOS anti-reverseing defence** chapter, under **Jailbreak detection (MSTG-RESILIENCE-1)** -> **calling system apis** subtitle, document says that "Calling the system function with a "NULL" argument on a non-jailbroken device ..."

How can we make a call to the system() function. When I try to call it from swift code I get system is not part of iOS compiler error.

A code example would be great. 

Thanks.

**Comment by sushi2k** [comment]
Thanks for pointing that out. A quick Google search says that from iOS 11 onwards the system() function is not available anymore. Seems that part in the RE chapter need to be updated/removed.

https://forums.developer.apple.com/thread/100617
