### ISSUE TITLE
Add SMS retriever API

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1777]
Add to https://github.com/OWASP/owasp-mstg/blob/e6ddca17b0a95e521463cf66892a0e4496cd0e7d/Document/0x05h-Testing-Platform-Interaction.md#permission-analysis

With the sms retriever API an app is able to trigger an SMS on the backend and the OS will give it back. It must contain a certain set of characteristics, e.g. a certain hash. This way the app does not have to request read access to SMSs as a permission. Example app: WhatsApp

**Comment by 0x10f2c** [comment]
I'll do some research into this and add it

**Comment by cpholguera** [comment]
That would be great @0x10f2c, thanks!

**Comment by 0x10f2c** [comment]
Will try to get onto this next weekend, been quite busy of late!

**Comment by cpholguera** [comment]
Perfect, thanks for the update :)
