### ISSUE TITLE
Broken Vantagepoint Blog links

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1781]
It seems that all links to Vantagepoints blog are broken now. e.g. https://www.vantagepoint.sg/blog/90-the-jiu-jitsu-of-detecting-frida from 0x05j-Testing-Resiliency-Against-Reverse-Engineering.md

Thanks to @fujiokayu for pointing that out in #1780!

**Comment by martinbydefault** [comment]
Wayback machine has some mirrors of the site: https://web.archive.org/web/20181227120751/http://www.vantagepoint.sg/blog/90-the-jiu-jitsu-of-detecting-frida

**Comment by cpholguera** [comment]
awesome, thanks @martinbydefault !
