### ISSUE TITLE
React Native and Flutter are not hybrid as per the given definition

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#1787]
From https://github.com/OWASP/owasp-masvs/issues/461  by @mrrenaud

https://github.com/OWASP/owasp-mstg/blob/1.1.3/Document/0x04a-Mobile-App-Taxonomy.md#hybrid-app

Hybrid apps are described this way :

A hybrid app executes like a native app, but a majority of the processes rely on web technologies, meaning a portion of the app runs in an embedded web browser (commonly called “webview”)

But this is not true for framework such as React Native, Flutter or even Xamarin. They may have 3 different approaches, but none of them uses an embedded browser.

Do you think it would be interesting to clarify that point, and maybe introduce a new category?

**Comment by jadeboer** [comment]
Absolutely necessary.

**Comment by su-vikas** [comment]
i will take this one.

**Comment by vixentael** [comment]
Shouldn't this be closed?

**Comment by cpholguera** [comment]
That's right, thanks @vixentael for keeping an eye on the issues ;)
