### ISSUE TITLE
Error in "Obtaining and Extracting Apps" section

### ISSUE THREAD

**Issue by m2sup3rn0va** [OWASP/owasp-mstg#1794]
**Section - Obtaining and Extracting Apps**
**2 - From a Jailbroken device**

In this point, it's mentioned that after installing the app from App store, you need to rebuild the IPA from memory because of DRM, but I guess that is not correct.

As per my understanding, DRM is applicable till App store and only for IPA's injected with streaming videos to protect copyright and Apple to have sole ownership of the video.

Once the app is installed, we can go to **Bundle location** and zip the **.app** folder and rename it to **.IPA** and then we can scp that to our local drive which can in-turn be re-installed via **Filza**.

I have tried the same and have created a tool to get the **IPA** and have tested with most of the app including the banking ones and it works just fine and also I am able to re-install that also.

The only catch here is that we need a **"jailbroken"** idevice.

Please do let me know if I am correct or the report needs to be updated.

_MyTool_ - **xIPA** - https://github.com/m2sup3rn0va/xIPA.git

Thank you for hearing me out.
Appreciate it.

**Comment by Sjord** [comment]
[Link to text in question](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06b-Basic-Security-Testing.md#acquiring-the-app-binary)

> If you don't have the original IPA, then you need a jailbroken device where you will install the app (e.g. via App Store). Once installed, you need to extract the app binary from memory and rebuild the IPA file. Because of DRM, the file is encrypted when it is stored on the iOS device, so simply pulling the binary from the Bundle (either through SSH or Objection) will not be successful.

**Comment by m2sup3rn0va** [comment]
Thank you **Sjord** for explaining the fact but this is exactly the point I am not aligned with and that's why I have added the link of my tool which will do exactly what you are saying will not be successful **"so simply pulling the binary from the Bundle (either through SSH or Objection) will not be successful"**

Once an app is installed on a JB idevice, we can use **SSH** to extract the IPA and **process hooking** is not required. I tried the same and was successfully able to get the IPA. Not only that I was able to re-install the IPA after extracting the IPA from idevice.

The script I wrote does SSH to idevice to extract the IPA. Please have a look at the script.
 I have tested this on multiple apps including banking apps and I was able to extract the IPA and after extraction was able to re-install the app too.

**My Script** -

[xIPA - Extract IPA](https://github.com/m2sup3rn0va/xIPA.git)

**Comment by cpholguera** [comment]
Hi @m2sup3rn0va, of course you can extract the IPA and re-install it without having to decrypt anything but if your goal is to extract and reverse engineer the **app binary** you'll have to let the OS decrypt it for you and then use e.g.  Frida to extract it directly from memory.

We should anyway rework that sentence. Even if it is correct, it might be confusing. "The file" refers to the binary, not the IPA.

```
Because of DRM, the file is encrypted when it is stored on the iOS device, so simply pulling the binary from the Bundle (either through SSH or Objection) will not be successful.
```

Should be:

```
Because of DRM, the app binary file is encrypted when it is stored on the iOS device, so simply pulling it from the Bundle (either through SSH or Objection) will not be sufficient to reverse engineer it.
```
