### ISSUE TITLE
Slack join link doesn't work

### ISSUE THREAD

**Issue by b3n-j4m1n** [OWASP/owasp-mstg#1796]
The join link for Slack in the README doesn't appear to work - https://owasp-slack.herokuapp.com/

![Screen Shot 2020-07-31 at 10 09 47 am](https://user-images.githubusercontent.com/19149345/88986323-fcf65f00-d315-11ea-9429-1828133a4c19.png)

**Comment by sushi2k** [comment]
We raised it in the OWASP Slack and will come back to you once we have an answer. Thanks for raising.

**Comment by sushi2k** [comment]
@b3n-j4m1n: Please use this link for now https://owasp.slack.com/join/shared_invite/zt-g398htpy-AZ40HOM1WUOZguJKbblqkw#/
OWASP is investigating to get the old link working
