### ISSUE TITLE
Need invite for owasp slack 

### ISSUE THREAD

**Issue by mattjerry** [OWASP/owasp-mstg#1799]
Pl Share  invite  for owasp slack. All published invites don’t work

**Comment by commjoen** [comment]
Hi @mattjerry , thank you for filing an issue about the no longer working url.
If https://owasp-slack.herokuapp.com/ no longer works, then there's not much we can do ATM. We raised the issue with the community given your comment at https://github.com/OWASP/owasp-mstg/issues/877#issuecomment-666936474 . Let's close this issue and wait for the community to respond.
