### ISSUE TITLE
All links in current checklist are broken

### ISSUE THREAD

**Issue by daMatz** [OWASP/owasp-mstg#1802]
In the current checklists (e.g. [Mobile_App_Security_Checklist-English_1.2.xlsx](https://github.com/OWASP/owasp-mstg/blob/master/Checklists/Mobile_App_Security_Checklist-English_1.2.xlsx)) all the hyperlinks referenced in "Testing Procedure(s)" are broken, as they link to a base URL of `https://github.com/OWASP/owasp-mstg/blob/1.2/Document/`, which doesn't seem to exist anymore. So the webpages linked are all returning the error code 404 (e.g. `https://github.com/OWASP/owasp-mstg/blob/1.2/Document/0x04b-Mobile-App-Security-Testing.md`)

- Why is version 1.2 gone?
- Should the base URL in the checklists be adapted?
- Hint: If you have problems with this and need a fast local fix, you can change the version (1.2) in the "Dashboard" sheet of the Spreadsheet to "master"

**Comment by sushi2k** [comment]
Thanks for raising. I just fixed it. https://github.com/OWASP/owasp-mstg/pull/1803
