### ISSUE TITLE
AAB to APK

### ISSUE THREAD

**Issue by paradisperdu** [OWASP/owasp-mstg#1810]
**Platform:**
Android
**Description:**

I am testing an application which is deployed from Play store as an AAB. It stores the base.apk and several split_config.apk files within the /data/app/app folder.

If i retrieve the base.apk and install it on another device, the app will not load. I assume this is because I need the other apk files too.  If i push these apk's to the folder the app still doesn't run.

What I can't yet figure out is how to take the APKs that I have retrieved from the device, bundle them and then reinstall. 

The page https://mobile-security.gitbook.io/mobile-security-testing-guide/android-testing-guide/0x05a-platform-overview#the-app-sandbox references building apks from an aab , but i don't have that aab. 

Do you have steps that go through the process of either retrieving an aab, or bundling the individual apk files taken from the device into an apks? 

If i figure it out myself I will share this with you.

**Comment by cpholguera** [comment]
Hi @paradisperdu, did you try to revert the process? For instance, by taking the whole structure of .apk files and putting them together in an .apks file that you could the 
 handle with bundletool?

Something like this here but inverted: https://www.geekdashboard.com/extract-apk-files-from-aab/

**Comment by cpholguera** [comment]
By the way, I can highly recommend you to post these kind of questions in our Slack channel. There you have a lot of people ready to help and it's more likely to also help others that might have the same question 😊
