### ISSUE TITLE
sha256sum error 

### ISSUE THREAD

**Issue by ghenry** [OWASP/owasp-mstg#1824]
HI all,

I'm getting:

```
sha256sum Mobile_App_Security_Checklist-English_1.2.xlsx 
118fb33c94442a14aa740cd6a892001d659c0746ed00219e5ccc237a4736edc6  Mobile_App_Security_Checklist-English_1.2.xlsx
```

and the README says:

```
$ sha256sum *.xlsx
80027dca50a3be9f724c32f84117be6e961d62f2a4fa3eab5a94ac5c21ff06c8  Mobile_App_Security_Checklist-English_1.2.xlsx
```

**Comment by sushi2k** [comment]
Hi @ghenry. Thanks for pointing out this inconsistency! The hash wasn't updated in the README. To simplify, we will be removing the hashing section completely. The hashing was introduced for two reasons:

- File was downloaded properly: If the xls is not downloaded properly the file will be corrupted anyway.
- Integrity of the file: We have a single source of truth with the Github repo. If someone would have access to the repo the file hash can also be changed (of course you would see it in the commit history, but we would see this anyway also when the xls file would be updated). PR's can only be merged after approval by one of the project leads. 

Thanks again and cheers!

**Comment by ghenry** [comment]
No problem. Just enjoying your SE Radio podcast :)--
Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html
