### ISSUE TITLE
Commercial services?

### ISSUE THREAD

**Issue by ghenry** [OWASP/owasp-mstg#1833]
Hi all,

Apologies for raising this issue, but I was uncertain where to ask this. Does anyone that watches these issues provide services to do the testing on one of your apps following the guide?

Thanks,
Gavin.

**Comment by sushi2k** [comment]
Hi Gavin. We are not handling commercial requests here. Therefore I will close this issue. 

Nevertheless what might help you is CREST: https://service-selection-platform.crest-approved.org/. CREST is an organisation coming from the UK that is certifying vendors for penetration testing and red teaming. You might find a suitable vendor there that offers penetration testing services. 

Good luck and cheers!
