### ISSUE TITLE
Automation of Checklist

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1837]
**Describe the issue**
Checklists are still maintained manually, creation should be automated. 

Branches: 
- https://github.com/OWASP/owasp-masvs/tree/checklist-generation 
- https://github.com/OWASP/owasp-masvs/tree/project-integration

**Comment by cpholguera** [comment]
Closed with https://github.com/OWASP/owasp-masvs/tree/yaml-export for all languages
