### ISSUE TITLE
0x05d Refactor - Having a proper Chapter Overview

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1840]
Move the "Android KeyStore" and other sections describing "Data Storage" to the top of the chapter.  If we go though the whole chapter we can find:
  - "Local Storage" incl. Shared prefs, Databases, Internal and external storage, KeyStore.
  - Logs
  - Backups
  - Process Memory

```
## Overview
Intro to Local Storage, including mention of Logs, Backups, Process Memory.

Next, put the most relevant ones as subsections (those which have big descriptions already).

### Shared Preferences
### Databases
...
###  
```

**Comment by cpholguera** [comment]
Original issue: #1771

**Comment by Infernalbronco** [comment]
Sir, in this are we have to move the Key store subsection that is found in Static analysis section into overview section and make it a subsection(like shared preferences)?

**Comment by cpholguera** [comment]
Hi @Infernalbronco, subsections such as "####Shared Preferences" are still inside other sections (in this case "## Testing Local Storage for Sensitive Data (MSTG-STORAGE-1 and MSTG-STORAGE-2)".

They should be also moved as indicated above. This way we can have a consolidated level 2 (##) Overview section and the test cases can focus on testing and not on describing storage options.

**Comment by 0x10f2c** [comment]
So my plan for this one is to just move the sections into their new locations without modifying them (even for grammar/flow) as I presume we'll do the modification to each section in #1841 rather then double over ourselves and waste effort

Can you confirm if this is right @cpholguera, I've done an example commit in the PR

**Comment by cpholguera** [comment]
Please take a look at the comment here 😊 thanks for starting already, this will be a very nice refactoring. I like what you've already written to introduce the overview and separate concerns.

https://github.com/OWASP/owasp-mstg/pull/1849/files#r511565736

**Comment by 0x10f2c** [comment]
Awesome sounds good mate, ill try get it pushed all through this week
