### ISSUE TITLE
New 1.2 excel with new guided link, as needle is outdated,

### ISSUE THREAD

**Issue by dipti-code** [OWASP/owasp-mstg#1854]
**Platform:**
Put the platform here for which you want to see the testcase (iOS, Android, etc.)
**Description:**
Describe the type of testcase that you are missing.

Kindly provide us new 1.2 version excel sheet with the link to the latest tool as needle is outdated.

**Comment by cpholguera** [comment]
We'll be having new Excel Checklists soon, all inline with the latest MASVS and MSTG 😉
