### ISSUE TITLE
Sync releases with changelog

### ISSUE THREAD

**Issue by fam4r** [OWASP/owasp-mstg#1857]
Hello,

right now the latest version  ([1.2](https://github.com/OWASP/owasp-mstg/blob/master/CHANGELOG.md#v12---12-may-2020)) described in the `CHANGELOG.md` file is still not being released.

In fact, the latest release is [1.1.3](https://github.com/OWASP/owasp-mstg/releases/tag/1.1.3-excel).

Can you please update releases?

Thanks

**Comment by SecJoe** [comment]
In the 1.1.2 Excel (Filename) is the 1.1.3 Release (Dashboard) included. I think the filenames are incorrect??

**Comment by cpholguera** [comment]
Fixed in the 1.2 release. Regarding the excel, no need to worry, soon it will be automatically generated for all languages so there's no need to maintain it anymore.
