### ISSUE TITLE
Proposal for iOS backup

### ISSUE THREAD

**Issue by righettod** [OWASP/owasp-mstg#1879]
**Describe the issue**

I have found the following tools to work with iOS backup, do you think that it can be interesting to add it in the testing storage section when talking about backup ?

https://github.com/avibrazil/iOSbackup

Thanks a lot in advance 😃

**Comment by cpholguera** [comment]
It sounds very interesting, have you tried it out yourself? Does it work well?

**Comment by righettod** [comment]
Hi,

I used it to create the following little utility script and it work like a charm:

https://github.com/righettod/toolbox-pentest-web/blob/master/scripts/search-in-encrypted-ios-backup.py

**Comment by cpholguera** [comment]
Nice, then you could add a little entry in the Tools chapter (0x08) and in the iOS chapter with a markdown reference to the tools chapter entry. We're following this approach with all tools now to have them centralized. Let me know if you have any questions 😁

**Comment by righettod** [comment]
OK, i will do it once you have analyzed if my initial PR was acceped or rejected in order to work in sequence 😃

**Comment by cpholguera** [comment]
done, you made proceed ^^

**Comment by righettod** [comment]
OK I will do it very very very soon

**Comment by cpholguera** [comment]
big LIKE to that ;)

**Comment by righettod** [comment]
Done in PR #1880 😃
