### ISSUE TITLE
About unchecked requirements in excel checklists

### ISSUE THREAD

**Issue by fujiokayu** [OWASP/owasp-mstg#1882]
Sorry to ask a trivial question.
I noticed there are 2 requirements that are not checked(:heavy_check_mark:) in Excel checklists.
- Android / iOS V2.2
- Android / iOS V4.4

Is there any reason for this? If there is no reason, I would like to fix it.

**Comment by cpholguera** [comment]
Hi @fujiokayu,

thanks for reporting this issue! I've closed it but for a very good reason I hope you'll also like.

As you already know as of now we edit the excel file per hand, for every language. In a couple of weeks we'll introduce some code that will automatically write the contents of the checklists by parsing the MASVS in all the available languages.

This means that we keep the MASVS files as the source of truth and we'll be always up-to-date in the excel files ;)
