### ISSUE TITLE
Path of auto generated screenshots has changed (MSTG-STORAGE-9)

### ISSUE THREAD

**Issue by gl4nce** [OWASP/owasp-mstg#1889]
MSTG-STORAGE-9 states as path for saving background screenshots `/var/mobile/Containers/Data/Application/$APP_ID/Library/Caches/Snapshots/`.

Looks like it has changed or it's app related (tested on iOS 14.2). For me it's `/var/mobile/Containers/Data/Application/$APP_ID/Library/SplashBoard/Snapshots/sceneID:$APP_NAME-default/`

**Comment by Tobifrinator** [comment]
Had the same issue, the snapshot location has changed and should be updated in the guide. The directory provided by [Testing Auto-Generated Screenshots for Sensitive Information (MSTG-STORAGE-9) #Dynamic Analysis](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06d-Testing-Data-Storage.md#dynamic-analysis-7) does not exist anymore. My test device is an iPhone SE with iOS 14.6.

**Comment by cpholguera** [comment]
Thanks for sharing your results @Tobifrinator, this is always very helpful for us. Please keep it coming and always that you feel like it gladly open a PR. That usually speeds up the process and gives you contribution points 😉.
