### ISSUE TITLE
Duplicate CWE and OWASP Top 10 References

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#19]
Hi guys, we have CWE and Top 10 references in both OWASP-DATAST and OWASP-DATAST-Android sections. Can we keep these in the generic section only to avoid redundancies.

**Comment by sushi2k** [comment]
Sure. Deleted it already in the template. 

https://github.com/OWASP/owasp-mstg/commit/eb790472b7a8f62959921d1740a22f79768231e1

**Comment by sushi2k** [comment]
Cleaned it. All references are now in the main section. 

https://github.com/OWASP/owasp-mstg/commit/8cc0b7e8ab7f332452b22d51a6b1c2195598edc9
