### ISSUE TITLE
IDA Pro decompiler (Hex Ray) is solving Uncrackable-Level 2

### ISSUE THREAD

**Issue by wahibimoh** [OWASP/owasp-mstg#1929]
Hi, 
I am not sure if the binaries for armv7 are optimized too much or if Hex Ray decompiler, v7.5, is better than I expected. But when I used the decompiler on libfoo.so from armeabi-v7a the solution is in plain text:
 
![image](https://user-images.githubusercontent.com/2051325/126253181-9ce9a58c-4368-4786-83f9-6f2eba718c73.png)

Here is what I get Ghidar:
![image](https://user-images.githubusercontent.com/2051325/126253237-8952cb79-449b-42a7-8bab-e55e20a34678.png)

**Comment by cpholguera** [comment]
Hi @wahibimoh, thanks for your message :) The solution string is indeed inside the code so it might be very possible that IDA was able to resolve it using techniques such as symbolic execution.

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#symbolic-execution
