### ISSUE TITLE
0x5d - Don't understand statement 'are outta there'

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#193]
In line 454, the current sentence reads 'Many major versions of the Android operating system are still actively used and are outta there.'. What does 'are outta there' mean? Is it to express the idea that this kind of vulnerability are still part of many Android versions? Or does it have any other meaning?

**Comment by sushi2k** [comment]
Hi @romualdszkudlarek. This means that there are still Android devices out there from version 2.X to 7.x that are actively used by end users and that it might be hard to deactivate the clipboard for all those versions and the forks of Android from different vendors where different UI changes were done. 

I just deleted this part, as it's anyway expressed already in the sentence. 

See the commit
https://github.com/OWASP/owasp-mstg/commit/87cd9227d4061a45673e7614e2af2fe89940c55e
