### ISSUE TITLE
[iOS] SecKeyEncrypt has been deprecated

### ISSUE THREAD

**Issue by fujiokayu** [OWASP/owasp-mstg#1965]
[SecKeyEncrypt](https://developer.apple.com/documentation/security/1617956-seckeyencrypt) has been deprecated in iOS SDK 15.
- [Security iOS 14.5 to 15.0 API Differences](http://codeworkshop.net/objc-diff/sdkdiffs/ios/15.0/Security.html)

MSTG does not mention this API in any depth, and SecKey itself is not deprecated.
So, I would like to just fix the following one place.
What do you think of this ?

- [0x06e-Testing-Cryptography.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06e-Testing-Cryptography.md)

```diff
- #### CommonCrypto, SecKeyEncrypt and Wrapper libraries
+ #### CommonCrypto, SecKey and Wrapper libraries
```

**Comment by cpholguera** [comment]
Hi @fujiokayu, nicely spotted! Would you mind opening a PR with the fix for that title? 🙏

I think that a bit down below in that section we refer to `SecKey` using the correct links. If you find any inconsistencies, could you please include them in the same PR? Let us know if you have any questions, thanks a lot!

> Tip: for a one line edit you can do it directly in GitHub by going to the file and clicking on "Edit file".
>
> Alternatively you can [navigate to the file and press "."](https://twitter.com/github/status/1425505817827151872?t=IKc3a2GzeF3f9W1RLbzKoA&s=19), you'll be presented with an online vscode where you can do and commit your changes and even open a PR from there.

**Comment by fujiokayu** [comment]
@cpholguera Thank you for checking this, and sorry for the delay in noticing.
I will send PR soon.
