### ISSUE TITLE
💲🎉 New Donation

### ISSUE THREAD

**Issue by brian-nowsecure** [OWASP/owasp-mstg#2020]
### 🙂 Your Name

Brian Reed

### 🏢 Company Name

NowSecure

### 📧 E-Mail Address

breed@nowsecure.com

### 💵 Donation Amount

4000.00

### 📦 Donation Package

God Mode Donator (USD 4000 / 5 Available; 3 years; 5 paperback MSTGs)

### 📘 MSTG Paperback Copies

🌱 No, please save the money for the project and help the environment and climate.

### 📋 Code of Conduct and Donation Conditions

- [X] I agree to follow this project's Code of Conduct and Donation conditions.

**Comment by cpholguera** [comment]
Open PRs (waiting for verification and approval):

- https://github.com/OWASP/owasp-masvs/pull/613
- https://github.com/OWASP/owasp-mstg/pull/2021
- https://github.com/OWASP/www-project-mobile-security-testing-guide/pull/66
