### ISSUE TITLE
0x03 Mobile Application Threats

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#207]
Section lacks content. Add description of the OWASP Top 10, and how it maps to the MASVS / MSTG.

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x03-Overview.md#mobile-application-threats

**Comment by sushi2k** [comment]
This section: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x03-Overview.md#mobile-application-threats

I can draft something till end of the month

**Comment by EhsanMashhadi** [comment]
Test comment for pull requesting

**Comment by b-mueller** [comment]
Probably better to replace the Mobile Top Ten with the MASVS vulnerability categories.

**Comment by seamustuohy** [comment]
[NIST's Mobile Threat Catalogue](https://pages.nist.gov/mobile-threat-catalogue/) has a solid enumeration of various threats on a variety of different levels of the mobile ecosystem. It might be a useful resource to at least link out to while you are developing a more robust section here.

**Comment by b-mueller** [comment]
@seamustuohy that's an awesome resource, thanks.

**Comment by sushi2k** [comment]
Hi @defern. Do you still have time to create this content?
