### ISSUE TITLE
Using the OWASP Mobile Security Testing Guide

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#208]
Migrate content from our blog article:

http://www.vantagepoint.sg/blog/84-verifying-mobile-app-security-using-the-owasp-checklist

To this section:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x03-Overview.md#using-the-owasp-mobile-security-testing-guide

**Comment by sushi2k** [comment]
I will make a draft next week.

**Comment by b-mueller** [comment]
@sushi2k I think this chapter needs some more work before moving to "review". Some of the content potentially be moved to "Mobile App Security Testing Methodology" depending on what Johannes and Florian come up with. What do you think?

**Comment by sushi2k** [comment]
I was moving this issue to review, as the section "Using the OWASP Mobile Security Testing Guide" is now done with a first draft. The whole chapter is not fully done yet, you are right, as the mobile threats are missing. But this is covered in another issue. So the work done on this issue can still be reviewed, right?

**Comment by b-mueller** [comment]
alright, I'll have a look at it.

**Comment by b-mueller** [comment]
I reviewed this and moved some of the content to 0x04 - Testing processes.
