### ISSUE TITLE
Mobile Security Testing - High Level Methodology

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#209]
This section lacks content.

Florian and Johannes, the authors of [this presentation](https://www.owasp.org/images/0/04/Security_Testing_Guidelines_for_mobile_Apps_-_Florian_Stahl%2BJohannes_Stroeher.pdf), have agreed to port the content to the MSTG (need to follow up with them).

**Comment by sushi2k** [comment]
Hi @defern. Can you please let me know if you have time to take care of this ticket?

**Comment by defern** [comment]
I cannot.I am sorry, for not getting back with you earlier.Thank you for the opportunity, but I am sorry I let you down. Thanks,David 

    On Thursday, June 29, 2017 10:24 PM, Sven <notifications@github.com> wrote:
 

 Hi @defern. Can you please let me know if you have time to take care of this ticket?—

**Comment by sushi2k** [comment]
No worries, thanks for coming back to us.
