### ISSUE TITLE
Misinformation

### ISSUE THREAD

**Issue by bimsec** [OWASP/owasp-mstg#2099]
Corellium is the only publicly available iOS emulator. It is an enterprise SaaS solution with a per user license model and does not offer any trial license. => this is no longer true, Correlium does offer trial licenses. Important sidenote, you will need an IPA file that has been signed with your own developer certificate in order to be able to install on Corellium devices. 

This is for 0x06b-Basic-Security-Testing.md in the Testing on an Emulator section.

**Comment by cpholguera** [comment]
Hi @bimsec, do you have a reference link pointing to that information?

Would you mind opening a PR with your correction, that'd be very helpful. Thank you in advance.
