### ISSUE TITLE
[REVIEW NEEDED] 0x5c - Android - Frida Tutorial

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#210]
Show how to set up Frida and demonstrate core functionality.

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#user-content-dynamic-instrumentation-with-frida

**Comment by mhelwig** [comment]
Added some basic usage examples. Please check:
https://github.com/OWASP/owasp-mstg/pull/237
I am going to add more on solving the crackme within the next days.
