### ISSUE TITLE
Out of date info

### ISSUE THREAD

**Issue by bimsec** [OWASP/owasp-mstg#2100]
[Passionfruit](https://github.com/chaitin/passionfruit): an iOS app blackbox assessment tool. It's no longer Passionfruit but it is now called Grapefruit. (https://github.com/chichou/grapefruit). 

Found in 0x08-Testing-Tools.md#frida

**Comment by cpholguera** [comment]
Hi @bimsec, we already have an issue for that. See https://github.com/OWASP/owasp-mstg/issues/1924

This would imply updating all occurrences and examples of passionfruit. Would you mind opening a PR with an update? That'd be a huge help for us right now.

If you have any questions or need help getting started please let us know. Thank you very much!
