### ISSUE TITLE
[iOS] Add information on enabling Safari Web Inspector on iOS

### ISSUE THREAD

**Issue by lndevel** [OWASP/owasp-mstg#2111]
In  *Testing iOS WebViews (MSTG-PLATFORM-5)* the guide provides information on testing web views.

Turning on Safari developer tools results in a great  information resource on web view contents. 
Additionally, it allows for better vetting of hybrid applications, as the contents of the mobile application's web views can be inspected directly on a Mac.

We suggest adding information on enabling the web inspector on iOS either in the iOS fundamentals or in *Testing iOS WebViews (MSTG-PLATFORM-5)* .

To enable the inspector the following steps have to be done:
1. Open Settings on iOS device: Go to **Safari->Advanced**, enable Web Inspector
2. Open Application under test
3. Open Safari on a Mac that is conected to the iOS device: The iOS device should appear in the **Developer** toolbar entry. The web inspector can be opened for the Application in this submenu.

We tested this on a jailbroken iPhone running iOS 14.3 with several applications that use web views.

References:
*  (Apple Documentation)[https://developer.apple.com/library/archive/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html]

**Comment by cpholguera** [comment]
Hi @lndevel, that's a great improvement. Would you mind opening a PR with your proposal? Thanks a lot in advance!

**Comment by lndevel** [comment]
Hi. I created a PR with a short description on enabling the web inspector. I hope the location is appropriate. If you want the section to be more detailed, just let me know.

**Comment by cpholguera** [comment]
Thanks a lot @lndevel, we'll take a look at it soon!
