### ISSUE TITLE
💲🎉 New Donation

### ISSUE THREAD

**Issue by vadimszzz** [OWASP/owasp-mstg#2115]
### 🙂 Your Name

Vadim Yegorov

### 🏢 Company Name

Vadim Yegorov. I don't own a company. Would be nice to see my name \\^^/

### 📧 E-Mail Address

vadimszzz@airmail.cc

### 💵 Donation Amount

4000 USD

### 📦 Donation Package

God Mode Donator (USD 4000 / 5 Available; 3 years; 5 paperback MSTGs)

### 📘 MSTG Paperback Copies

📮 Yes, please send them to me.

### 📋 Code of Conduct and Donation Conditions

- [X] I agree to follow this project's Code of Conduct and Donation conditions.

**Comment by cpholguera** [comment]
Hi @vadimszzz, this is awesome, thank you very much for your support! We've contacted you per email regarding the next steps. We'll be happy to coordinate that as well as your upcoming content contributions which we're very much looking forward to. Have a great Sunday!

**Comment by sushi2k** [comment]
Hi Anna, 

we are sorry to hear that, but to clarify a few things:

- We never got this money, OWASP confirmed with us
- The only communication that did happen was this ticket when it was opened, without any follow-up from him. 
- We never got any response or were in active contact with him, even after following up with him directly.

We are happy to help if there is any way, but no money was being transferred to OWASP. As of now we would close this ticket as the donation was not transferred. 

Thanks,

Sven and Carlos

**Comment by vadimszzz** [comment]
Who is Felicia Kay Burt?

**Comment by ghost109264829** [comment]
> He is not adhering to the code of conduct. This is the person he is harassing. I am his ex girlfriend. He is stealing from me. [livmalo@yahoo.com](mailto:livmalo@yahoo.com) and he is using my email [annalynn308@gmail.com](mailto:annalynn308@gmail.com).
> Please stop him.
> I develop for Apple and Meta and know what he is doing is wrong and infringes upon my rights.
> Sincerely,
> Felicia Kay Burt

Hi Felicia Kay Burt (Anna Lynn),
I can confirm that I’m not familiar with your name and we are not related to this situation, for your knowledge funds have not been sent to any party, OWASP Foundation never received the donation.
Please contact your local authorities for help regarding your impersonation and fraud. Also I suggest you to change your password.
