### ISSUE TITLE
New Chapter for Reference Apps

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#2142]
Rename 0x08-Testing-Tools.md to 0x08a-Testing-Tools.md and fix all related links in the MSTG.

Create a new chapter for ["Vulnerable applications"](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x08-Testing-Tools.md#vulnerable-applications): 0x08b-Reference-Apps.md

Each entry should have own markdown headers:

```
# Reference Applications

The applications listed below can be used as training materials. Note: only the MSTG apps and Crackmes are tested and maintained by the MSTG project.

## Android

### Crackmes
...
### AndroGoat
...

## iOS
...
### DVIA-v2
```

Ensure that the headers are unique, e.g. `### Crackmes` should be `### Android Crackmes` and `### iOS Crackmes`.

Search for all references in the MSTG and link back to this chapter. For example:

```md
Let's look at bypassing jailbreak detection using the Damn Vulnerable iOS application as an example again. 
```

should be:

```md
Let's look at bypassing jailbreak detection using the [Damn Vulnerable iOS application](0x08b-Reference-Apps.md#dvia-v2) as an example again. 
```

**Comment by wwwhackcom** [comment]
Thanks @cpholguera, I am happy to start with this "create a new chapter 0x08b".

**Comment by cpholguera** [comment]
It's now assigned to you. See how to contribute https://github.com/OWASP/owasp-mstg/blob/master/docs/contributing/2_Getting_Started.md#contribute-offline

And here more info about opening your first PR and the review process: https://github.com/OWASP/owasp-mstg/blob/master/docs/contributing/3_PRs_and_Reviews.md

Thanks!
