### ISSUE TITLE
[Tool] APKLab

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#2158]
Evaluate for inclusion:

https://github.com/Surendrajat/APKLab/

**Comment by fujiokayu** [comment]
@cpholguera 

Thanks for sharing good tool.

Installation was very easy. And i tried decompile, MITM Patch, and rebuild by this tool.
It looks good for me.

**Comment by cpholguera** [comment]
Hey @fujiokayu, that's great. Thanks for taking the time to test it. Would you like to add a short entry to the Testing Tools chapter ...

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x08a-Testing-Tools.md 


and in here ...?

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#decompiling-java-code

**Comment by fujiokayu** [comment]
Thanks @cpholguera for specifying the chapters.
I'll send you a PR in a few weeks.

**Comment by cpholguera** [comment]
Thank you very much!
