### ISSUE TITLE
[Bug] Landscape change, claim might not hold anymore

### ISSUE THREAD

**Issue by t3chn0m4g3** [OWASP/owasp-mstg#2163]
### MSTG Chapter

MSTG-RESILIENCE-5, line 638

### File Line Number

638 (0x06j-Testing-Resiliency-Against-Reverse-Engineering.md)

### Context

At the moment R5 on iOS claims, that emulation detection is no concern on iOS since the only known emulator is XCode. However there are offerings i.e. by Corellium (https://www.corellium.com/) offering iOS emulation even jailbroken and large scale. It is probably advisable to adjust this chapter accordingly.

**Comment by t3chn0m4g3** [comment]
@cpholguera Of course, but it will need review and testing.

**Comment by cpholguera** [comment]
That's great, please take your time. We'll review your PR of course 👍 Thank you very much!

**Comment by t3chn0m4g3** [comment]
PR created with #2167
