### ISSUE TITLE
0x5a - Author new content on vulnerabilities that can be created while using IPC mechanisms [Android]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#251]

**Comment by romualdszkudlarek** [comment]
Look for -- TODO [Explain what vulnerabilities can be created while using IPC mechanisms. Give short examples in the form of code snippets] --

**Comment by clviper** [comment]
@romualdszkudlarek please assign this issue to me. Thanks.

**Comment by b-mueller** [comment]
@clviper I added you as a collaborator, please visit this link:

https://github.com/OWASP/owasp-mstg/invitations

**Comment by b-mueller** [comment]
FYI, Android IPC is already discussed in several places:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05a-Platform-Overview.md#user-content-how-apps-communicate---android-ipc

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#user-content-testing-whether-sensitive-data-is-exposed-via-ipc-mechanisms

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05h-Testing-Platform-Interaction.md#user-content-testing-for-sensitive-functionality-exposure-through-ipc

@clviper not sure what still needs to be done here but this needs to be restructured and cleaned up. I also added others to this topic that contributed on IPC.

**Comment by clviper** [comment]
@b-mueller @sushi2k sorry guys, have not been able to dedicate the time this deserves :( What still needs to be done is show examples of vulnerabilities that can be created with different components and how can we fix those vulnerabilities. I already have the code created for each vulnerability and started writing the text for this.

**Comment by sushi2k** [comment]
Thanks for the @clviper. Looking forward for your Pull Request :-)
