### ISSUE TITLE
0x5b - Add link to Testing Custom Certificate Stores and SSL Pinning

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#253]

**Comment by romualdszkudlarek** [comment]
Look for See also test case "Testing Custom Certificate Stores and SSL Pinning" (-- TODO [add_link] --) for further details.

**Comment by joebowbeer** [comment]
This reference-missing-a-link is (also) here:

[Testing Network Communication](https://b-mueller.gitbooks.io/the-owasp-mobile-security-testing-guide/content/0x04f-Testing-Network-Communication.html)

> In such a scenario, please check "Testing Custom Certificate Stores and SSL Pinning". 

Where is this section in the book?
