### ISSUE TITLE
[UNDER REVIEW] 0x5c - Android - Command line JDB intro

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#262]
Read it here: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#user-content-debugging-and-tracing

**Comment by romualdszkudlarek** [comment]
Look for -- TODO [Command line JDB intro] --

**Comment by b-mueller** [comment]
Section ready for review: 

Read it here: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#user-content-debugging-and-tracing

(everything up to native debugging)

**Comment by anantshri** [comment]
as mentioned on the other comment
"Note: If you experience JRE compatibility issues with apksigner, you can use jarsigner instead:"
we need to specify that zipaligner would be required after jar signer not before.

not checked from https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md#debugging-using-an-ide as todo markers found.
