### ISSUE TITLE
0x5e - Develop existing content on Test Case Verifying Key Management [Android]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#277]

**Comment by commjoen** [comment]
There are a bunch of issues with the key management in Android:

- Byte-arrays for the Java Key are not cleaned after operations, one should create a wrapper which implements Destroyable and clears up the key
- The Bounceycastle working key for AES is not cleared
- The keys might not be in the secure hardware (so one should always check). Please check the fingerprint authentication for more details.
- People should not use certain keystores
-etc...
