### ISSUE TITLE
[REVIEW NEEDED] 0x5f - Test Case Testing Session Management [Android]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#281]
See here:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05f-Testing-Authentication.md#user-content-testing-session-management

**Comment by b-mueller** [comment]
See here:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05f-Testing-Authentication.md#user-content-testing-device-binding
