### ISSUE TITLE
[UNDER REVIEW] 0x5i - Verifying That the App is Properly Signed [Android]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#300]

**Comment by anantshri** [comment]
Review comment: please use apksigner as that's the prefered method by google for this now. https://developer.android.com/studio/command-line/apksigner.html

also note apksigner signs the whole apk hence the older process of jarsigner and the zipalign is now inverse we need to do zipalign first and then apksigner for verification purposes nothing changes apksigner verify is what we use as outlined on above page.

**Comment by b-mueller** [comment]
@anantshri good input, thanks

**Comment by b-mueller** [comment]
@anantshri I made some updates to the test case, and add more detailed description of the available app signing schemes to the platform overview chapter:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05a-Platform-Overview.md#user-content-apk-signing-schemes

Please have a look.

**Comment by anantshri** [comment]
looks a lot better now. I am happy to call it reviewed.

just one nuance, should we be adding a one liner about zipalign?

**Comment by b-mueller** [comment]
I added some info on zipalign to 0x05a.
