### ISSUE TITLE
0x5j - Develop existing content on Test Case Testing Anti-Debugging [Android]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#308]

**Comment by b-mueller** [comment]
Looking for someone here who solved UnCrackable App for Android Level 2, and bypassed anti-debugging in the process. Can be used as a how-to for this test case. @ryantzj @mhelwig

**Comment by mhelwig** [comment]
I solved it using Frida, but my solution mostly ignores the anti debugging stuff and just injects Frida early into the process. I'm going to writeup this solution in the next days.
