### ISSUE TITLE
[REVIEW NEEDED] 0x5j - Testing File Integrity Checks [Android]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#309]
See here:
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#user-content-testing-file-integrity-checks

**Comment by b-mueller** [comment]
Section ready for review:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#user-content-testing-file-integrity-checks

**Comment by commjoen** [comment]
I will address this a bit soon :)

**Comment by commjoen** [comment]
See https://github.com/OWASP/owasp-mstg/pull/519 which provides an update
