### ISSUE TITLE
0x5j - Author new content on Test Case Testing Device Binding [Android]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#313]

**Comment by romualdszkudlarek** [comment]
Assigned to Jeroen Willemsen

**Comment by b-mueller** [comment]
@commjoen are you still going to write this? Will do it myself otherwise.

**Comment by b-mueller** [comment]
@commjoen ?

**Comment by commjoen** [comment]
Sorry for not responding that quick, I have started to work on it again today, hope to finish it during appsec.

**Comment by commjoen** [comment]
Please find a PR at https://github.com/OWASP/owasp-mstg/pull/449
