### ISSUE TITLE
0x6e - Author new content on Test Case Testing Random Number Generation [iOS]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#357]
See here:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06e-Testing-Cryptography.md#user-content-testing-random-number-generation

**Comment by sushi2k** [comment]
Any update on this @kongwenbin? Dynamic Analysis is missing for this test case. Have a look at the Android Test Case, so that the test cases are also aligned.
