### ISSUE TITLE
0x6h - Author new content on Test Case Testing for Sensitive Functionality Exposed Through IPC [iOS]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#376]

**Comment by sushi2k** [comment]
Available mechanisms:

http://ddeville.me/2015/02/interprocess-communication-on-ios-with-mach-messages
http://ddeville.me/2015/02/interprocess-communication-on-ios-with-berkeley-sockets
http://nshipster.com/inter-process-communication/
