### ISSUE TITLE
[REVIEW NEEDED] 0x6h - Test Case Testing JavaScript Execution in WebViews [iOS]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#377]
See here:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06h-Testing-Platform-Interaction.md#user-content-testing-javascript-execution-in-webviews

**Comment by b-mueller** [comment]
See here: 

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06h-Testing-Platform-Interaction.md#user-content-testing-javascript-execution-in-webviews
