### ISSUE TITLE
0x6h - Author new content on Test Case Testing WebView Protocol Handlers [iOS]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#378]

**Comment by sushi2k** [comment]
Hi @xep624. Any update on this or can you share a timeline when you think you can commit a draft?

**Comment by sushi2k** [comment]
Hi @xep624. Any update on this or can you share a timeline when you think you can commit a draft?

**Comment by xep624** [comment]
Sorry for such big delay. However, I've just committed a PR: https://github.com/OWASP/owasp-mstg/pull/608
