### ISSUE TITLE
0x6h - Author new content on Test Case Testing for Local File Inclusion in WebViews [iOS]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#379]

**Comment by sushi2k** [comment]
Hi @xep624. Any update on this or can you share a timeline when you think you can commit a draft?

**Comment by xep624** [comment]
Yup, I'll finish it but need more time (around 2-3 weeks). Hope that's not a problem

**Comment by sushi2k** [comment]
No problem at all. Thanks for the feedback.
