### ISSUE TITLE
[Proofreading] 0x6j - Test Case: Testing Device Binding [iOS]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#396]

**Comment by pmilosev** [comment]
I've done a quick review and added inline comments to the last commit.

**Comment by b-mueller** [comment]
I'm getting confused with those tickets. This one refers to iOS device binding, but there's no content for that yet. @commjoen are you currently working on that?

@pmilosev you probably mean the Android device binding one?

Let's please add links to what we wrote to the tickets before putting them into the "ready for review" column.

This ticket refers to:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#user-content-testing-device-binding

**Comment by pmilosev** [comment]
@b-mueller I only looked to the things added with the last commit 5722b4f.
The text looks pretty iOS to me :)
E.g. it mentions APIs like [UIDevice currentDevice] which is an iOS API.

The link that you proved in the comment above points to master.
The commit I commented on is on branch 0x6j/device_binding_iOS

**Comment by commjoen** [comment]
I am working on that yes...

Sent from a mobile device with autocomplete.

Op 20 mei 2017 08:24 schreef "Bernhard Mueller" <notifications@github.com>:

**Comment by commjoen** [comment]
Btw: the content is being created as you can see. I will finish it during the summit.

**Comment by commjoen** [comment]
Please find my first PR at https://github.com/OWASP/owasp-mstg/pull/508
