### ISSUE TITLE
0x4d - Complete the Secure SDLC and DevSecOps chapter

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#402]
See here:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04-Testing-Processes-and-Techniques.md#user-content-security-testing-in-the-software-development-life-cycle

**Comment by b-mueller** [comment]
I made this issue a bit more generic, as this chapter still didn't have a final ToC.

**Comment by b-mueller** [comment]
This section has been moved:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04-Testing-Processes-and-Techniques.md#user-content-security-testing-in-the-software-development-life-cycle

@romualdszkudlarek @streichsbaer please complete this section.
