### ISSUE TITLE
iOS code examples: Obj-C or Swift

### ISSUE THREAD

**Issue by abjurato** [OWASP/owasp-mstg#427]
Could not find any info regarding whether iOS code examples should be in Obj-C or Swift. 
So far I've seen only Obj-C examples. As for me whole community moves towards Swift last couple of years, but it has downside in frequent updates and code-breaking features. On the other hand, this book will should be focused on today's juniors, who are starting with Swift and are terrified by Obj-C verbosity.

So, maybe let's provide examples in both languages?

**Comment by b-mueller** [comment]
@abjurato I think we need to cover both.
