### ISSUE TITLE
consider using git lfs for binaries/large files

### ISSUE THREAD

**Issue by dweinstein** [OWASP/owasp-mstg#429]
this will reduce the size of cloning the repo while allowing those who want the binaries to do so. see https://git-lfs.github.com/ for more.

**Comment by b-mueller** [comment]
thanks for the input, i'll check it out.

**Comment by b-mueller** [comment]
I moved app packages and images to LFS. unfortunately, Gitbook.com is not compatible with LFS, so the images don't sync. Will have to find a way to untrack them again :/

**Comment by b-mueller** [comment]
Alright, fixed by re-adding the images as normal files. APKs and IPAs still tracked in LFS, which is a good compromise. Closing this issue.

**Comment by dweinstein** [comment]
@b-mueller I was reading up a bit more on it and there is potentially another downside to git-lfs that I hadn't quite paid close enough attention to before making the suggestion to use it for this project. I wanted to make you aware and sorry for not checking it sooner. 

The default bandwidth/storage for LFS files is only 1GB per month for their free tier! This seems very low, and kind of insane given that using LFS seems better for github's servers... Data packs can be added in increments of $5 per 50GB/mo.

I'm not sure if this project is accepting donations, but that might be one way to offset this if/when it becomes a problem. FWIW I believe that including all the large files in the git repo history itself would have been detrimental to the project over time, so seems like something we'd have to address eventually.
