### ISSUE TITLE
0x6d Test Case: Testing for Sensitive Data in Memory on iOS

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#430]

**Comment by pmilosev** [comment]
What needs to be done regarding this issue ?
I can already see a section named "Testing for Sensitive Data in Memory" under "Testing Data Storage".

**Comment by b-mueller** [comment]
Link: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06d-Testing-Data-Storage.md#user-content-testing-for-sensitive-data-in-memory

**Comment by b-mueller** [comment]
I think your comments referring to the Android version of this test case:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#user-content-testing-for-sensitive-data-in-memory

I agree that the recommendation need to be improved. 

1. AFAIK, it is possible to use byte arrays, the content of which can be referenced directly. However, I'm not sure if this is consistently safe for all Android runtimes.

2. The points about mutable objects & speeding up garbage collection should be added as well.

3. There should also be a recommendation to implement critical operations natively if it can't be done safely in Java.

@pmilosev can you help to improve this chapter?

**Comment by pmilosev** [comment]
@b-mueller Yes, I referred to Android. 
You can assign the ticket to me.

Please feel free to correct me on anything you see as potentially unsafe or something.

**Comment by sushi2k** [comment]
@pmilsoev As this is the iOS ticket, I just assigned you this ticket: https://github.com/OWASP/owasp-mstg/issues/478

This one is linked to memory testing of Android. Please create a PR with your changes. Thanks for your help.

**Comment by pmilosev** [comment]
Sure, just note that it will take me few weeks before I implement this.
As commented already on another ticket, I'll be going trough the existing content by end of next week, before start adding any new content. I already have a ticket for proof reading one chapter - this will be done in the next several days.
