### ISSUE TITLE
Chapter "Testing Data Storage" in the wrong location.

### ISSUE THREAD

**Issue by clviper** [OWASP/owasp-mstg#44]
This chapter is located in /Document/Testcases/0x00_OMTG-DATAST.md From what I understood it should be placed in the root of the /Document folder.

**Comment by clviper** [comment]
And the name itself should be rename to the right format.

**Comment by sushi2k** [comment]
Hi clviper,

can you please elaborate what you mean that it is in the wrong location? This repo is not really for reading the final document, at the moment you can create a docx or html out of the markdown by a shell script  (https://github.com/OWASP/owasp-mstg/blob/master/generate_document.sh). This will be the deliverable. 

We were also already thinking about merging to Gitbooks, to make it easier but this is work in progress. 

What is wrong with the name of testing data storage?

Cheers,

Sven

**Comment by clviper** [comment]
Hi @sushi2k. When reading the index (https://github.com/OWASP/owasp-mstg/blob/master/README.md) all the chapter .md files are located in the /document root folder except Testing Data Storage that is located in the /Document/Testcases/. Looking at the index, all the chapters .md file names are in the format of 0x<id>-NAME.md. This chapter because is stored in a different folder has a completly differente name (0x00_OMTG-DATAST.md)

**Comment by clviper** [comment]
Going to close this, already talked in Slack regarding this issue.
