### ISSUE TITLE
[EDITING] Chapter "Testing Data Storage on Android"

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#467]
See here:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md

**Comment by pmilosev** [comment]
I'm starting the review.

**Comment by b-mueller** [comment]
Thanks for the review so far. I added some more changes.

Still, I think that large parts of this chapter need to be rewritten due to grammar errors and style issues. IMHO we need to get someone with good English & writing skills to completely overhaul it.

**Comment by sushi2k** [comment]
@pmilosev Any update on this or any timeline when you might be able to review? Thanks

**Comment by pmilosev** [comment]
I should be able to finish the review next week.

**Comment by sushi2k** [comment]
Great. There were a lot of updates in the guide during the OWASP Summit, so also do a pull request first ;-)

**Comment by pmilosev** [comment]
I finished the review.
I agree with @b-mueller that this chapter needs some better wording.
Other than that the content looks OK.
I just added a small hint on potential issues when stripping logs with ProGuard - see the PR above.

**Comment by pmilosev** [comment]
p.s. I personally (as a user of a mobile device) didn't like the idea of the mobile app gaining admin rights to check if proper security is ensured by the user (e.g. if strong device password is set, etc.).
Personal freedom (privacy, freedom of choice, etc.) is already secondary to security for many application providers (and some are even using security only as an excuse). I'm afraid that having OWASP suggest that it's OK to get some freedom out of the hands of the user may be badly misunderstood / misused by many.
I'm well aware of why this requirement is there, but I would rather be quite careful with the wording :)

**Comment by pmilosev** [comment]
@b-mueller, is there something I should do about this ticket, as I finished the review ?
