### ISSUE TITLE
images are not loading in doc

### ISSUE THREAD

**Issue by dineshdinz** [OWASP/owasp-mstg#468]
when generating document from tools folder using pandoc, the generated document has missing images, please check with that..

**Comment by b-mueller** [comment]
Hi @dineshdinz, it works for me without errors. What images are missing exactly?

**Comment by dineshdinz** [comment]
All images are not loading in the document, and I have noticed that when I download the zip file all the images which are in the Document folder are crashed and shows can't able to open in mac.

**Comment by b-mueller** [comment]
That's weird! Do you have Git-LFS installed?
If not, please try to install it according to the [instructions here](https://git-lfs.github.com) and try again. 
Anyway, strange as the images shouldn't be tracked by LFS, I'll investigate.

**Comment by dineshdinz** [comment]
ok, Thanks for the help... 👍

**Comment by b-mueller** [comment]
I deactivated git-lfs completely and re-added all files the normal way. If you git pull now everything should work?

**Comment by dineshdinz** [comment]
Now it works perfectly

**Comment by b-mueller** [comment]
Awesome! Closing this issue then.
