### ISSUE TITLE
[REVIEW NEEDED] 0x04 - Types of Mobile Apps

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#477]

**Comment by b-mueller** [comment]
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04-Testing-Processes-and-Techniques.md#user-content-different-types-of-mobile-apps

This section has some grammar issues that need fixing.

**Comment by sushi2k** [comment]
Now covered in Mobile Taxonomy https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04a-Mobile-App-Taxonomy.md
