### ISSUE TITLE
0x5d Test Case: Update Testing for Sensitive Data in Memory on Android

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#478]
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#testing-for-sensitive-data-in-memory

**Comment by sushi2k** [comment]
Hi @pmilosev. Any update for this test case?

**Comment by Naushad007** [comment]
Testing for Sensitive Data in Local Storage...SQLite Databases

**Comment by commjoen** [comment]
@Naushad007 is that not more on sensitive data in storage? Because on storage you would need to test for:
- SQLite
- SQLCipher 
- Realm
- Plists
- NSUserDefaults
...and gimme some more ;-)

**Comment by Naushad007** [comment]
Thanks @commjoen I will follow up that streem

**Comment by sushi2k** [comment]
Hi @Naushad007. This issue is about sensitive data exposed in the memory, not the file system. 

Do you want to work on this ticket? If so, please create a PR and I can assign the ticket also to you. I think @pmilosev is still busy at the moment and couldn't find time to update the test case.

**Comment by pmilosev** [comment]
Sorry, few escalations at work and the plan goes out of window.
I'm on a vacation in the next few weeks, so I'll try to do at least some contribution, but let's not promise much.
I still have this project on my agenda though ;)

**Comment by sushi2k** [comment]
Noted and understand. Just wanted to ping you :-)

**Comment by pmilosev** [comment]
I've started reviewing and editing this chapter.

**Comment by pmilosev** [comment]
done, check the linked pull request #675
