### ISSUE TITLE
0x06g Testing Network Communication - Add App Transport Security

### ISSUE THREAD

**Issue by dharshin** [OWASP/owasp-mstg#480]
Add App transport security (Ref: https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

**Comment by dharshin** [comment]
Please assign this to me and I can complete this

**Comment by b-mueller** [comment]
@dharshin is it completed?

**Comment by dharshin** [comment]
@b-mueller not yet. I'll finish it by end of this week.

**Comment by sushi2k** [comment]
Hi @dharshin. Is the test case ready from your site?
