### ISSUE TITLE
[DONE] 0x05c Tampering and Reverse Engineering on Android

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#491]
See here:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05c-Reverse-Engineering-and-Tampering.md

Tasks:

- Check and improve the chapter structure
- Proofreading & consistency
- Make sure examples are working
- Link all examples to existing demo apps so they can be reproduced
- Update Kernel module howto to Android 7

**Comment by eclipse95** [comment]
Hello,
As [Panda (1.0)](https://github.com/moyix/panda) is deprecated, it could be interesting to update this part with [Panda 2](https://github.com/panda-re/panda).
I haven't tested Panda 2 yet.

**Comment by b-mueller** [comment]
Good to know, thanks. Would you like to update it? :)

**Comment by eclipse95** [comment]
Hello,
I will try to test Panda 2, check functionalities and make the update if needed.

**Comment by eclipse95** [comment]
Hello,
Panda 2 has dropped "official" support for Android. It might stay possible to make working Android virtual device manually, but it would be painful and time consuming. I tried to do it but I experienced several problems for now.

So, I suggest to keep Panda 1 even if it's deprecated.
