### ISSUE TITLE
0x07e ARM Assembly tutorial

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#493]
See here:
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x07e-ARM-Assembly-Tutorial.md

**Comment by b-mueller** [comment]
hey @azeria-labs, are you still going to add this? I'll remove this chapter otherwise.

**Comment by sushi2k** [comment]
Hi @azeria-labs. Last call :-) Can you please let us know if you are able to write something? Otherwise we remove the chapter and close this ticket next week.

**Comment by azeria-labs** [comment]
Hi! Can I get a Slack invite? :-) I can start working on it next week, but I'd like to discuss how detailed it should be before I start.

**Comment by sushi2k** [comment]
Thanks for coming back to us :-) 
You can register yourself here: https://github.com/OWASP/owasp-mstg/#contributions-feature-requests-and-feedback
Our slack channel is https://owasp.slack.com/messages/project-mobile_omtg/details/

**Comment by b-mueller** [comment]
+ [Slack signup link](http://owasp.herokuapp.com)
