### ISSUE TITLE
0x06b - IntroSpy Howto [iOS]

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#500]
Write a brief howto for API monitoring with IntroSpy:

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06b-Basic-Security-Testing.md#https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06b-Basic-Security-Testing.md

**Comment by Naushad007** [comment]
Running Basic Security Testing on Jailbreaking iOS

**Comment by yog3shsharma** [comment]
Updated the file @ https://github.com/OWASP/owasp-mstg/pull/634/commits/32b9fd2677202d7c1cca818b7b0ed9007fdae032
