### ISSUE TITLE
Write up on Spongey castle versus bouncey castle and the other android security providers [Android]

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#517]
One important topic that has not been covered is the use of security providers and the patching of some of them.
For instance:
- there are various versions of "altered" bouncey-castles delivered with older versions of Android and then there's spongey-castle to fix that, but it will mostly force developers to multi-dex, which is another issue (in 0x05e-Testing-Cryptography.md)
- we need to patch the security provider as https://developer.android.com/training/articles/security-gms-provider.html for your ssl traffic (a new testcase in 0x05g-Testing-Network-Communication.md )
- There is a boatload of security providers in later version of android, we need to inform both developers and pentesters on which ones are important (in 0x05e-Testing-Cryptography.md).

**Comment by commjoen** [comment]
Will create a new chapter in the platform and create a new item in the MASVS first.

**Comment by commjoen** [comment]
Once PR is accepted, I can create content in the MSTG.

**Comment by commjoen** [comment]
I will create a new testcase in 0x05g

**Comment by sushi2k** [comment]
@commjoen: Can we close this ticket? There is still one todo in the test case ""

**Comment by commjoen** [comment]
All todo's are resolved. let's close!
