### ISSUE TITLE
incorrect information on Intent framework 

### ISSUE THREAD

**Issue by ryantzj** [OWASP/owasp-mstg#55]
Hi guys, 

I found that there is a misinformation on Intent framework under topic Android 0x04a. [link](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04a-Android.md#high-level-abstractions)

> Intent messaging is a framework for asynchronous communication built on top of binder. 
> ...
> Although intents facilitate communication between components in several ways, there are three fundamental use cases:
> 
> - Explicit intents specify the component to start by name (the fully-qualified class name).

Intent types were given here instead of uses cases. Below is the use cases written in Android Developer manual. [ source](https://developer.android.com/guide/components/intents-filters.html)

>- Starting an activity
> An Activity represents a single screen in an app. You can start a new instance of an Activity by passing an Intent to startActivity(). The Intent describes the activity to start and carries any necessary data.
> If you want to receive a result from the activity when it finishes, call startActivityForResult(). Your activity receives the result as a separate Intent object in your activity's onActivityResult() callback. For more information, see the Activities guide.
>- Starting a service
> A Service is a component that performs operations in the background without a user interface. With Android 5.0 (API level 21) and later, you can start a service with JobScheduler. For more information about JobScheduler, see its API-reference documentation.
> For versions earlier than Android 5.0 (API level 21), you can start a service by using methods of the Service class. You can start a service to perform a one-time operation (such as downloading a file) by passing an Intent to startService(). The Intent describes the service to start and carries any necessary data.
> If the service is designed with a client-server interface, you can bind to the service from another component by passing an Intent to bindService(). For more information, see the Services guide.
>- Delivering a broadcast
> A broadcast is a message that any app can receive. The system delivers various broadcasts for system events, such as when the system boots up or the device starts charging. You can deliver a broadcast to other apps by passing an Intent to sendBroadcast() or sendOrderedBroadcast().

**Comment by b-mueller** [comment]
Thanks Ryan! Unfortunately this chapter isn't managed by anyone at the moment. Maybe you want to correct this and do a pull request?

**Comment by b-mueller** [comment]
Closing this, thanks for fixing.
