### ISSUE TITLE
[Ready for Review] 0x4b Mobile App Security Testing: Instruction on how to repackage and resign an Android App

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#563]
It should be explained how an Android App can be repackaged and resigned, for example to activate debugging in an App.

**Comment by sushi2k** [comment]
Once content ready, set link https://github.com/OWASP/owasp-mstg/issues/273

**Comment by bugwrangler** [comment]
Activate debug in app looks pretty ordinary scenario, it should be around root detection bypass. I had given talk at AppSec USA. If you want me to write a description, I can prepare with example and share it. Pls confirm.

**Comment by sushi2k** [comment]
It's already there. 

https://github.com/OWASP/owasp-mstg/blob/5a4879e2f814430e037729bce30ba8cf5ab6dcb7/Document/0x05c-Reverse-Engineering-and-Tampering.md#repackaging

If you want have a look at it and let us know via Pull Request if something is missing or wrong or can be done better.
