### ISSUE TITLE
Ambiguous use of the term "black-box testing" in 0x06 Reverse Engineering and Tampering

### ISSUE THREAD

**Issue by banescusebi** [OWASP/owasp-mstg#57]
Under the heading "Why should I bother?" of the following page: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06-Reverse-Engineering-and-Tampering.md
the second reason states "To enhance static analysis in black-box security testing". IMHO this is ambiguous. Static analysis is generally associated with white-box or gray-box testing, because it looks at the source- or byte-code. On the other hand, black-box testing is simply feeding inputs to the app and observing outputs. Is there a page with a definition of black-box testing in the MSTG?

**Comment by b-mueller** [comment]
The terms are used ambiguously throughout the guide. We originally intended for "white-box testing" and "black-box testing" to refer to testing with/without access to the source code, respectively. It seems to me now though that this doesn't make a lot of sense in the context of testing mobile apps. Even if we don't have the original code, we don't do _black-box testing_ in the sense of treating the app as a black-box. Perhaps we shouldn't be using these terms at all in the MSTG, and instead talk about static vs. dynamic analysis (actually it used to be like that in the first place) - and further subdivide static analysis into with/without access to source code?

**Comment by sushi2k** [comment]
Agree. 
Writing the test cases and splitting the verification part into static and dynamic test cases will definitely lead to a more detailed structure of it. This also makes it more clear to the reader what testing strategy can be applied when checking for a test case. 
Black box testing might be confusing and not describing properly the approach, as on a rooted/jailbroken device a lot of things are already possible.

**Comment by sushi2k** [comment]
@banescusebi: Ok if I close this issue? We will switch to the terms dynamic/static analysis instead of Black Box / White Box. Thanks for pointing out and starting the discussion.

**Comment by banescusebi** [comment]
Sure you can close it. However, before you close it, I want to ask one thing about the terms dynamic/static analysis: if an analysis involve both static and dynamic analysis, what do you call it? 

For instance, in IDA Pro the disassembly is first done statically, but each time the program is executed, the disassembly may be updated to reflect paths that could not be disassembled statically. There are also other examples, where you first dynamically execute the code and then search for the output message in the static binary, etc. Would these fall into the category of dynamic analysis?

**Comment by sushi2k** [comment]
In the test cases itself we will have the separation into static and dynamic. What are you describing sounds to me like dynamic analysis, as you are running the App and looking for the output/changes that was/were generated. There might be sometimes edge cases and then they the Lead Author should decide on a case to case basis if it's dynamic or static. 
Thanks again for bringing it up.
