### ISSUE TITLE
Add C++ to NDK languages

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#61]
Could it be worth adding C++ to C? NDK is supporting both languages, and the sentence could be "as a C or C++ binary by using the Android NDK" (cf https://developer.android.com/ndk/guides/index.html)

**Comment by sushi2k** [comment]
Which section are you referring to?

**Comment by romualdszkudlarek** [comment]
Sorry about that : chapter 0x04, Mobile Platforms Overview

**Comment by romualdszkudlarek** [comment]
Sorry about that : chapter 0x04, Mobile Platforms Overview
