### ISSUE TITLE
0x6d Add RSA Encryption to Testing Local Data Storage [iOS]

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#618]
Add RSA Encryption sampel to Remediation section of Test Case "Testing Local Data Storage".
-- [TODO: add key generation for RSA encryption] --

**Comment by righettod** [comment]
Hello,

Do this type of code sample is what you want to add or do you want a more specific sample ?

```java
//Define working variables
String aks = "AndroidKeyStore"; 
String keyAlias = "LocalDataCipheringKey"; 
String dataToProtect = "XXXXX"; 
String algo = "RSA/ECB/PKCS1Padding";

//Use stronger algorithm if target device is >= Android M
if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M){ 
  algo = "RSA/ECB/OAEPWithSHA-512AndMGF1Padding"; 
}

//Load keystore using Android Keys Store
KeyStore keyStore = KeyStore.getInstance(aks); 
keyStore.load(null);

//Generate and save a RSA keypair if the keystore do not already contains it
if (!keyStore.containsAlias(keyAlias)) {
  Calendar cal = Calendar.getInstance(); Date now = cal.getTime(); cal.add(Calendar.YEAR, 1); Date end = cal.getTime();
  KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA", aks);
  kpg.initialize(new KeyPairGeneratorSpec.Builder(getApplicationContext())
  .setKeySize(4096).setAlias(keyAlias).setStartDate(now).setEndDate(end)
  .setSerialNumber(BigInteger.valueOf(1))
  .setSubject(new X500Principal("CN=" + keyAlias)).build());
  KeyPair kp = kpg.generateKeyPair();
}

//Retrieve keypair from the Android Key Store keystore (simulate further key usage)
KeyStore.Entry keyPairEntry = keyStore.getEntry(keyAlias, null); 
KeyStore.PrivateKeyEntry key = (KeyStore.PrivateKeyEntry)keyPairEntry;

//Cipher chunk of data using the asymetric public key that came from the AndroidKeyStore
Cipher cipher = Cipher.getInstance(algo);
cipher.init(Cipher.ENCRYPT_MODE, key.getCertificate().getPublicKey());
byte[] encryptedBytes = cipher.doFinal(dataToProtect.getBytes());
String encodedEncryptedBytes = Base64.encodeToString(encryptedBytes,Base64.DEFAULT);
Log.d("TEST", encodedEncryptedBytes);

//Decipher chunk of data using the asymetric private key that came from the AndroidKeyStore
cipher = Cipher.getInstance(algo);
cipher.init(Cipher.DECRYPT_MODE, key.getPrivateKey());
byte[] decryptedBytes = cipher.doFinal(encryptedBytes);
String decryptedString = new String(decryptedBytes);
Log.d("TEST", "Equals to plaintext? " + (decryptedString.equals(dataToProtect)));
```

Thanks in advance for your feedback.

**Comment by sushi2k** [comment]
This ticket is addressing the iOS test case :-) Do you also have code examples in Objective-C or Swift?

**Comment by commjoen** [comment]
Maybe i am overlooking it as i am usibg the mobile view now. Bit the sample does not contain goals for the keys. Maybe add that too to the java code? And as an option, describe validation of the keys using the KeyInfo?

**Comment by commjoen** [comment]
And it would be nice to provide people guidance on the various padding schemes, the strength/time to wait for a key and the data size to encrypt.

**Comment by righettod** [comment]
@commjoen 
Thanks you for the feedback, so the sample (after reworking using your feedback) is interesting for the project ?

@sushi2k 
Sorry I didn't have one for iOS

**Comment by sushi2k** [comment]
Hi @righettod. Apologies, I thought we already had a code snippet for the usage of the Keystore on Android, but there is none. 
Therefore yes, you're code sample would definitely be very useful. Please create a Pull Request with your proposed changes to "Document/0x05d-Testing-Data-Storage.md" in the remediation part of the local storage test case: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#remediation

Please also make a reference in case part of the code is copied from somewhere else, to make it clear.

**Comment by righettod** [comment]
OK i will take in account all your feedback and provides a PR for this proposal . 

Question: In the guide from which minimum Android version you start ? I ask the question because some method/class about key generation are deprecated between API version like for example the KeyPairGeneratorSpec class is deprecated in API level 23...

**Comment by sushi2k** [comment]
We do not have a minimum version, use the latest best practice available and if there are classes/methods are deprecated you are using in your sample code please point this out.
