### ISSUE TITLE
0x6d Testing for Sensitive Data in Memory [iOS]

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#620]

**Comment by pmilosev** [comment]
@sushi2k is anyone working on this ticket ?
I finished editing same ticket for Android, so I might give this one a try next :)

I'll be able to do some work in a week from now.

**Comment by sushi2k** [comment]
Hi @pmilosev. I added a few things last week to the dynamic part. But if you want you can take over. Just assigned you :-)
