### ISSUE TITLE
Update MASVS references

### ISSUE THREAD

**Issue by Sjord** [OWASP/owasp-mstg#641]
In some places the references to MASVS requirements became incorrect, probably because the MASVS documents were changed. I have identified the following places (using [this script](https://github.com/Sjord/masvs-reference-tool) I wrote) where the MASVS reference should be updated:

- [x] [MASVS V8.3](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x05j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 205
- [x] [MASVS V8.4](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x05j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 1034
- [x] [MASVS V8.10](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x05j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 1454
- [x] [MASVS V8.8](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x05j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 1491
- [x] [MASVS V8.9](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x05j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 1492
- [x] [MASVS V8.12](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x05j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 1493
- [x] [MASVS V4.6](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x09-V4-Authentication_and_Session_Management_Requirements.md) in [0x05f-Testing-Local-Authentication.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05f-Testing-Local-Authentication.md#owasp-masvs) line 125
- [x] [MASVS V8.10](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x06j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 805
- [x] [MASVS V8.12](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md) in [0x06j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#owasp-masvs) line 843
- [x] [MASVS V6.7](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x11-V6-Interaction_with_the_environment.md) in [0x05h-Testing-Platform-Interaction.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05h-Testing-Platform-Interaction.md#owasp-masvs) line 754
- [x] [MASVS V6.8](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x11-V6-Interaction_with_the_environment.md) in [0x05h-Testing-Platform-Interaction.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05h-Testing-Platform-Interaction.md#owasp-masvs) line 858
- [x] [MASVS V6.9](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x11-V6-Interaction_with_the_environment.md) in [0x05h-Testing-Platform-Interaction.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05h-Testing-Platform-Interaction.md#owasp-masvs) line 1078
- [x] MASVS V6.10 in [0x05h-Testing-Platform-Interaction.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05h-Testing-Platform-Interaction.md#owasp-masvs) line 1149
- [x] [MASVS V4.6](https://github.com/OWASP/owasp-masvs/blob/master/Document/0x09-V4-Authentication_and_Session_Management_Requirements.md) in [0x06f-Testing-Local-Authentication.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06f-Testing-Local-Authentication.md#owasp-masvs) line 75

**Comment by sushi2k** [comment]
Thanks @Sjord. I was in the middle of updating a test case in 0x05h-Testing-Platform-Interaction.md  anyway so I updated all MASVS references your script found.
