### ISSUE TITLE
OMTG-DATAST-004: Test Whether Sensitive Data is Sent to Third Parties

### ISSUE THREAD

**Issue by clviper** [OWASP/owasp-mstg#65]
Hi guys.

This test case is inserted inside the Data Storage, but I think is more adequate to move it to the Network Communication.

What do you think?

**Comment by b-mueller** [comment]
It somewhat fits into both categories IMHO - depends how you look at it.

**Comment by clviper** [comment]
At least IMHO this has nothing to do with storage. This relates to information that is sent over the network. It could be information that is correctly secured from the point of view of storage but is being sent to third parties.

**Comment by sushi2k** [comment]
When I was writing this down I was more looking from the perspective of sensitive data that is sent  to some 3rd party, that's why I choose DATAST. But we can also move it to the network section, it's an edge case I guess.

**Comment by b-mueller** [comment]
Closing this - re-categorizing test cases is not a priority right now.
