### ISSUE TITLE
References → Info section

### ISSUE THREAD

**Issue by Sjord** [OWASP/owasp-mstg#683]
Some documents have a "References" section with an "Info" subsection. I think "Info" is not really a good section header. First of all, info is short for information, and we should at least write the whole word. Second, the "references" header already indicates that pointers to more information will follow.

I think the references that don't fit under the CWE, MASVS, etc. headers should go directly under the "References" header, without their own additional header. Like this:

> #### References
> 
> - [#nelenkov] - N. Elenkov, Android Security Internals, No Starch Press, 2014, Chapter 5.
> 
> ##### OWASP MASVS
> - etc.

These sections contain an "Info" header:

* [0x06j-Testing-Resiliency-Against-Reverse-Engineering.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md)
* [0x05e-Testing-Cryptography.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05e-Testing-Cryptography.md)
* [0x05d-Testing-Data-Storage.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md)
* [0x05h-Testing-Platform-Interaction.md](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05h-Testing-Platform-Interaction.md)

**Comment by sushi2k** [comment]
Agree, "Info" should be removed entirely and the content should be placed under References. This is an inconsistency that we have at the moment.

**Comment by sushi2k** [comment]
Fixed https://github.com/OWASP/owasp-mstg/commit/83e2d37fe40874d958fc1378889e66de358dd1e3
