### ISSUE TITLE
0x04e Add dictionary check to password policy section

### ISSUE THREAD

**Issue by Sjord** [OWASP/owasp-mstg#688]
The section on [password policy in 0x04e](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04e-Testing-Authentication-and-Session-Management.md#testing-the-password-policy) mentions length and character classes. What is missing it the practice of checking the password against a dictionary. In that case, the application has a list with unsafe passwords and does not allow setting your password to one that occurs in the list. This makes it possible to disallow "Welcome123!" which would match complexity rules but still wouldn't be a proper password.

[NIST](https://pages.nist.gov/800-63-3/sp800-63b.html) thinks this is a good practice:

> When processing requests to establish and change memorized secrets, verifiers SHALL compare the prospective secrets against a list that contains values known to be commonly-used, expected, or compromised. For example, the list MAY include, but is not limited to:
> 
> -  Passwords obtained from previous breach corpuses.
> -  Dictionary words.
> -  Repetitive or sequential characters (e.g. ‘aaaaaa’, ‘1234abcd’).
> -  Context-specific words, such as the name of the service, the username, and derivatives thereof.
> 
> If the chosen secret is found in the list, the CSP or verifier SHALL advise the subscriber that they need to select a different secret, SHALL provide the reason for rejection, and SHALL require the subscriber to choose a different value.

This can be both more user friendly and more effective against insecure passwords, but still isn't much used in services. I think it deserves a mention in our guide.

**Comment by sushi2k** [comment]
Hey @Sjord. 
I was also thinking about this a while ago, but then I did not put in the test case for several reasons. First of all I don't think that this is more user friendly. If 
- the password is long enough (10 characters)
- a mechanism is in place that addresses brute forcing (e.g. suspend the account for 5 minutes after a threshold is hit, like 5 times a wrong password within 2minutes or a CAPTCHA)
- the password policy is  "strong" as already described in the test case
this is sufficient for most apps and the attack vector of brute forcing a password is simply not there. Even if you get in possession of the hashed password dump, you cannot do much if you use a strong hashing algorithm with a unique salt. 

Enforcing checks like this makes it harder for a user to pick a password. I know they should use a password manager and use random strings with 30 characters, like we do, but that's simply not the reality out there. 

If it's really an app/service that handles sensitive data/functions, they should use 2FA anyway.

**Comment by Sjord** [comment]
The dictionary check is an *alternative* for complexity rules.

We have complexity rules in 0x04e:

> The password must meet at least three out of the following four complexity rules:
> 
> *  at least one uppercase character (A-Z)
> * at least one lowercase character (a-z)
> *  at least one digit (0-9)
> * at least one special character (punctuation)

These rules have the goal to make users pick a hard-to-guess password. To reach that same goal, NIST has another approach: check the password against a dictionary, and don't impose any complexity rules:

> Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets.

An app that follows NIST recommendations isn't necessarily insecure, even if it doesn't have complexity rules. However, this isn't clearly described in 0x04e. The MSTG says you must have complexity rules, and NIST says you shouldn't, and I think we should handle both cases in the guide.

Something like: ensure that the password is hard to guess. This can be done using password complexity rules, or alternatively by checking it against a dictionary.

**Comment by sushi2k** [comment]
Understand. Makes sense. You wanna do a PR for this?

**Comment by b-mueller** [comment]
Adding @romualdszkudlarek, he is gonna add instructions for dictionary attack with BURP.

**Comment by romualdszkudlarek** [comment]
Just made a proposal concerning dictionaries. This issue may be closed.
