### ISSUE TITLE
0x06d-Testing-Data-Storage - Testing for Sensitive Data in the Clipboard

### ISSUE THREAD

**Issue by allRiceOnMe** [OWASP/owasp-mstg#732]
I suggest to add the following to the Overview section within Testing for Sensitive Data in the Clipboard:

Before iOS 9, a malicious app might monitor the pasteboard in the background while periodically retrieving `[UIPasteboard generalPasteboard].string`. As of iOS 9, the access to the pasteboard content is only allowed to apps in the foreground.

However, just a suggestion. Would be nice to see in the guide.

**Comment by sushi2k** [comment]
Please create a PR for it, then we can review it and merge afterwards. Thanks
