### ISSUE TITLE
0x6d - Alternative methods to hide sensitive information in Auto-Generated Screenshots 

### ISSUE THREAD

**Issue by allRiceOnMe** [OWASP/owasp-mstg#737]
There are [other methods](https://appsec-labs.com/portal/ios-i-just-snapshotted-your-credit-card-i-did-it-for-you/) to prevent sensitive information from being captured within auto-generated screenshots. One could consider to add them to the testing guide.

By the way, I was not able to get the provided example by using UIImageView to work.

**Comment by sushi2k** [comment]
Thanks for the suggestion.
Item 3 in the link you shared is exactly the code snippet we have in the MSTG.
Item 2 is already covered in the test case "Testing for Sensitive Data Disclosure Through the User Interface.

Do you want to create a PR for item 1 :-) ?

**Comment by allRiceOnMe** [comment]
@sushi2k The test case for "Testing for Sensitive Data Disclosure Through the User Interface" seems to be empty?!

If you look at the comments in the linked article, the blurring method might be unsafe... Not sure, if it should be added to the test case.
