### ISSUE TITLE
New NIST password guidance

### ISSUE THREAD

**Issue by allRiceOnMe** [OWASP/owasp-mstg#738]
This is a follow-up of issue #688 that has been addressed in PR #723. The PR was merged but the resulting text removed later on (commit 6fd2ba2). My proposal would be to re-add the removed text in order to meet the [NIST guidance](https://pages.nist.gov/800-63-3/sp800-63b.html).

One approach could be the "offline" comparison of the hashes from known as compromised passwords. To be independent from 3rd party services that compares the passwords over the web, the collection of pwned passwords can be downloaded, e.g. from [here](https://haveibeenpwned.com/Passwords).  However, since the files are huge, the check needs to be done in the own backend.

**Comment by sushi2k** [comment]
Sounds good. Do you want to do a PR for this? Thanks
