### ISSUE TITLE
0x05b-Basic-Security_Testing.md on Android - Mentioning Nathan

### ISSUE THREAD

**Issue by whoot** [OWASP/owasp-mstg#790]
Maybe you should consider adding [Nathan](https://github.com/mseclab/nathan) in the "Testing on the Emulator" section.
It combines a VM and different tools, proxy is easy to use too. Therefore you do not need to generate a custom AVD, install tools and so on.

**Comment by b-mueller** [comment]
Sure, we can do that! Care to do a pull request?

**Comment by whoot** [comment]
Done
