### ISSUE TITLE
Android Basic Testing: Add detailed instructions for setting up an interception proxy

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#802]
At the moment, the Android basic security testing only has links to the Portswigger website. Add detailed instructions and screenshots for configuring a proxy and installing a CA certificate.

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05b-Basic-Security_Testing.md#user-content-network-setup

**Comment by xep624** [comment]
I take it. Will update you soon ;)

**Comment by b-mueller** [comment]
Awesome, thanks!

**Comment by xep624** [comment]
Done under PR #822. Awaiting for review.
