### ISSUE TITLE
ProGuard optimizationpasses setting

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#805]
See [feedback on GitBook](https://www.gitbook.com/book/b-mueller/the-owasp-mobile-security-testing-guide/discussions/6).

"in most recent version of proguard assumenosideeffect works only if use -optimizationpasses options."

According to the ProGuard manual, the default number of optimization passes is 1 if this flag isn't set. Did this change with recent versions? We need more detail on this.

For this issue do the following:
- Create an app in Android Studio with a log statement
- Use the configuration for ProGuard from the MSTG to strip logs (https://github.com/OWASP/owasp-mstg/blob/98e7dd94453c4461d0c33f9d7436dee7c797b060/Document/0x05d-Testing-Data-Storage.md#static-analysis-2). If errors are thrown investigate on how to resolve, e.g. usage of optimizationpasses as described above 
- Verify if log statements are stripped and not part of the APK anymore, e.g. by decompiling the app and checking for the log statement or executing the app and verifying the log output

**Comment by lwierzbicki** [comment]
I verified that case. 
I use following setup:
* default Android Studio installation
* application was based on MyFirstApp (https://developer.android.com/training/basics/firstapp) with added `import android.util.Log` and some test Log.v statements
* added rules to proguard-rules.pro as mentioned in [OWASP guide](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#static-analysis-2 "OWASP guide") and in [Proguard guide](https://www.guardsquare.com/en/products/proguard/manual/examples#logging "Proguard guide").
* adjust build.gradle according to [Android shrink-code guide](https://developer.android.com/studio/build/shrink-code "Android shrink-code guide")

As you may noticed I haven't used  -optimizationpasses options. At that point log statements where removed from code (no logcat output, no code after decompiling). 

**Additional output:** 
- name of proguard configuration file mismatch (currently used is `proguard-rules.pro` on https://developer.android.com/studio/build/shrink-code, in OWASP Guide is `proguard-project.txt`)
- example code is currently not valid `Log.v("Private key [byte format]: " + key);` - as it is not containing tag parameter. That should looks like `Log.v("PrivateKey tag","Private key [byte format]: " + key);`
- shrinking log statement from code line like this
`Log.v("sendMessageTEST",new StringBuilder("Sending message:").append(editText.toString()).toString());`
leave some code - after decompiling I found this:
`StringBuilder stringBuilder = new StringBuilder("Sending message:");
 stringBuilder.append(editText.toString());
 stringBuilder.toString();`. That confirms part mentioned in example about possible plain text data leaks to memory. 

**Next step:**
I would add/modify the following:
* correct name of proguard configuration file
* add references to official documentation - Android and Proguard
* correct example (adding parameter to `Log.v`) to make it current

What do you think?

**Comment by commjoen** [comment]
Sound like a plan! Thank you very much @lwierzbicki ! Would you mind creating a PR to fix this :) ?

**Comment by lwierzbicki** [comment]
I will do that.

**Comment by cpholguera** [comment]
Fixed in #1630
