### ISSUE TITLE
Mobile App Security Checklist - Testing Procedure links returns a 404 error

### ISSUE THREAD

**Issue by bstelmack** [OWASP/owasp-mstg#846]
Click any of the "Testing Procedure" links returns a 404 error.  Looks like the path in the URI changed from "owasp-mobile-security-testing-guide" to "the-owasp-mobile-security-testing-guide".

Ex: 
https://b-mueller.gitbooks.io/owasp-mobile-security-testing-guide/content/0x05j-Testing-Resiliency-Against-Reverse-Engineering.html#testing-advanced-root-detection

should be replaced with 

https://b-mueller.gitbooks.io/the-owasp-mobile-security-testing-guide/content/0x05j-Testing-Resiliency-Against-Reverse-Engineering.html#testing-advanced-root-detection

**Comment by b-mueller** [comment]
Hi @bstelmack, the security checklist is quite outdated and it's difficult to keep track because the ToC still changes frequently. We'll revisit this prior to releasing 1.0 (or potentially scrap the Excel sheet entirely).

**Comment by sushi2k** [comment]
The Excel Sheet was updated with links to the latest Gitbook on https://mobile-security.gitbook.io/mobile-security-testing-guide/
