### ISSUE TITLE
Open question for projects references

### ISSUE THREAD

**Issue by righettod** [OWASP/owasp-mstg#872]
Hello,

With Jim Manico we work on the OWASP Cheat Sheet Series project. 

In this project, we have cheat sheet (called CS) about Android and iOS topics. 

https://www.owasp.org/index.php/OWASP_Cheat_Sheet_Series
https://www.owasp.org/index.php/Android_Testing_Cheat_Sheet
https://www.owasp.org/index.php/IOS_Developer_Cheat_Sheet
https://www.owasp.org/index.php/IOS_Application_Security_Testing_Cheat_Sheet

In regards of the amazing work performed for you and your community on the MSTG and MASVS projects, I have suggested to Jim to replace our CS on Android/IOS by references to your projects because they provides precious remediation always up to date information.

As your projects focus on mobile, I think that is more relevant to point to your work for mobile advices.

What do you think?

Thanks you very much in advance for your feedback  :smiley:

**Comment by sushi2k** [comment]
I love that idea and thanks for the kind words. 
I was going through the cheat sheets just now and I think everything is covered in more detail in the MSTG. Therefore please go for it. Thanks again for reaching out to us and let me know if you need any support.

**Comment by righettod** [comment]
You are welcome and it's normal 😃 

We will do in this way and add information about how to obtains supports via the MSTG github project.

**Comment by sushi2k** [comment]
Thanks for the update :-)
