### ISSUE TITLE
Not abe to create document

### ISSUE THREAD

**Issue by pragyan1994** [OWASP/owasp-mstg#873]
\			generate_toc.rb
generate_document.sh	omtg-pre-commit.sh
Tools$: ./generate_document.sh
pandoc: Could not find image `Images/license.png', skipping...
Tools$: 

I get the above error. any idea how to fix it.

**Comment by sushi2k** [comment]
Please use generate_document.sh if you want to generate a Docx. The script you are executing was just used to generate a ToC of the document. The error message your are getting just means it cannot find the license png file, so it's not included in the output. 

```
./generate_document.sh
[WARNING] Deprecated: markdown_github. Use gfm instead.
[WARNING] Could not fetch resource 'Images/license.png': PandocResourceNotFound "Images/license.png"
```
See also:
https://github.com/OWASP/owasp-mstg/#reading-the-mobile-security-testing-guide
