### ISSUE TITLE
0x04b-Mobile-App-Security-Testing 

### ISSUE THREAD

**Issue by stivalet** [OWASP/owasp-mstg#876]
Mobile App Security Testing --> Principles of Testing --> Avoiding False Positives:

For consistency purposes in the document, i would suggest to edit the sentence "Stored Cross-Site Scripting (CSS)" to "Stored Cross-Site Scripting (**XSS**)"

**Comment by sushi2k** [comment]
Thanks. CSS definitely means something else ;-) https://github.com/OWASP/owasp-mstg/commit/613df2caf354b938ecc46e3c1ddf840431286ad1
