### ISSUE TITLE
0x04h-Testing-Code-Quality

### ISSUE THREAD

**Issue by stivalet** [OWASP/owasp-mstg#878]
Testing Code Quality -> Memory Corruption Bugs
 -> Buffer and Integer Overflows

There is a duplicate of "strlcat" in the example given for the unsafe string functions.

**Comment by sushi2k** [comment]
Thanks. Just fixed it. Can you please make a pull request next time. Then it's easier for us to manage such requests and it only need to be merged. 

Thanks
