### ISSUE TITLE
Anti Kernel Hooking Mitigation

### ISSUE THREAD

**Issue by shuber1** [OWASP/owasp-mstg#880]
There seems to be a technique to mitigate/detect syscall hooking as described in section 0x05c-Reverse-Engineering-and-Tampering. The promon shield  somehow uses ptrace to hook syscalls and then is able to detect a syscall hook from kernel layer. Currently did not understand how it works in detail. Is there any detailed description or example of this approach documented ?

**Comment by TheDauntless** [comment]
_Thinking out loud, and native is not my strongest area of expertise_

Depends on how you implement your hooks. If you create a custom kernel module that changes your syscalls, I doubt you can ever detect this.

On the other hand, if you use tools such as Frida to hook them, I think it would make changes in the apps' virtual function table (VFT) at runtime, which could be detected. I'm not sure if you can know if the initial values are modified though (maybe they no longer point to the correct memory region?), which is what would happen with something as frida spawn.

**Comment by joscandreu** [comment]
This kind of check is doable, just look at how rootkit detectors work, for instance: https://github.com/dgoulet/kjackal/blob/master/src/syscall.c
This should detect the tampered syscall function if the hook is done in a similar way as it is explained in the OWASP-MSTG, that is, swapping the pointers to the syscall functions.

**Comment by commjoen** [comment]
Hi @shuber1 , while cleaning up older issues, I saw this issue still being open. Were the responses in this issue satisfying enough to close this issue?

**Comment by shuber1** [comment]
Can close it.


Am Mittwoch, 25. September 2019 schrieb Jeroen Willemsen <
notifications@github.com>:
