### ISSUE TITLE
If you don't implement MASVS-R, The Excel checklist fails to calculate a MASVS compliance score.

### ISSUE THREAD

**Issue by meetinthemiddle-be** [OWASP/owasp-mstg#881]
In the Management Summary tab, the percentace calculator for V8 should take into account that all items could be N/A (e.g. when you aren't implementing MASVS-R). Now this triggers a #DIV/0! error, also resulting in the MASVS compliance score not being calculated. This could be avoided by adjusting the formula to set the percentage to 0 when there would be a division by zero:

Current:
=D50/(E50+D50)

Better
=IF(550+D50=0; 0; D50/(E50+D50))

**Comment by sushi2k** [comment]
Thanks. I just added it.
