### ISSUE TITLE
Apps are checking Proxy Settings

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#896]
Some financial mobile Apps nowadays check the local proxy settings. If a proxy is set the app is not sending any requests. 

Describe:
- how to make a test setup by using an Access Point 
- Hock the method with Frida

**Comment by godzillahacker** [comment]
https://stackoverflow.com/questions/10811698/getting-wifi-proxy-settings-in-android

**Comment by commjoen** [comment]
@clviper what is the status of this?

**Comment by commjoen** [comment]
It might be a good idea to add that indeed having a proxied connection should be risky if no pinning is enabled.
