### ISSUE TITLE
Typo In Testing Data Storage on Android

### ISSUE THREAD

**Issue by jssomerville** [OWASP/owasp-mstg#903]
In Dynamic Analysis part of the 'Testing Data Storage on Android' section, there is a typo in the link to the secure-preferences github page.  It says 'recure' instead of 'secure'.

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#dynamic-analysis

**Comment by sushi2k** [comment]
Thanks for pointing it out! Fixed
