### ISSUE TITLE
Backup Conversion to tar does not work on OSX

### ISSUE THREAD

**Issue by jssomerville** [OWASP/owasp-mstg#905]
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#dynamic-analysis-7

**Comment by sushi2k** [comment]
What exactly does not work? Is dd not working, or abe.jar, or both?

**Comment by jssomerville** [comment]
Sorry for not elaborating!
openssl on MacOS does not have a zlib command.  There are work-arounds, but they include installing openssl from source and building with zlib.

**Comment by sushi2k** [comment]
Ok. Usually it should run out of the box, you only need abe.jar. Can you please explain which command wasn't working and what error you were getting?

**Comment by jssomerville** [comment]
Right, sorry about the confusion.  This may be a non-issue after all.
When running `dd if=mybackup.ab bs=24 skip=1|openssl zlib -d > mybackup.tar`, I get the error `openssl:Error: 'zlib' is an invalid command.` on Mac OS High Sierra.

**Comment by sushi2k** [comment]
Ok. Otherwise just try abe.jar, as explained in the test case. 
I will close this issue now. 
Let us know if you still face issues. Thanks
