### ISSUE TITLE
Create issues to update MSTG given Android P & Oreo

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#910]
Android Oreo is alive and Android P's SDKs will be out soon. Some rewriting is required given the Oreo update and we might have to update again in Q3 given Android P.

**Comment by commjoen** [comment]
Other related topic to discuss might be:
- https://developer.android.com/guide/topics/text/autofill 
- other new frameworks
- Firebase integrations, etc.

**Comment by sushi2k** [comment]
We should create issues for each test case that might need an update, for example like this one https://github.com/OWASP/owasp-mstg/issues/895. 
Let's indicate the source that explains the new security feature/change and also where in the guide this information should be placed.

**Comment by commjoen** [comment]
For Oreo & P together we have the following changes:
1. https://developer.android.com/work/versions/Android-8.0 &  https://developer.android.com/preview/work - android Enterprise (do we want to add this?)
2. https://developer.android.com/about/versions/oreo/background - broadcast limitations & background service limitations (changing the way you can behave as a rogue app)
3. https://developer.android.com/about/versions/oreo/android-8.1#go GO edition of android. Do we want to start including this?
4. https://developer.android.com/guide/topics/text/autofill & https://developer.android.com/preview/features/autofill autofill (And security implications)
5. https://developer.android.com/guide/webapps/managing-webview webview updates
6. https://developer.android.com/about/versions/oreo/android-8.1 safebrowsing
7. https://developer.android.com/about/versions/oreo/android-8.1 shared memory
8. https://developer.android.com/about/versions/oreo/android-8.1 & https://developer.android.com/preview/features/security fingerprint updates
9. https://developer.android.com/about/versions/oreo/android-8.1 & https://developer.android.com/preview/features/security cryptography updates
10. https://developer.android.com/preview/features/security Android protection confirmation
11. https://developer.android.com/preview/features/security hardware sec module support
12. https://developer.android.com/preview/features/security secure key import
13. https://developer.android.com/preview/features/security decrypt on secure ulnocked devices only
14. https://developer.android.com/preview/features/security-behav & https://developer.android.com/about/versions/oreo/android-8.0-changes TLS changes
15. https://developer.android.com/about/versions/oreo/android-8.0-changes alert windows changs
16. https://developer.android.com/about/versions/oreo/android-8.0-changes unknown sources
17. https://developer.android.com/about/versions/oreo/android-8.0-changes privacy & permissions
18. https://developer.android.com/about/versions/oreo/android-8.0-changes classloaders
19. https://developer.android.com/about/versions/oreo/android-8.0-changes native app-wrapping

**Comment by commjoen** [comment]
All issues have been approved by @sushi2k and new issues are created and added to project 2

**Comment by commjoen** [comment]
@sushi2k , can you please help with the issues created so we can establish the right chapters to update?

**Comment by commjoen** [comment]
All items have been reviewed together with @sushi2k  and have been prioritized.
