### ISSUE TITLE
gramma mistake in 0x04b-Mobile-App-Security-Testing.md

### ISSUE THREAD

**Issue by h4sh5** [OWASP/owasp-mstg#912]
"Infrastructure as Code is based on the use of tools and automation to fasten the provisioning process and **make is more reliable and repeatable**"

Should be "make it more reliable and repeatable".

**Comment by sushi2k** [comment]
Thanks it's fixed. Please consider doing a Pull Request next time, then you can contribute and it's easy to do QA. 

https://github.com/OWASP/owasp-mstg/commit/61c8fc596eb17e4629daae28b68950e4ceee2827
