### ISSUE TITLE
0x06c wrong security command

### ISSUE THREAD

**Issue by kysokzla** [OWASP/owasp-mstg#920]
Command for listing codesigning profiles is now invalid, tested on 2 os x's.
As written: security find-identity -p codesigning -v
As working: security find-identity  -v

**Comment by sushi2k** [comment]
Tested on macOS High Sierra 10.13.3, and I get the same output:

![untitled](https://user-images.githubusercontent.com/5951320/42666503-28e0d5ba-8678-11e8-9c94-2eae5a056661.png)

Did you get an error or what was the problem for you?

**Comment by sushi2k** [comment]
I just changed it to the shorter command, as it's the same output .

https://github.com/OWASP/owasp-mstg/commit/8a4002a70ae042ce06ba46be6c6dc9d151a25ff0
