### ISSUE TITLE
MASVS 3.3: Config of crypto missing for iOS

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#923]
MASVS 3.3: The app uses cryptographic primitives that are appropriate for the particular use-case, configured with parameters that adhere to industry best practices.

See Android test case https://mobile-security.gitbook.io/mobile-security-testing-guide/android-testing-guide/0x05e-testing-cryptography

- [x] Update the Android section on the security provider given https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html
- [x] Update the Android section based on https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
- [x] Update the Android section based on https://developer.android.com/about/versions/oreo/android-8.1
- [x] Update the iOS section given:
- [x] https://www.apple.com/business/site/docs/iOS_Security_Guide.pdf
- [x] https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys
- [x] ttps://developer.apple.com/library/archive/documentation/Security/Conceptual/cryptoservices/Introduction/Introduction.html
- [x] https://developer.apple.com/documentation/cryptotokenkit
- [x] Next, take care of #922

**Comment by commjoen** [comment]
1. Update the Android section on the security provider given https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html 
2. Update the Android section based on https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
3. Update the Android section based on https://developer.android.com/about/versions/oreo/android-8.1
4.

**Comment by commjoen** [comment]
Next, take care of #922
