### ISSUE TITLE
MASVS 7.2 is missing for iOS

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#929]
MASVS 7.2: The app has been built in release mode, with settings appropriate for a release build (e.g. non-debuggable).

See Android Test Case: https://mobile-security.gitbook.io/mobile-security-testing-guide/android-testing-guide/code-quality-and-build-settings-for-android-apps#determining-whether-the-app-is-debuggable

**Comment by TheDauntless** [comment]
test

**Comment by sushi2k** [comment]
Hi @shwetajoshi26. Any update on this ticket?

**Comment by commjoen** [comment]
@shwetajoshi26 any updates?

**Comment by commjoen** [comment]
The app should have:
- recommended compiler settings enabled (Stack canary, etc.)
- not be debuggable,

**Comment by romualdszkudlarek** [comment]
@sushi2k I've just initiated a proposal (PR #1086 ). Feel free to develop it :-)

**Comment by commjoen** [comment]
Merged it to OWASP:929/debugging and will continue there today
