### ISSUE TITLE
Finished Russian translation of iOS related chapters.

### ISSUE THREAD

**Issue by kysokzla** [OWASP/owasp-mstg#934]
Please advise how to act further. Created pull request.

**Comment by commjoen** [comment]
Hi there, so the pull request has been merged, but new commits have come, so now I guess the best way would be to update the translation after every tagged release. So once 1.1 is done, we can see the changes and translate them again. Does that make sense?

**Comment by sushi2k** [comment]
Hi @kysokzla. Any update on the russian translation of the MSTG? Is this something you want to continue working on?

**Comment by kysokzla** [comment]
@sushi2k i've corrected some typos , but didn't pull. Have no time for now. Maybe in future i would continue, but idea of writing main content seems more interesting because many topics could be improved. But again lack of time ...
