### ISSUE TITLE
Android Oreo change: android GO edition

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#942]
With Android GO edition, a lot will change in terms of the need for hardware. Time to get it into the general section of the MSTG! https://developer.android.com/about/versions/oreo/android-8.1#go

**Comment by cpholguera** [comment]
Is this relevant when applying the MASVS security controls? I have the feeling that this is more information "for developers" and, in that case, I'd close it.

_"We’ve updated the building for billions guidelines with additional guidance on how to optimize your app for devices running Android Oreo (Go edition). For most developers, optimizing your existing APK or using Google Play’s Multiple APK feature to target a version of your APK to low-RAM devices is the best way to prepare for devices running Android Oreo (Go edition). Remember that making your app lighter and more efficient benefits your whole audience, regardless of device."_

**Comment by commjoen** [comment]
The only think I want to cover here is, that when downsizing your application, you should take lightweight, but still effective controls and not remove the main controls out of your "fat" application. This can be as simple as extending the instant-apps with a notification Go based apps i guess...
