### ISSUE TITLE
Android Oreo & P updates: changes in cryptography

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#947]
There have been nice updates for Android O & P in terms of how cryptography is handled: more hmacs and ciphers! Time to update the MSTG at the cryptography for Android.
 https://developer.android.com/about/versions/oreo/android-8.1 & https://developer.android.com/preview/features/security
https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html 
https://developer.android.com/training/articles/keystore

**Comment by commjoen** [comment]
Part of it is now dealt with while updating to #923 as we are revisitng the android parts in there as well a little bit.

**Comment by commjoen** [comment]
It seems that all code should be checked for providerSelection. BC/SC recommendations should be removed and the urge for patching the security provider should be stringently underlined.

**Comment by commjoen** [comment]
note: we should incldue better key derivation functions, etc. as well..

**Comment by commjoen** [comment]
Todo:
- [ ] update crypto/signing recommendations for android (what not to use and what to use)
- [ ] update key derivation functions (recommend right ones, derecommend wrong/sweaker ones)
- [ ] verify that provider selection is no longer recommended anywhere
- [ ] keychain and keystore (key goal) updates (E..g what to use and what not to use)

**Comment by lwierzbicki** [comment]
If it is still valid, I could investigate the case and submit PR (and you can assign this issue to me)

**Comment by cpholguera** [comment]
Assigned, thanks @lwierzbicki ;)

**Comment by lwierzbicki** [comment]
Provider selection (for BC and SC) is only mentioned in 0x05d-Testing-Data-Storage.md (in Older Android, when Android Keystore was not available). I would leave it as it is then. Additionally, I would move whole section about Keystore&Keychain from 0x05d-Testing-Data-Storage.md to 0x05e-Testing-Cryptography.md (and left only reference that this is described in Cryptography).

In 0x05e-Testing-Cryptography.md - I think -  there is a need to organize the content - as through all Testing section we use Keystore, Key Generation and other cryptography features). I would gather and move it at the bottom in Overview section (with recommendation what to use and what not) and then went through Testing guides. This will lead to serious redesign of that chapter.

Proposed structure is:
```
### Overview
#### Recommendation & Best practices
#### Keystore
#### Keychain
#### Key generation
#### PRNG


### Testing (...) - iterate through all testing points, same structure
#### Static Analysis
#### Dynamic Analysis
```

What do you think about that? Should I proceed?

**Comment by cpholguera** [comment]
Hi @lwierzbicki, thanks for analyzing the content and suggesting those structural changes. We'll evaluate them and let you know about how to proceed ;)

**Comment by sushi2k** [comment]
Hi @lwierzbicki. We are ok with the restructuring as proposed by you, please consider for this PR also
- ticket #949 
- to-do list for restructuring: https://github.com/OWASP/owasp-mstg/issues/949#issuecomment-522730843
- to-do list for restructuring: https://github.com/OWASP/owasp-mstg/issues/947#issuecomment-522726281

**Comment by lwierzbicki** [comment]
I will consider these two issues (and their comments) in my PR. Could you assign me to #949 as well?
