### ISSUE TITLE
Android P update: hardware security module support

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#949]
With android P the hardware security module support has improved. Time to update data protection and cryptography chapter! https://developer.android.com/preview/features/security

**Comment by commjoen** [comment]
Include titan and thr Android blog about it

**Comment by commjoen** [comment]
- [ ] cover strongbox (And the requirement for a fallback for older devices
- [ ] cover titan in terms of programmatic interaction if necessary.

**Comment by cpholguera** [comment]
@lwierzbicki thanks, we'll assign this to you as well

**Comment by cpholguera** [comment]
For some reason GitHub doesn't allow right now to assign it, your name is not appearing on the list. I'll investigate this.
