### ISSUE TITLE
Android Oreo change: Alert windows

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#953]
With Android Oreo, alert windows behavior changed. This also needs a bit of investigation and writeup so testers can explain when and why this might be a good idea. If there are tangible security outcomes, let's update the Android platform interaction chapter https://developer.android.com/about/versions/oreo/android-8.0-changes

Next, we need to warn people about the overlay attacks as part of this issue (for Android).

**Comment by cpholguera** [comment]
If security-relevant, add after #1642 to complement MSTG-PLATFORM-9.

**Comment by cpholguera** [comment]
I've included a suggestion in #1642 which will close this, @commjoen @sushi2k please review.

https://github.com/OWASP/owasp-mstg/pull/1642#discussion_r418610302
