### ISSUE TITLE
Upgrade all swift code to Swift 5

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#961]
We need to update all swift code to Swift 4.1, so that it is consistent and understandable for people who just switched to Swift development.

**Comment by commjoen** [comment]
@funky-monkey will help in here. Welcome to the team!

**Comment by funky-monkey** [comment]
Thanks! I'll have a look and see if i am able to help out

**Comment by sushi2k** [comment]
Hey @funky-monkey. You just got an invite from Github. Please accept then I assign this ticket for you. Thanks for the support!

**Comment by sushi2k** [comment]
It's all yours :-)  Thanks for your help!

**Comment by sushi2k** [comment]
Hi @funky-monkey. Any update for this ticket? Are you still interested in adding Swift source code? It should also be now Swift 4.2 instead of 4.1

**Comment by funky-monkey** [comment]
Yes still interested. I’ll pick this up asap

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by funky-monkey** [comment]
Hi @sushi2k, @commjoen,

A lot has changed in my personal life and I need to focus on other things. I'm a little sad I can't pick this up. I hope you can find someone else to make this shine.

Cheers, 
Sidney

**Comment by commjoen** [comment]
No worries! We will look for a new volunteer :)

**Comment by commjoen** [comment]
So with swift 5 we have to update it again ;-)

**Comment by commjoen** [comment]
Still looking for a volunteer!

**Comment by commjoen** [comment]
Assigned for @cak. Welcome aboard!

**Comment by cpholguera** [comment]
Hi @cak , could you start working on this one as well? Please let us know, thanks!

**Comment by cak** [comment]
Hey @cpholguera, yes, I will make another pass. I need to add references to Combine (and SwiftUI) where relevant as well.

**Comment by cpholguera** [comment]
Awesome. Thanks a lot for the quick response!
