### ISSUE TITLE
Add Kotlin snippets for Android 

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#962]
Many projects move to kotlin. So let's add s o me snippets in there to support the modern mobile dev!

**Comment by cpholguera** [comment]
Hi @B3nac , @commjoen , what's still open here? Any updates on progress?

**Comment by B3nac** [comment]
Hi @cpholguera I was really busy and ran out of time to work on this. Not sure if Kotlin examples are still needed. Please let me know. Cheers!

**Comment by cpholguera** [comment]
Hi @B3nac yes definitely, there are plenty of code snippets still only in Java. However, we don't have to target all of them at once. It would be great if you could help us go step by step whenever you have some time. Maybe someone else also wants to participate on this, we can all on the Slack channel :)

**Comment by B3nac** [comment]
Hi @cpholguera that sounds great! I'll sign back into the Slack channel later today :]

**Comment by B3nac** [comment]
Hi @cpholguera I've finally made some progress. #1766 :)
