### ISSUE TITLE
Explain danger of sms as a 2nd factor 

### ISSUE THREAD

**Issue by commjoen** [OWASP/owasp-mstg#963]
In https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04f-Testing-Network-Communication.md#making-sure-that-critical-operations-use-secure-communication-channels we need to elaborate on the danger of sms forwarding . Same holds for the authentication chapter.

**Comment by NamiShuri** [comment]
I'd like to help tackle this issue.

**Comment by commjoen** [comment]
Please accept the invite link send to you, so we can assign it to you :).

**Comment by NamiShuri** [comment]
I have made changes and it looks like you all can see them but I am not 100% sure. Please let me know if you have any issues. I apologize in advance.

**Comment by commjoen** [comment]
This can be closed now. Thank you @NamiShuri ! Feel free to pick up your next issue ;-). Let us know via Slack or Github what you want to do next :).
