### ISSUE TITLE
Update OWASP Wiki Page 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#968]
https://www.owasp.org/index.php/OWASP_Mobile_Security_Testing_Guide

Update the wiki page and align to the latest developments.

**Comment by commjoen** [comment]
See https://www.owasp.org/index.php/OWASP_Mobile_Security_Testing_Guide ... I have updated quiet some stuff: you can only do source-edits unfortunately ATM. Do we need something else?

**Comment by commjoen** [comment]
@sushi2k All that is left is to put a thank you message of Bernhard leaving the project and me joining... Anything else? When was the official leave of Bernhard?

**Comment by commjoen** [comment]
Wiki is updated. We can close this now.
