### ISSUE TITLE
"Basic Security Testing / Reverse Engineering and Tampering" Chapters Restructuring

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#970]
As I was reviewing the chapters on Android and iOS Basic Security Testing / Reverse Engineering and Tampering (0x5b/5c and 0x6b/6c), I found that sometimes they are a bit mixed-up. In addition, if you read one and then go to the other you will find a completely different structure. 

![owasp_mstg_issues6b_6c 002](https://user-images.githubusercontent.com/29175115/44062945-c8919140-9f5e-11e8-8339-c590d2c6bdc4.jpeg)
![owasp_mstg_issues6b_6c 003](https://user-images.githubusercontent.com/29175115/44062979-e5b9c5e4-9f5e-11e8-82f7-5b63aea10089.jpeg)
![owasp_mstg_issues6b_6c 004](https://user-images.githubusercontent.com/29175115/44062980-e5d2cc24-9f5e-11e8-9376-6a92e0254db9.jpeg)
![owasp_mstg_issues6b_6c 005](https://user-images.githubusercontent.com/29175115/44062982-e5edb264-9f5e-11e8-97f9-a6e64f01bbc7.jpeg)

Of course the way we perform the testing on the different platforms is completely different but at the end, _what we want to do_ is the same. The proposed unified structure for both chapters should:

- Be consistent by
  - Avoiding repetition of some specific content (e.g. Installing Frida, Setting up the Android SDK)
  - Avoiding mixing of general content like Static/Dynamic Analysis (present on both sections)
  - Adding missing content (e.g. "app folder structure", "copying app data files" are only present in the iOS chapters)
- Provide a clear methodology / way-to-go for both platforms that will facilitate the first reading and the further reading of the other platform (e.g. I already learn the organized approach in 0x5b/5c and I want to start with iOS by reading 0x6b/6c. With the new structure I directly find what I may expect, i.e. the same structured way-to-go, after reading 0x5b/5c).
- Revise tools that might be outdated, (e.g. ipainstaller) and add new tools or techniques (e.g. r2frida).
- Relate to 0x4b (Mobile App Security Testing) and 0x4c (Tampering and Rev.Eng.)

At the end, as a mobile security tester, I normally _want to do the same_: work on a device with root access, get a shell, install apps, reverse apps, patch, debug, inject code, trace/dump stuff, access files, ...

Based on all of the previous points I have crafted the structure as a first draft that I would like to discuss with you. This could be implemented in several steps / tickets one per chapter, that would re-structure and re-organize them keeping all the current content, removing duplicates and adding the new stuff.

Here are the proposed outlines for the four chapters:

**Comment by commjoen** [comment]
Thank you for the wonderful description of the issue! Is it ok if can can have a call first?

**Comment by commjoen** [comment]
Scheduled to be taken care of during the OSS2019! https://open-security-summit.org/working-sessions/mobile/restructure/

**Comment by commjoen** [comment]
Don't forget to update the excel after this :)

**Comment by TheDauntless** [comment]
Will we move to make a direct link between MASVS and MSTG? Just like ASVS and the security testing guide?

For a very large part of the content, this would make good sense.

**Comment by commjoen** [comment]
I think having direct links (excel file? and masvs?) will make sense. Moreover, some of the stuff is still os-dependent, while it might make more sense to say that these items can be written for both os's as well. The challenge is still a bit for some of the content: where should it go to (for instance: teh static analysis which should be moved out: where to?)

**Comment by commjoen** [comment]
what i think is still pretty important, is to keep the restructuring as fast and as painless as possible: let's first reuse existing content and restructure BEFORE we are going to write a lot of new content :),. this way other people adding content will not introduce a lot of merging conflicts.

**Comment by commjoen** [comment]
Can we close this?

**Comment by cpholguera** [comment]
We cannot close it yet. We've only covered the "Basic Security Testing"
chapters on PRs #1220 and #1222. Now we still have to target the RE
chapters on two new PRs.

**Comment by TheDauntless** [comment]
I'm aligning iOS and Android from a structure point of view

**Comment by commjoen** [comment]
@cpholguera : can we now close this issue :D ?

**Comment by cpholguera** [comment]
Yes! We finally made it :D

**Comment by commjoen** [comment]
Congratulations!!! YOU and the team worked hard on this one! Finally!!!!! Whooohoooo!
