### ISSUE TITLE
Crackme Android 01 : Typo in the root-detection notification

### ISSUE THREAD

**Issue by meetinthemiddle-be** [OWASP/owasp-mstg#992]
**Describe the bug**
When running the crackme on a rooted device, the app displays a pop-up that says 'This **in** unacceptable', which should be 'this **is** unacceptable'

**crackme or other challenge**
Android 01

**To Reproduce**
1. Install the app on a rooted device, run it and observe the text in the pop-up

**Comment by commjoen** [comment]
New PR created, can you plase check @meetinthemiddle-be ? it is #994 .

**Comment by commjoen** [comment]
Thanks!
